// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

bool item;
int _taster_B = 2;
void setup()
{
    Serial.begin(9600); 
    pinMode(_taster_B, INPUT);
    item = digitalRead(_taster_B);
}

void loop()
{
}