// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

bool item;
int _output_M = 7;
void setup()
{
    Serial.begin(9600); 
    pinMode(_output_M, INPUT);
    item = digitalRead(_output_M);
}

void loop()
{
}