// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <SPI.h>
#include <MFRC522.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

String item;
bool item2;
#define SS_PIN_R 9
#define RST_PIN_R 10
MFRC522 _mfrc522_R(SS_PIN_R, RST_PIN_R);
String _readRFIDData()
{
    if(!_mfrc522_R.PICC_IsNewCardPresent()) 
    {
        return "N/A";
    }
    if(!_mfrc522_R.PICC_ReadCardSerial())
    {
        return "N/D";
    }
    return String(((long)(_mfrc522_R.uid.uidByte[0])<<24)
    |((long)(_mfrc522_R.uid.uidByte[1])<<16)
    | ((long)(_mfrc522_R.uid.uidByte[2])<<8)
    | ((long)_mfrc522_R.uid.uidByte[3]), HEX);
}

void setup()
{
    Serial.begin(9600); 
    SPI.begin();
    _mfrc522_R.PCD_Init();
    item = _readRFIDData();
    item2 = _mfrc522_R.PICC_IsNewCardPresent();
}

void loop()
{
}