// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <IRremote.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

bool item;
int _RECV_PIN_I = 11;
IRrecv _irrecv_I(_RECV_PIN_I);
decode_results _results_I;
bool _getIRResults()
{
    bool results = false;
    if (_irrecv_I.decode(&_results_I)) {
        results = true;
        _irrecv_I.resume();
    }
    return results;
}

void setup()
{
    Serial.begin(9600); 
    pinMode(13, OUTPUT);
    _irrecv_I.enableIRIn();
    item = _getIRResults();
}

void loop()
{
}