// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

double item;
int _led_L = 13;
unsigned long __time = millis();

void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    item = (int) (millis() - __time);
}

void loop()
{
    __time = millis();
}