// This file is automatically generated by the Open Roberta Lab.

#define ANALOG2PERCENT 0.0978

#include <math.h>
#include <MeMCore.h>
#include <Wire.h>
#include <SoftwareSerial.h>
#include <MeDrive.h>
#include <NEPODefs.h>
#include <RobertaFunctions.h>

MeUltrasonicSensor _meUltraSensor3(PORT_3);
MeLineFollower __meLineFollower2(PORT_2);
MeLightSensor _meLight6(PORT_6);
MeLightSensor _meLight2(PORT_2);
RobertaFunctions rob;

double item;
bool item2;

unsigned long __time = millis();

void setup()
{
    Serial.begin(9600); 
    item = 0;
    item2 = true;
}

void loop()
{
    item = _meUltraSensor3.distanceCm();
    item2 = (analogRead(PORT_7) < 512);
    item2 = __meLineFollower2.readSensor1();
    item = _meLight6.read() * ANALOG2PERCENT;
    item = _meLight2.read() * ANALOG2PERCENT;
    item = (int) (millis() - __time);
    __time = millis();
}