alter table USER add ACTIVATED boolean default false not null;
alter table USER add YOUNGER_THAN_14 boolean default false not null;

create table PENDING_EMAIL_CONFIRMATIONS (
    ID INTEGER not null generated by default as identity (start with 1),
    USER_ID INTEGER not null,
    URL_POSTFIX varchar(255),
    CREATED timestamp not null,
    
    primary key (ID),
    foreign key (USER_ID) references USER(ID) ON DELETE CASCADE
);

insert into USER
(ID, ACCOUNT, PASSWORD, EMAIL, ROLE, CREATED, LAST_LOGIN, TAGS, USER_NAME, ACTIVATED, YOUNGER_THAN_14)
values (2, 'Gallery','f17a0084220e822e:313c4eda282166163f78cd0b13da3b66f5ed6a0e','','TEACHER',now ,now ,'','The Gallery', true, false
);
commit;