// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <math.h>
#include <RobertaFunctions/NEPODefs.h>


int _spiele_B = 5;
void setup()
{}

void loop()
{
    tone(_spiele_B,300, 100);
}