// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

unsigned int item;
unsigned int item2;
unsigned int item3;
int _led_red_R = 5;
int _led_green_R = 6;
int _led_blue_R = 3;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_red_R, OUTPUT);
    pinMode(_led_green_R, OUTPUT);
    pinMode(_led_blue_R, OUTPUT);
    item = RGB(0xFF, 0xFF, 0xFF);
    item2 = item;
    item3 = RGB(120, 120, 120);
}

void loop()
{
    analogWrite(_led_red_R, 204);
    analogWrite(_led_green_R, 0);
    analogWrite(_led_blue_R, 0);
    
    analogWrite(_led_red_R, RCHANNEL(item));
    analogWrite(_led_green_R, GCHANNEL(item));
    analogWrite(_led_blue_R, BCHANNEL(item));
    
    analogWrite(_led_red_R, 120);
    analogWrite(_led_green_R, 120);
    analogWrite(_led_blue_R, 120);
    
    analogWrite(_led_red_R, 0);
    analogWrite(_led_green_R, 0);
    analogWrite(_led_blue_R, 0);
    
}