// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <math.h>
#include <Stepper/src/Stepper.h>
#include <RobertaFunctions/NEPODefs.h>


int _SPU_S2 = 2048;
Stepper Motor_S2(_SPU_S2, 6, 5, 4, 3);
void setup()
{}

void loop()
{
    Motor_S2.setSpeed(10);
    Motor_S2.step(_SPU_S2*(5));
}