// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <LiquidCrystal_I2C/LiquidCrystal_I2C.h>
#include <NEPODefs.h>


LiquidCrystal_I2C _lcd_L(0x27, 16, 2);
void setup()
{
    _lcd_L.begin();
}

void loop()
{
    _lcd_L.setCursor(0,1);
    _lcd_L.print("Hallo");
    _lcd_L.clear();
}