// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <Servo.h>
#include <NEPODefs.h>


Servo _servo_S;
void setup()
{
    _servo_S.attach(8);
}

void loop()
{
    _servo_S.write(90);
}