// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

int _spiele_B = 5;
void setup()
{
    Serial.begin(9600); 
}

void loop()
{
    tone(_spiele_B,300, 100);
}