// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <NEPODefs.h>


int _buzzer_B = 5;
void setup()
{}

void loop()
{
    tone(_buzzer_B,300, 100);
    delay(100);
}