// This file is automatically generated by the Open Roberta Lab.

#define ANALOG2PERCENT 0.0978

#include <MeMCore.h>
#include <MeDrive.h>
#include <NEPODefs.h>

MeIR _meIr;

String ___header;
String ___temp;

void setup()
{
    Serial.begin(9600); 
    ___header = "my_message: ";
    ___temp = "";
}

void loop()
{
    for (int ___i = 1; ___i < 10; ___i += 1) {
        _meIr.sendString(___header);
        ___temp += String(___i);
        _meIr.sendString("number is: ");
        _meIr.sendString(___temp);
        delay(1);
    }
    for (int ___j = 1; ___j < 10; ___j += 1) {
        ___temp = _meIr.getString();
        Serial.println(___temp);
        delay(1);
    }
}
