// This file is automatically generated by the Open Roberta Lab.
#define _ARDUINO_STL_NOT_NEEDED
#include "SenseBoxMCU.h"
#undef max
#undef min
#include <NEPODefs.h>

unsigned int ___item;
unsigned int ___item2;
int _led_R2 = 8;
int _buzzer_B = 5;
int _led_red_R = 1;
int _led_green_R = 2;
int _led_blue_R = 3;
int _led_L = 4;
int _led_R1 = 7;

void setup()
{
    pinMode(_led_R2, OUTPUT);
    pinMode(_led_red_R, OUTPUT);
    pinMode(_led_green_R, OUTPUT);
    pinMode(_led_blue_R, OUTPUT);
    pinMode(_led_L, OUTPUT);
    pinMode(_led_R1, OUTPUT);
    ___item = RGB(0xFF, 0xFF, 0xFF);
    ___item2 = RGB(120, 120, 120);
}

void loop()
{
    tone(_buzzer_B, 300);
    delay(100);
    noTone(_buzzer_B);
    digitalWrite(_led_R1, HIGH);
    digitalWrite(_led_R2, HIGH);
    digitalWrite(_led_L, HIGH);
    analogWrite(_led_red_R, 0xcc);
    analogWrite(_led_green_R, 0x00);
    analogWrite(_led_blue_R, 0x00);
    
    analogWrite(_led_red_R, 120);
    analogWrite(_led_green_R, 120);
    analogWrite(_led_blue_R, 120);
    
    analogWrite(_led_red_R, RCHANNEL(___item));
    analogWrite(_led_green_R, GCHANNEL(___item));
    analogWrite(_led_blue_R, BCHANNEL(___item));
    
    analogWrite(_led_red_R, RCHANNEL(___item2));
    analogWrite(_led_green_R, GCHANNEL(___item2));
    analogWrite(_led_blue_R, BCHANNEL(___item2));
    
    analogWrite(_led_red_R, 0);
    analogWrite(_led_green_R, 0);
    analogWrite(_led_blue_R, 0);
    
    analogWrite(_led_red_R, 0);
    analogWrite(_led_green_R, 0);
    analogWrite(_led_blue_R, 0);
    
}
