// This file is automatically generated by the Open Roberta Lab.
#define _ARDUINO_STL_NOT_NEEDED
#include "SenseBoxMCU.h"
#undef max
#undef min
#include <NEPODefs.h>
#include <stdlib.h>



void ____control();
void ____logic();


double ___numVar;
bool ___boolVar;
String ___stringVar;
unsigned int ___colourVar;
std::list<double> ___numList;
std::list<bool> ___boolList;
std::list<String> ___stringList;
std::list<unsigned int> ___colourList;


void ____control() {
    if ( ___boolVar ) {
    }
    if ( ___boolVar ) {
    } else if ( ___boolVar ) {
    }
    if ( ___boolVar ) {
    }
    while ( true ) {
        delay(1);
    }
    for (int ___k0 = 0; ___k0 < ___numVar; ___k0 += 1) {
        delay(1);
    }
    while ( ! ___boolVar ) {
        delay(1);
    }
    while ( ___boolVar ) {
        delay(1);
    }
    for (int ___i = ___numVar; ___i < ___numVar; ___i += ___numVar) {
        delay(1);
    }
    for ( double ___item : ___numList ) {
        delay(1);
    }
    for ( bool ___item2 : ___boolList ) {
        delay(1);
    }
    for ( String ___item3 : ___stringList ) {
        delay(1);
    }
    for ( unsigned int ___item4 : ___colourList ) {
        delay(1);
    }
    while ( true ) {
        break;
        delay(1);
    }
    while ( true ) {
        continue;
        delay(1);
    }
    while (true) {
        if ( ___boolVar ) {
            break;
        }
        delay(1);
    }
    while (true) {
        if ( ___boolVar ) {
            break;
        }
        if ( ___boolVar ) {
            break;
        }
        delay(1);
    }
    delay(___numVar);
}

void ____logic() {
    Serial.println(___numVar == ___numVar);
    Serial.println(___numVar != ___numVar);
    Serial.println(___numVar < ___numVar);
    Serial.println(___numVar <= ___numVar);
    Serial.println(___numVar > ___numVar);
    Serial.println(___numVar >= ___numVar);
    Serial.println(___boolVar && ___boolVar);
    Serial.println(___boolVar || ___boolVar);
    Serial.println(! ___boolVar);
    Serial.println(NULL);
    Serial.println(( ( ___boolVar ) ? ( ___numVar ) : ( ___numVar) ));
}

void setup()
{
    Serial.begin(9600);

    ___numVar = 0;
    ___boolVar = true;
    ___stringVar = "";
    ___colourVar = RGB(0xFF, 0xFF, 0xFF);
    ___numList = {0, 0, 0};
    ___boolList = {true, true, true};
    ___stringList = {"", "", ""};
    ___colourList = {RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF)};
}

void loop()
{
    ____control();
    ____logic();
}