// This file is automatically generated by the Open Roberta Lab.
#define _ARDUINO_STL_NOT_NEEDED
#include "SenseBoxMCU.h"
#undef max
#undef min
#include <NEPODefs.h>
#include <stdlib.h>



void ____text();
void ____colour();
void ____parameters(double ___x, bool ___x2, String ___x3, unsigned int ___x4, std::list<double> ___x5, std::list<bool> ___x6, std::list<String> ___x7, std::list<unsigned int> ___x8);
double ____function_return_numberVar();
bool ____function_return_booleanVar();
String ____function_return_stringVar();
unsigned int ____function_return_colourVar();
std::list<double> ____function_return_numberList();
std::list<bool> ____function_return_booleanList();
std::list<String> ____function_return_stringList();
std::list<unsigned int> ____function_return_colourList();


double ___numVar;
bool ___boolVar;
String ___stringVar;
unsigned int ___colourVar;
std::list<double> ___numList;
std::list<bool> ___boolList;
std::list<String> ___stringList;
std::list<unsigned int> ___colourList;


void ____text() {
    //
    ___stringVar += ___stringVar;
}

void ____colour() {
    Serial.println(RGB(___numVar, ___numVar, ___numVar));
}

void ____parameters(double ___x, bool ___x2, String ___x3, unsigned int ___x4, std::list<double> ___x5, std::list<bool> ___x6, std::list<String> ___x7, std::list<unsigned int> ___x8) {
}

double ____function_return_numberVar() {
    return ___numVar;
}

bool ____function_return_booleanVar() {
    return ___boolVar;
}

String ____function_return_stringVar() {
    return ___stringVar;
}

unsigned int ____function_return_colourVar() {
    return ___colourVar;
}

std::list<double> ____function_return_numberList() {
    return ___numList;
}

std::list<bool> ____function_return_booleanList() {
    return ___boolList;
}

std::list<String> ____function_return_stringList() {
    return ___stringList;
}

std::list<unsigned int> ____function_return_colourList() {
    return ___colourList;
}

void setup()
{
    Serial.begin(9600);

    ___numVar = 0;
    ___boolVar = true;
    ___stringVar = "";
    ___colourVar = RGB(0xFF, 0xFF, 0xFF);
    ___numList = {0, 0, 0};
    ___boolList = {true, true, true};
    ___stringList = {"", "", ""};
    ___colourList = {RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF)};
}

void loop()
{
    ____text();
    ____colour();
    ____parameters(___numVar, ___boolVar, ___stringVar, ___colourVar, ___numList, ___boolList, ___stringList, ___colourList);
    Serial.println(____function_return_numberVar());
    Serial.println(____function_return_booleanVar());
    Serial.println(____function_return_stringVar());
    Serial.println(____function_return_colourVar());
    ___numList = ____function_return_numberList();
    ___boolList = ____function_return_booleanList();
    ___stringList = ____function_return_stringList();
    ___colourList = ____function_return_colourList();
}