// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>


#include <LiquidCrystal/src/LiquidCrystal.h>
#include <NEPODefs.h>


double ___n;
String ___s;
int _led_L = LED_BUILTIN;
LiquidCrystal _lcd_lcd1602(12, 11, 5, 4, 3, 2);
void setup()
{
    pinMode(_led_L, OUTPUT);
    _lcd_lcd1602.begin(16, 2);
    ___n = 0;
    ___s = "Innsbruck";
}

void loop()
{
    _lcd_lcd1602.setCursor(0,0);
    _printToDisplay(_lcd_lcd1602, ___s);

    _lcd_lcd1602.clear();
}