// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>

#include <Servo/src/Servo.h>
#include <LiquidCrystal_I2C/LiquidCrystal_I2C.h>
#include <Adafruit_SSD1306.h>
#include <Stepper/src/Stepper.h>
#include <NEPODefs.h>

void ____action();
void ____move();
void ____display();
void ____sounds();
void ____lights();
void ____pin();

double ___n;
bool ___b;
String ___s;
unsigned int ___c;
std::list<double> ___nl;
std::list<bool> ___bl;
std::list<String> ___sl;
std::list<unsigned int> ___cl;
int _led_red_R2 = 5;
int _led_green_R2 = 9;
int _led_blue_R2 = 10;
int _v_colour_temp;
int _buzzer_S3 = 11;
int _output_A = 0;
int _output_A2 = 3;
int _relay_R = 6;
Servo _servo_S;
LiquidCrystal_I2C _lcd_L3(0x27, 16, 2);
int _led_L = LED_BUILTIN;
#define SCREEN_ADDRESS 0x3D
#define OLED_RESET 4
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 64
Adafruit_SSD1306 _lcd_O(SCREEN_WIDTH, SCREEN_HEIGHT, &Wire, OLED_RESET);
int _SPU_S2 = 2048;
Stepper _stepper_S2(_SPU_S2, 1, 4, 2, 12);

void ____action() {
    ____move();
    ____display();
    ____sounds();
    ____lights();
    ____pin();
}

void ____move() {
    _servo_S.write(___n);
    _stepper_S2.setSpeed(___n);
    _stepper_S2.step(_SPU_S2*(___n));
    digitalWrite(_relay_R, LOW);
    digitalWrite(_relay_R, HIGH);
}

void ____display() {
    Serial.println(___s);
    _lcd_L3.setCursor(___n,___n);
    _printToDisplay(_lcd_L3, ___s);

    _lcd_L3.clear();
    _lcd_O.setCursor(0,1);
    _printToDisplay(_lcd_O, "Hallo", true);

    _lcd_O.clearDisplay();
    _lcd_O.display();
}

void ____sounds() {
    tone(_buzzer_S3, ___n, ___n);
    delay(___n);
}

void ____lights() {
    digitalWrite(_led_L, HIGH);
    digitalWrite(_led_L, LOW);
    analogWrite(_led_red_R2, RCHANNEL(___c));
    analogWrite(_led_green_R2, GCHANNEL(___c));
    analogWrite(_led_blue_R2, BCHANNEL(___c));

    analogWrite(_led_red_R2, 0);
    analogWrite(_led_green_R2, 0);
    analogWrite(_led_blue_R2, 0);

}

void ____pin() {
    digitalWrite(_output_A, (int)___n);
    analogWrite(_output_A2, (int)___n);
}

void setup()
{
    Serial.begin(9600);
    pinMode(_led_red_R2, OUTPUT);
    pinMode(_led_green_R2, OUTPUT);
    pinMode(_led_blue_R2, OUTPUT);
    pinMode(_output_A, OUTPUT);
    pinMode(_output_A2, OUTPUT);
    pinMode(_relay_R, OUTPUT);
    _servo_S.attach(7);
    _lcd_L3.begin();
    pinMode(_led_L, OUTPUT);
    _lcd_O.begin(SSD1306_SWITCHCAPVCC, SCREEN_ADDRESS);
    _lcd_O.clearDisplay();
    _lcd_O.setTextColor(SSD1306_WHITE);
    ___n = 0;
    ___b = true;
    ___s = "";
    ___c = RGB(0xFF, 0xFF, 0xFF);
    ___nl = {0, 0};
    ___bl = {true, true};
    ___sl = {"", ""};
    ___cl = {RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF)};
}

void loop()
{
    ____action();
}