// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>

#include <Servo/src/Servo.h>
#include <LiquidCrystal_I2C/LiquidCrystal_I2C.h>
#include <Stepper/src/Stepper.h>
#include <NEPODefs.h>

void action();
void display();
void lights();
void move();
void sounds();
void pin();

double ___n;
bool ___b;
String ___s;
unsigned int ___c;
std::list<double> ___nl;
std::list<bool> ___bl;
std::list<String> ___sl;
std::list<unsigned int> ___cl;
int _led_red_R2 = 5;
int _led_green_R2 = 9;
int _led_blue_R2 = 10;
int _buzzer_S3 = 11;
int _output_A = 0;
int _output_A2 = 3;
int _relay_R = 6;
Servo _servo_S;
LiquidCrystal_I2C _lcd_L3(0x27, 16, 2);
int _led_L = LED_BUILTIN;
int _SPU_S2 = 2048;
Stepper _stepper_S2(_SPU_S2, 1, 4, 2, 12);

void action() {
    move();
    display();
    sounds();
    lights();
}

void display() {
    Serial.println(___s);
    _lcd_L3.setCursor(___n,___n);
    _lcd_L3.print(___s);
    
    _lcd_L3.clear();
}

void lights() {
    digitalWrite(_led_L, HIGH);
    digitalWrite(_led_L, LOW);
    analogWrite(_led_red_R2, RCHANNEL(___c));
    analogWrite(_led_green_R2, GCHANNEL(___c));
    analogWrite(_led_blue_R2, BCHANNEL(___c));
    
    analogWrite(_led_red_R2, 0);
    analogWrite(_led_green_R2, 0);
    analogWrite(_led_blue_R2, 0);
    
}

void move() {
    _servo_S.write(___n);
    _stepper_S2.setSpeed(___n);
    _stepper_S2.step(_SPU_S2*(___n));
    digitalWrite(_relay_R, LOW);
    digitalWrite(_relay_R, HIGH);
}

void sounds() {
    tone(_buzzer_S3, ___n, ___n);
    delay(___n);
}

void pin() {
    digitalWrite(_output_A, (int)___n);
    analogWrite(_output_A2, (int)___n);
}

void setup()
{
    Serial.begin(9600);
    pinMode(_led_red_R2, OUTPUT);
    pinMode(_led_green_R2, OUTPUT);
    pinMode(_led_blue_R2, OUTPUT);
    pinMode(_output_A, OUTPUT);
    pinMode(_output_A2, OUTPUT);
    pinMode(_relay_R, OUTPUT);
    _servo_S.attach(7);
    _lcd_L3.begin();
    pinMode(_led_L, OUTPUT);
    ___n = 0;
    ___b = true;
    ___s = "";
    ___c = RGB(0xFF, 0xFF, 0xFF);
    ___nl = {0, 0};
    ___bl = {true, true};
    ___sl = {"", ""};
    ___cl = {RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF)};
}

void loop()
{
    action();
}