// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <IRremote/src/IRremote.h>
#include <NEPODefs.h>


double ___item;
bool ___item2;
IRrecv _irrecv_I(11);

bool _getIRPresence(IRrecv &irrecv) {
    decode_results results;
    if (irrecv.decode(&results)) {
        irrecv.resume();
        return true;
    } else {
        return false;
    }
}

long int  _getIRValue(IRrecv &irrecv) {
    decode_results results;
    if (irrecv.decode(&results)) {
        long int tmpValue = results.value;
        irrecv.resume();
        return tmpValue;
    } else {
        return 0;
    }
}

void setup()
{
    pinMode(13, OUTPUT);
    _irrecv_I.enableIRIn();
    ___item = _getIRValue(_irrecv_I);
    ___item2 = _getIRPresence(_irrecv_I);
}

void loop()
{
}