// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <DHT_sensor_library/DHT.h>
#include <NEPODefs.h>


double ___item;
double ___item2;
#define DHTPINH 2
#define DHTTYPE DHT11
DHT _dht_H(DHTPINH, DHTTYPE);
void setup()
{
    _dht_H.begin();
    ___item = _dht_H.readHumidity();
    ___item2 = _dht_H.readTemperature();
}

void loop()
{
}
