// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <NEPODefs.h>


double ___item;
int _led_L = 13;
unsigned long __time_1 = millis();

void setup()
{ 
    pinMode(_led_L, OUTPUT);
    ___item = (int) (millis() - __time_1);
}

void loop()
{
    __time_1 = millis();
}
