// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <NEPODefs.h>


double ___item;
int _TMP36_T = A0;
void setup()
{ 
    ___item = map(analogRead(_TMP36_T), 0, 410, -50, 150);
}

void loop()
{
}
