// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

double ___item;
int _output_P2 = A0;
void setup()
{
    Serial.begin(9600); 
    ___item = ((double)analogRead(_output_P2))*5/1024;
}

void loop()
{
}
