// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <NEPODefs.h>


double ___item;
int _S_D = A0;
void setup()
{
    ___item = analogRead(_S_D)/10.24;
}

void loop()
{
}
