// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <NEPODefs.h>


double ___item;
int _SensorPin_P = A0;
void setup()
{
    ___item = analogRead(_SensorPin_P);
}

void loop()
{
}
