// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

double item;
int _TMP36_T = A0;
void setup()
{
    Serial.begin(9600); 
    item = map(analogRead(_TMP36_T), 0, 410, -50, 150);
}

void loop()
{
}