// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <NEPODefs.h>


double ___item;
int _moisturePin_M = A0;
void setup()
{
    ___item = analogRead(_moisturePin_M)/10.24;
}

void loop()
{
}
