// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <NEPODefs.h>


double ___item;
int _led_L = 13;
unsigned long __time = millis();

void setup()
{ 
    pinMode(_led_L, OUTPUT);
    ___item = (int) (millis() - __time);
}

void loop()
{
    __time = millis();
}
