// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <NEPODefs.h>


bool ___item;
int _taster_B = 2;
void setup()
{
    pinMode(_taster_B, INPUT);
    ___item = digitalRead(_taster_B);
}

void loop()
{
}
