// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <IRremote.h>
#include <NEPODefs.h>


bool ___item;
int _RECV_PIN_I = 11;
IRrecv _irrecv_I(_RECV_PIN_I);
decode_results _results_I;

bool _getIRPresence(IRrecv irrecv, decode_results &irResults) {
    if (irrecv.decode(&irResults)) {
        irrecv.resume();
        return true;
    } else {
        return false;
    }
}

long int  _getIRValue(IRrecv irrecv, decode_results &irResults) {
    if (irrecv.decode(&irResults)) {
        long int tmpValue = irResults.value;
        irrecv.resume();
        return tmpValue;
    } else {
        return 0;
    }
}

void setup()
{
    Serial.begin(9600); 
    pinMode(13, OUTPUT);
    _irrecv_I.enableIRIn();
    ___item = _getIRPresence(_irrecv_I, _results_I);
}

void loop()
{
}