// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <SparkFun_LSM6DS3_Breakout/src/SparkFunLSM6DS3.h>
#include <NEPODefs.h>


String ___Element;
LSM6DS3 _imu_B(SPI_MODE, SPIIMU_SS);
LSM6DS3 _imu_K(SPI_MODE, SPIIMU_SS);
int _led_L = LED_BUILTIN;
void setup()
{
    Serial.begin(9600); 
    _imu_B.begin();
    _imu_K.begin();
    pinMode(_led_L, OUTPUT);
    ___Element = "";
}

void loop()
{
    ___Element = "Gyro: X: ";
    ___Element += _imu_K.readFloatGyroX();
    ___Element += ", Y: ";
    ___Element += _imu_K.readFloatGyroY();
    ___Element += ", Z: ";
    ___Element += _imu_K.readFloatGyroZ();
    Serial.println(___Element);
    ___Element = "Accelerometer: X: ";
    ___Element += _imu_B.readFloatAccelX();
    ___Element += ", Y: ";
    ___Element += _imu_B.readFloatAccelY();
    ___Element += ", Z: ";
    ___Element += _imu_B.readFloatAccelZ();
    Serial.println(___Element);
}