// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

double item;
double item2;
int _input_S = 0;
int _input_S2 = A0;
void setup()
{
    Serial.begin(9600); 
    pinMode(_input_S, INPUT);
    pinMode(_input_S2, INPUT);
    item = analogRead(_input_S2);
    item2 = digitalRead(_input_S);
}

void loop()
{
}