// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

double item;
int _trigger_U = 7;
int _echo_U = 6;
double _signalToDistance = 0.03432/2;
double _getUltrasonicDistance()
{
    digitalWrite(_trigger_U, LOW);
    delay(5);
    digitalWrite(_trigger_U, HIGH);
    delay(10);
    digitalWrite(_trigger_U, LOW);
    return pulseIn(_echo_U, HIGH)*_signalToDistance;
}

void setup()
{
    Serial.begin(9600); 
    pinMode(_trigger_U, OUTPUT);
    pinMode(_echo_U, INPUT);
    item = _getUltrasonicDistance();
}

void loop()
{
}