package de.fhg.iais.roberta.visitor;

public enum Txt4Methods {
    MOTORSTART,
    MOTORSTARTFOR,
    OMNIDRIVEVERTICAL,
    OMNIDRIVEHORIZONTAL,
    OMNIDRIVEDIAGONALTL,
    OMNIDRIVEDIAGONALTR,
    OMNIDRIVETURN,
    OMNIDRIVETURNDEGREES,
}
