package de.fhg.iais.roberta.visitor;

public enum Txt4Methods {
    MOTORSTART,
    MOTORSTARTFOR,
    OMNIDRIVE,
    OMNIDRIVETURN,
    OMNIDRIVETURNDEGREES,

    OMNIDRIVESTRAIGHTDISTANCE,

    OMNIDRIVEDIAGONALTRDISTANCE,

    OMNIDRIVEDIAGONALTLDISTANCE
}
