package de.fhg.iais.roberta.visitor;

public enum Txt4Methods {
    MOTORSTART,
    MOTORSTARTFOR,
    OMNIDRIVE,
    DIFFERENTIALDRIVE,
    OMNIDRIVETURN,
    DIFFDRIVETURN,
    OMNIDRIVECURVEDISTANCE,
    OMNIDRIVETURNDEGREES,
    DIFFDRIVETURNDEGREES,
    OMNIDRIVESTRAIGHTDISTANCE,
    OMNIDRIVEDIAGONALTRDISTANCE,
    OMNIDRIVEDIAGONALTLDISTANCE,
    DIFFERENTIALDRIVEDISTANCE,
    DIFFERENTIALDRIVECURVEDISTANCE,
    DISPLAYLEDON,
    CAMERAGETCOLOUR,
    LINEINFORMATION,
    BALLINFORMATION,
    COLOURCOMPARE,
}
