// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.fr');

goog.require('Blockly.Msg');

Blockly.Msg.ACTIVITY_TOOLTIP = "ajouter blocs";
Blockly.Msg.ACTOR_TOOLTIP = "autres activités";
Blockly.Msg.ADD_COMMENT = "Ajouter un commentaire";
Blockly.Msg.AUTH = "Veuillez autoriser cette application à permettre la sauvegarde de votre travail et à l’autoriser d'être partagé par vous.";
Blockly.Msg.BATTERY_GETSAMPLE_TOOLTIP = "Gets the current voltage from the battery.";  // untranslated
Blockly.Msg.BRICKLIGHT = "lumière du EV3";
Blockly.Msg.BRICKLIGHT_BLUE = "blue";  // untranslated
Blockly.Msg.BRICKLIGHT_COLOR = "couleur";
Blockly.Msg.BRICKLIGHT_DOUBLE_FLASH = "clignotement double";
Blockly.Msg.BRICKLIGHT_FLASH = "clignote";
Blockly.Msg.BRICKLIGHT_GREEN = "vert";
Blockly.Msg.BRICKLIGHT_OFF_TOOLTIP = "éteind la lumière du EV3";
Blockly.Msg.BRICKLIGHT_ON = "allumée";
Blockly.Msg.BRICKLIGHT_ON_TOOLTIP = "allume la lumière du EV3";
Blockly.Msg.BRICKLIGHT_ORANGE = "orange";
Blockly.Msg.BRICKLIGHT_RED = "rouge";
Blockly.Msg.BRICKLIGHT_RESET_TOOLTIP = "reset vers clignotement vert";
Blockly.Msg.BRICK_TRACK_WIDTH = "écart entre les roues";
Blockly.Msg.BRICK_WHEEL_DIAMETER = "diamètre de la roue";
Blockly.Msg.BUTTON_DO_DELETE = "effacer";
Blockly.Msg.BUTTON_DO_SHARE = "diviser";
Blockly.Msg.BUTTON_EMPTY_LIST = "vider la liste";
Blockly.Msg.BUTTON_FINISH = "terminer";
Blockly.Msg.BUTTON_LOAD = "charger";
Blockly.Msg.BUTTON_MORE = "plus";
Blockly.Msg.BUTTON_REFRESH = "actualiser";
Blockly.Msg.BUTTON_START = "On y va !";
Blockly.Msg.BUTTON_STOP = "arrêt";
Blockly.Msg.CHANGE_VALUE_TITLE = "Modifier la valeur :";
Blockly.Msg.CHAT = "Discutez avec votre collaborateur en tapant dans cette zone !";
Blockly.Msg.CLEAN_UP = "Nettoyer les blocs";
Blockly.Msg.COLLAPSE_ALL = "Réduire les blocs";
Blockly.Msg.COLLAPSE_BLOCK = "Réduire le bloc";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "couleur 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "couleur 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";
Blockly.Msg.COLOUR_BLEND_RATIO = "taux";
Blockly.Msg.COLOUR_BLEND_TITLE = "mélanger";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Mélange deux couleurs dans une proportion donnée (de 0.0 à 1.0).";
Blockly.Msg.COLOUR_GETSAMPLE_TOOLTIP = "donne la valeur actuelle du capteur couleur";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://fr.wikipedia.org/wiki/Couleur";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Choisir une couleur dans la palette.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "couleur aléatoire";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Choisir une couleur au hasard.";
Blockly.Msg.COLOUR_RGB_BLUE = "bleu";
Blockly.Msg.COLOUR_RGB_GREEN = "vert";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";
Blockly.Msg.COLOUR_RGB_RED = "rouge";
Blockly.Msg.COLOUR_RGB_TITLE = "colorier avec";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Créer une couleur avec la quantité spécifiée de rouge, vert et bleu. Les valeurs doivent être comprises entre 0 et 100.";
Blockly.Msg.COLOUR_TOOLTIP = "bloc pour capteur couleur";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_LEFT_MISSING = "Moteur gauche manquant dans la configuration du robot!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_LEFT_UNREGULATED = "La régulation du moteur gauche est inactive!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_MISSING = "Pas de moteur branché dans la configuration du robot!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_RIGHT_MISSING = "Moteur droite manquant dans la configuration du robot!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_RIGHT_UNREGULATED = "La régulation du moteur droite est inactive!";
Blockly.Msg.CONFIGURATION_ERROR_SENSOR_MISSING = "Le capteur n'est pas branché au bon port!";
Blockly.Msg.CONFIGURATION_ERROR_SENSOR_WRONG = "Un autre capteur est branché à ce port!";
Blockly.Msg.CONNECTION_CHECK = "connection to robot %1 active?";  // untranslated
Blockly.Msg.CONNECTION_CHECK_TOOLTIP = "check if the connection to the robot is active.";  // untranslated
Blockly.Msg.CONNECTION_CONNECT = "Connection avec le robot nommé ...";
Blockly.Msg.CONNECTION_FROM_ROBOT = "from robot";  // untranslated
Blockly.Msg.CONNECTION_OVER_CHANNEL = "over channel";  // untranslated
Blockly.Msg.CONNECTION_RECEIVED_DATA = "réception de message";
Blockly.Msg.CONNECTION_RECEIVE_TOOLTIP = "Attendre le mesage en provenance du lien indiqué";
Blockly.Msg.CONNECTION_SEND_DATA = "envoyer message";
Blockly.Msg.CONNECTION_START_TOOLTIP = "connexion Bluetooth avec un robot robot";
Blockly.Msg.CONNECTION_TOOLTIP = "A robot's connection";  // untranslated
Blockly.Msg.CONNECTION_TO_CONNECTION = "to connection";  // untranslated
Blockly.Msg.CONNECTION_TO_ROBOT = "to robot";  // untranslated
Blockly.Msg.CONNECTION_USED_CONNECTION = "via liaison";
Blockly.Msg.CONNECTION_WAIT_FOR_CONNECTION = "attendre la liaison";
Blockly.Msg.CONNECTION_WAIT_TOOLTIP = "le robot attend la demande de liaison d'un autre robot";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "quitter la boucle";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "passer à l’itération de boucle suivante";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Sortir de la boucle englobante.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Sauter le reste de cette boucle, et poursuivre avec l’itération suivante.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Attention : Ce bloc ne devrait être utilisé que dans une boucle.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "pour chaque élément %1 dans la liste %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Pour chaque élément d’une liste, assigner la valeur de l’élément à la variable '%1', puis exécuter des instructions.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "compter avec %1 de %2 à %3 par %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Faire prendre à la variable « %1 » les valeurs depuis le nombre de début jusqu’au nombre de fin, en s’incrémentant du pas spécifié, et exécuter les instructions spécifiées.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Ajouter une condition au bloc si.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Ajouter une condition finale fourre-tout au bloc si.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Ajouter, supprimer ou réordonner les sections pour reconfigurer ce bloc si.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "sinon";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "sinon si";
Blockly.Msg.CONTROLS_IF_MSG_IF = "si";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Si une valeur est vraie, alors exécuter certains ordres.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Si une valeur est vraie, alors exécuter le premier bloc d’ordres. Sinon, exécuter le second bloc d’ordres.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Si la première valeur est vraie, alors exécuter le premier bloc d’ordres. Sinon, si la seconde valeur est vraie, exécuter le second bloc d’ordres.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Si la première valeur est vraie, alors exécuter le premier bloc d’ordres. Sinon, si la seconde valeur est vraie, exécuter le second bloc d’ordres. Si aucune des valeurs n’est vraie, exécuter le dernier bloc d’ordres.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "http://fr.wikipedia.org/wiki/Boucle_for";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "faire";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "répéter %1 fois";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Exécuter des instructions plusieurs fois.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "répéter jusqu’à";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "répéter tant que";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Tant qu’une valeur est fausse, alors exécuter des instructions.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Tant qu’une valeur est vraie, alors exécuter des instructions.";
Blockly.Msg.DATATABLE_ACTUALIZATION = "dernière actualisation";
Blockly.Msg.DATATABLE_BLOCKS = "blocs";
Blockly.Msg.DATATABLE_CONFIGURATIONS = "configurations";
Blockly.Msg.DATATABLE_CONFIGURATION_NAME = "Nom de la configuration";
Blockly.Msg.DATATABLE_CREATED_BY = "créé par";
Blockly.Msg.DATATABLE_CREATED_ON = "créé le";
Blockly.Msg.DATATABLE_EMPTY_TABLE = "La liste est vide";
Blockly.Msg.DATATABLE_ENTRIES = "Entrées";
Blockly.Msg.DATATABLE_FIRST = "première";
Blockly.Msg.DATATABLE_LAST = "dernière";
Blockly.Msg.DATATABLE_NEXT = "suivante";
Blockly.Msg.DATATABLE_OF = "de";
Blockly.Msg.DATATABLE_PREVIOUS = "précédente";
Blockly.Msg.DATATABLE_PROGRAMS = "programme";
Blockly.Msg.DATATABLE_PROGRAM_NAME = "Nom du programme";
Blockly.Msg.DATATABLE_SHARED = "partager";
Blockly.Msg.DATATABLE_SHARED_WITH = "partager avec";
Blockly.Msg.DATATABLE_SHOW = "montre";
Blockly.Msg.DATATABLE_SHOWING = "montre";
Blockly.Msg.DATATABLE_TO = "jusqu'à ce que";
Blockly.Msg.DELETE_ALL_BLOCKS = "Supprimer ces %1 blocs ?";
Blockly.Msg.DELETE_BLOCK = "Supprimer le bloc";
Blockly.Msg.DELETE_X_BLOCKS = "Supprimer %1 blocs";
Blockly.Msg.DISABLE_BLOCK = "Désactiver le bloc";
Blockly.Msg.DISPLAY_CLEAR = "effacer l'écran";
Blockly.Msg.DISPLAY_CLEAR_TOOLTIP = "efface l'affichage de l'écran";
Blockly.Msg.DISPLAY_COL = "dans la colonne";
Blockly.Msg.DISPLAY_PICTURE = "image";
Blockly.Msg.DISPLAY_PICTURE_EYES_CLOSED = "yeux ouverts";
Blockly.Msg.DISPLAY_PICTURE_EYES_OPEN = "yeux fermés";
Blockly.Msg.DISPLAY_PICTURE_FLOWERS = "fleurs";
Blockly.Msg.DISPLAY_PICTURE_GLASSES = "lunettes";
Blockly.Msg.DISPLAY_PICTURE_TACHO = "compteur de vitesse";
Blockly.Msg.DISPLAY_PICTURE_TOOLTIP = "affiche une image à l'écran";
Blockly.Msg.DISPLAY_ROW = "dans la ligne";
Blockly.Msg.DISPLAY_SHOW = "montrer";
Blockly.Msg.DISPLAY_TEXT = "texte";
Blockly.Msg.DISPLAY_TEXT_TOOLTIP = "montre un texte à l'écran";
Blockly.Msg.DUPLICATE_BLOCK = "Dupliquer";
Blockly.Msg.ENABLE_BLOCK = "Activer le bloc";
Blockly.Msg.ENCODER_GETSAMPLE_TOOLTIP = "donne la valeur actuelle du capteur de rotation";
Blockly.Msg.ENCODER_RESET_TOOLTIP = "initialise le capteur de rotation";
Blockly.Msg.EV3BRICK_TOOLTIP = "bloc pour le EV3";
Blockly.Msg.EXPAND_ALL = "Développer les blocs";
Blockly.Msg.EXPAND_BLOCK = "Développer le bloc";
Blockly.Msg.EXTERNAL_INPUTS = "Entrées externes";
Blockly.Msg.FOR = "pour ";
Blockly.Msg.GET = "donne";
Blockly.Msg.GETSAMPLE_TOOLTIP = "Donne la valeur du capteur actuellement sélectionné";
Blockly.Msg.GYRO_GETSAMPLE_TOOLTIP = "donne la valeur actuelle du capteur gyroscopique";
Blockly.Msg.GYRO_RESET_TOOLTIP = "initialise le capteur gyroscopique";
Blockly.Msg.GYRO_TOOLTIP = "bloc pour le capteur gyroscopique";
Blockly.Msg.HELP = "Aide";
Blockly.Msg.IFELSE_TOOLTIP = "vérifie la condition SI. Si elle est vraie, execute l'action, SINON execute l'autre";
Blockly.Msg.IF_TOOLTIP = "vérifie la condition SI. Si elle est vraie, execute l'action";
Blockly.Msg.INFRARED_GETSAMPLE_TOOLTIP = "donne la valeur actuelle du capteur infrarouge";
Blockly.Msg.INFRARED_TOOLTIP = "bloc pour le capteur infrarouge";
Blockly.Msg.INLINE_INPUTS = "Entrées en ligne";
Blockly.Msg.KEY_ISPRESSEDANDRELEASED_TOOLTIP = "bouton heurté?";
Blockly.Msg.KEY_ISPRESSED_TOOLTIP = "bouton enfoncé?";
Blockly.Msg.LIGHT_GETSAMPLE_TOOLTIP = "Gets the current reading from the light sensor.";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "créer une liste vide";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Renvoyer une liste, de longueur 0, ne contenant aucun enregistrement";
Blockly.Msg.LISTS_CREATE_TITLE = "liste";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "liste";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Ajouter, supprimer, ou réordonner les sections pour reconfigurer ce bloc de liste.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "créer une liste avec";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Ajouter un élément à la liste.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Créer une liste avec un nombre quelconque d’éléments.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "premier";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# depuis la fin";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET = "obtenir";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "obtenir et supprimer";
Blockly.Msg.LISTS_GET_INDEX_LAST = "dernier";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "aléatoire";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "supprimer";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Renvoie le premier élément dans une liste.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Renvoie l’élément à la position indiquée dans une liste. #1 est le dernier élément.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Renvoie l’élément à la position indiquée dans une liste. #1 est le premier élément.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Renvoie le dernier élément dans une liste.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Renvoie un élément au hasard dans une liste.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Supprime et renvoie le premier élément dans une liste.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Supprime et renvoie l’élément à la position indiquée dans une liste. #1 est le dernier élément.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Supprime et renvoie l’élément à la position indiquée dans une liste. #1 est le premier élément.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Supprime et renvoie le dernier élément dans une liste.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Supprime et renvoie un élément au hasard dans une liste.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Supprime le premier élément dans une liste.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Supprime l’élément à la position indiquée dans une liste. #1 est le dernier élément.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Supprime l’élément à la position indiquée dans une liste. #1 est le premier élément.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Supprime le dernier élément dans une liste.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Supprime un élément au hasard dans une liste.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "jusqu’à # depuis la fin";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "jusqu’à #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "jusqu’à la fin";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "obtenir la sous-liste depuis le début";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "obtenir la sous-liste depuis # depuis la fin";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "obtenir la sous-liste depuis #";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Crée une copie de la partie spécifiée d’une liste.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "trouver la première occurrence de l’élément";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "trouver la dernière occurrence de l’élément";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Renvoie l’index de la première/dernière occurrence de l’élément dans la liste. Renvoie 0 si l'élément n'est pas trouvé.";
Blockly.Msg.LISTS_INLIST = "dans la liste";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 est vide";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Renvoie vrai si la liste est vide.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "longueur de %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Renvoie la longueur d’une liste.";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "créer une liste avec l’élément %1 répété %2 fois";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Crée une liste consistant en la valeur fournie répétée le nombre de fois indiqué.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "comme";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "insérer en";
Blockly.Msg.LISTS_SET_INDEX_SET = "mettre";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Insère l’élément au début d’une liste.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Insère l’élément à la position indiquée dans une liste. #1 est le dernier élément.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Insère l’élément à la position indiquée dans une liste. #1 est le premier élément.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Ajouter l’élément à la fin d’une liste.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Insère l’élément au hasard dans une liste.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Fixe le premier élément dans une liste.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Fixe l’élément à la position indiquée dans une liste. #1 est le dernier élément.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Fixe l’élément à la position indiquée dans une liste. #1 est le premier élément.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Fixe le dernier élément dans une liste.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Fixe un élément au hasard dans une liste.";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "croissant";
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "décroissant";
Blockly.Msg.LISTS_SORT_TITLE = "trier %1 %2 %3";
Blockly.Msg.LISTS_SORT_TOOLTIP = "Trier une copie d’une liste.";
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "alphabétique, en ignorant la casse";
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "numérique";
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "alphabétique";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "créer une liste depuis le texte";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "créer un texte depuis la liste";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Réunir une liste de textes en un seul, en les séparant par un séparateur.";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Couper un texte en une liste de textes, en coupant à chaque séparateur.";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "avec le séparateur";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "faux";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Renvoie soit vrai soit faux.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "vrai";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://fr.wikipedia.org/wiki/Inegalite_(mathematiques)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Renvoyer vrai si les deux entrées sont égales.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Renvoyer vrai si la première entrée est plus grande que la seconde.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Renvoyer vrai si la première entrée est plus grande ou égale à la seconde.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Renvoyer vrai si la première entrée est plus petite que la seconde.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Renvoyer vrai si la première entrée est plus petite ou égale à la seconde.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Renvoyer vrai si les deux entrées sont différentes.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "pas %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Renvoie vrai si l’entrée est fausse. Renvoie faux si l’entrée est vraie.";
Blockly.Msg.LOGIC_NULL = "nul";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Renvoie nul.";
Blockly.Msg.LOGIC_OPERATION_AND = "et";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "ou";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Renvoyer vrai si les deux entrées sont vraies.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Renvoyer vrai si au moins une des entrées est vraie.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "si faux";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "si vrai";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Vérifier la condition dans 'test'. Si elle est vraie, renvoie la valeur 'si vrai' ; sinon renvoie la valeur 'si faux'.";
Blockly.Msg.LOOP = "répéter jusqu'à ce que";
Blockly.Msg.LOOPFOREVER_TOOLTIP = "répéter indéfiniment l'action";
Blockly.Msg.LOOP_COUNT = "Nombre";
Blockly.Msg.LOOP_FOREVER = "répéter indéfiniment";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://fr.wikipedia.org/wiki/Arithmetique";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Renvoie la somme des deux nombres.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Renvoie le quotient des deux nombres.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Renvoie la différence des deux nombres.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Renvoie le produit des deux nombres.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Renvoie le premier nombre élevé à la puissance du second.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_TITLE = "incrémenter %1 de %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Ajouter un nombre à la variable '%1'.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Renvoie une des constantes courantes : π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), ou ∞ (infini).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "contraindre %1 entre %2 et %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Contraindre un nombre à être entre les limites spécifiées (incluses).";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "est divisible par";
Blockly.Msg.MATH_IS_EVEN = "est pair";
Blockly.Msg.MATH_IS_NEGATIVE = "est négatif";
Blockly.Msg.MATH_IS_ODD = "est impair";
Blockly.Msg.MATH_IS_POSITIVE = "est positif";
Blockly.Msg.MATH_IS_PRIME = "est premier";
Blockly.Msg.MATH_IS_TOOLTIP = "Vérifier si un nombre est pair, impair, premier, entier, positif, négatif, ou s’il est divisible par un certain nombre. Renvoie vrai ou faux.";
Blockly.Msg.MATH_IS_WHOLE = "est entier";
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_TITLE = "reste de %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Renvoyer le reste de la division euclidienne des deux nombres.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://fr.wikipedia.org/wiki/Nombre";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Un nombre.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "moyenne de la liste";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "maximum de la liste";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "médiane de la liste";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "minimum de la liste";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "majoritaires de la liste";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "élément aléatoire de la liste";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "écart-type de la liste";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "somme de la liste";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Renvoyer la moyenne (arithmétique) des valeurs numériques dans la liste.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Renvoyer le plus grand nombre dans la liste.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Renvoyer le nombre médian de la liste.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Renvoyer le plus petit nombre dans la liste.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Renvoyer une liste des élément(s) le(s) plus courant(s) dans la liste.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Renvoyer un élément dans la liste au hasard.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Renvoyer l’écart-type de la liste.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Renvoyer la somme de tous les nombres dans la liste.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "fraction aléatoire";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Renvoyer une fraction aléatoire entre 0.0 (inclus) et 1.0 (exclus).";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "entier aléatoire entre %1 et %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Renvoyer un entier aléatoire entre les deux limites spécifiées, incluses.";
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "arrondir";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "arrondir par défaut";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "arrondir par excès";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Arrondir un nombre au-dessus ou au-dessous.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://fr.wikipedia.org/wiki/Racine_carree";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "valeur absolue";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "racine carrée";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Renvoie la valeur absolue d’un nombre.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Renvoie e à la puissance d’un nombre.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Renvoie le logarithme naturel d’un nombre.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Renvoie le logarithme base 10 d’un nombre.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Renvoie l’opposé d’un nombre";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Renvoie 10 à la puissance d’un nombre.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Renvoie la racine carrée d’un nombre.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Renvoie l’arccosinus d’un nombre.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Renvoie l’arcsinus d’un nombre.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Renvoie l’arctangente d’un nombre.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Renvoie le cosinus d’un angle en degrés (pas en radians).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Renvoie le sinus d’un angle en degrés (pas en radians).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Renvoie la tangente d’un angle en degrés (pas en radians).";
Blockly.Msg.ME = "Moi";
Blockly.Msg.MENU_ABOUT = "via";
Blockly.Msg.MENU_ATTACH = "attacher";
Blockly.Msg.MENU_BEGINNER = "débutant";
Blockly.Msg.MENU_BUILDING_INSTRUCTIONS = "mode d'emploi";
Blockly.Msg.MENU_CHANGE = "modifier";
Blockly.Msg.MENU_CHECK = "vérifier";
Blockly.Msg.MENU_CONNECT = "lier";
Blockly.Msg.MENU_DELETE_USER = "effecer l'utilisateur";
Blockly.Msg.MENU_EDIT = "modifier";
Blockly.Msg.MENU_EDIT_TOOLTIP = "modifier";
Blockly.Msg.MENU_EV3 = "préparer EV3";
Blockly.Msg.MENU_EXPERT = "expert";
Blockly.Msg.MENU_EXPORT_PROG = "programmes exportés";
Blockly.Msg.MENU_FAQ = "questions fréquentes";
Blockly.Msg.MENU_GENERAL = "aide générale";
Blockly.Msg.MENU_HELP = "aide";
Blockly.Msg.MENU_HELP_TOOLTIP = "aide";
Blockly.Msg.MENU_IMPORT_PROG = "programmes importés";
Blockly.Msg.MENU_LANGUAGE = "languages";  // untranslated
Blockly.Msg.MENU_LANGUAGE_TOOLTIP = "languages";  // untranslated
Blockly.Msg.MENU_LIST = "Liste ...";
Blockly.Msg.MENU_LIST_CONF = "my configurations ...";  // untranslated
Blockly.Msg.MENU_LIST_PROG = "my programs ...";  // untranslated
Blockly.Msg.MENU_LIST_PROG_EXAMPLES = "example programs ...";  // untranslated
Blockly.Msg.MENU_LOGGING = "logging";
Blockly.Msg.MENU_LOG_IN = "connexion";
Blockly.Msg.MENU_LOG_OUT = "log out";
Blockly.Msg.MENU_MESSAGE_DOWNLOAD = "Ton programme a été téléchargé";
Blockly.Msg.MENU_NEW = "nouveu ...";
Blockly.Msg.MENU_PROGRAMMING = "programmer avec NEPO";
Blockly.Msg.MENU_PROPERTIES = "Propriétés";
Blockly.Msg.MENU_ROBOT = "robot";
Blockly.Msg.MENU_ROBOT_STATE_INFO = "info";
Blockly.Msg.MENU_ROBOT_STATE_TOOLTIP = "Info robot";
Blockly.Msg.MENU_ROBOT_TOOLTIP = "robots";
Blockly.Msg.MENU_SAVE = "sauvegarder";
Blockly.Msg.MENU_SAVE_AS = "sauvegarder sous...";
Blockly.Msg.MENU_SHOW_AGAIN = "Montre l'info de démarrage";
Blockly.Msg.MENU_SHOW_CODE = "code source";
Blockly.Msg.MENU_SIM_BACK = "retour";
Blockly.Msg.MENU_SIM_BACK_TOOLTIP = "back to programming editor";  // untranslated
Blockly.Msg.MENU_SIM_DRAW = "dessiner Parcours";
Blockly.Msg.MENU_SIM_INFO = "Info";
Blockly.Msg.MENU_SIM_MATH = "coordonnées du parcours";
Blockly.Msg.MENU_SIM_RESCUE = "Parcours Rescue";
Blockly.Msg.MENU_SIM_ROBERTA = "Parcours Roberta";
Blockly.Msg.MENU_SIM_ROBOT_TOOLTIP = "open/close the robot's view";  // untranslated
Blockly.Msg.MENU_SIM_SCENE_TOOLTIP = "change the scene";  // untranslated
Blockly.Msg.MENU_SIM_SIMPLE = "Parcours facile";
Blockly.Msg.MENU_SIM_START_PAUSE = "Début/Pause";
Blockly.Msg.MENU_SIM_STEP = "étape";
Blockly.Msg.MENU_SIM_STOP = "arrêt";
Blockly.Msg.MENU_START_BRICK = "démarre sur le robot";
Blockly.Msg.MENU_START_SIM = "démarre dans la simulation";
Blockly.Msg.MENU_STATE_INFO = "info détaillé";
Blockly.Msg.MENU_TOOLBOX = "blocs NEPO";
Blockly.Msg.MENU_TOOLBOX_BEGINNER = "blocs NEPO pour débutant";
Blockly.Msg.MENU_TOOLBOX_EXPERT = "blocs NEPO pour expert";
Blockly.Msg.MENU_UPDATE_FIRMWARE = "actualiser la firmware";
Blockly.Msg.MENU_USER = "connexion";
Blockly.Msg.MENU_USER_STATE_TOOLTIP = "info utilisateur";
Blockly.Msg.MENU_USER_TOOLTIP = "utilisateur";
Blockly.Msg.MENU_ZOOM = "zoomer";
Blockly.Msg.MENU_ZOOM_IN = "agrandir";
Blockly.Msg.MENU_ZOOM_OUT = "réduire";
Blockly.Msg.MENU_ZOOM_RESET = "initialiser";
Blockly.Msg.MESSAGE_CONFIGURATION_DELETED = "Tu as effacé la configuration $ du robot";
Blockly.Msg.MESSAGE_EDIT_CHECK = "Vérification de ton programme !";
Blockly.Msg.MESSAGE_EDIT_SAVE_CONFIGURATION = "Ta configuration $ a été sauvegardée !";
Blockly.Msg.MESSAGE_EDIT_SAVE_CONFIGURATION_AS = "Ta configuration a été sauvegardée sous le nom '$' !";
Blockly.Msg.MESSAGE_EDIT_SAVE_PROGRAM = "Ton programme $ a été sauvegardé !";
Blockly.Msg.MESSAGE_EDIT_SAVE_PROGRAM_AS = "Ton programme a été sauvegardé sous le nom '$' !";
Blockly.Msg.MESSAGE_EDIT_START = "Ton programme $ va démarrer sur le robot !";
Blockly.Msg.MESSAGE_FIRMWARE_ERROR = "Incompatbilité entre le firmware de Open Roberta Lab et celui de ton robot. Envoi nous s'il te plaît un email !";
Blockly.Msg.MESSAGE_INVALID_NAME = "Utilise uniquement des lettres et des chiffres et commance TOUJOURS par une letrre. Réessaie de nouveau !";
Blockly.Msg.MESSAGE_NOT_AVAILABLE = "Cette fonction n'existe pas encore, désolé !";
Blockly.Msg.MESSAGE_PASSWORD_ERROR = "Les mots de passe ne correspondent pas. Réessaie de nouveau !";
Blockly.Msg.MESSAGE_PROGRAM_DELETED = "Tu as effacé ton programme $.";
Blockly.Msg.MESSAGE_RELATION_DELETED = "Tu as effacé un lien vers ton programme $";
Blockly.Msg.MESSAGE_RESTART_ROBOT = "Connecte de nouveau ton robot avec Open Roberta Lab.";
Blockly.Msg.MESSAGE_ROBOT_CONNECTED = "Ton robot $ est maintenant connecté.";
Blockly.Msg.MESSAGE_ROBOT_FIRMWARE_UPDATE = "La mise à jour de ton robot $ a été faite !";
Blockly.Msg.MESSAGE_USER_DELETED = "Tu as effacé ton compte d'utilisateur. Nous espérons que tu reviennes bientôt !";
Blockly.Msg.MESSAGE_USER_LOGIN = "Salut $ !";
Blockly.Msg.MESSAGE_USER_LOGOUT = "Tu n'es plus connceté !";
Blockly.Msg.MESSAGE_USER_NEW = "Salut $, soi le bienvenu!";
Blockly.Msg.MODE = "mode";
Blockly.Msg.MODE_AMBIENTLIGHT = "lumière ambiante";
Blockly.Msg.MODE_ANGLE = "angle";
Blockly.Msg.MODE_COLOUR = "couleur";
Blockly.Msg.MODE_DEGREE = "degré";
Blockly.Msg.MODE_DISTANCE = "distance";
Blockly.Msg.MODE_LIGHT = "lumière";
Blockly.Msg.MODE_PRESENCE = "présence";
Blockly.Msg.MODE_RATE = "rotation";
Blockly.Msg.MODE_RGB = "RGB";
Blockly.Msg.MODE_ROTATION = "nombre de rotation";
Blockly.Msg.MODE_SOUND = "sound";  // untranslated
Blockly.Msg.MODE_STATE = "état";
Blockly.Msg.MOTOR = "moteur";
Blockly.Msg.MOTORDIFF_ON_FOR_TOOLTIP = "démarre le robot en utilisant une vitesse quelconque et fait en sorte qu'il s'arrête après une certaine distance";
Blockly.Msg.MOTORDIFF_ON_TOOLTIP = "démarre le robot en utilisant une vitesse quelconque";
Blockly.Msg.MOTORDIFF_STOP_TOOLTIP = "arrête le robot";
Blockly.Msg.MOTORDIFF_TURN_FOR_TOOLTIP = "fait tourner le robot en fonction du degré";
Blockly.Msg.MOTORDIFF_TURN_TOOLTIP = "fait tourner le robot";
Blockly.Msg.MOTOR_BACKWARD = "reculer";
Blockly.Msg.MOTOR_BIG = "grand";
Blockly.Msg.MOTOR_BIG_TOOLTIP = "bloc pour le grand moteur";
Blockly.Msg.MOTOR_BRAKE = "freiner";
Blockly.Msg.MOTOR_DEGREE = "degré";
Blockly.Msg.MOTOR_DISTANCE = "distance en cm";
Blockly.Msg.MOTOR_DRIVE = "parcourt";
Blockly.Msg.MOTOR_FLOAT = "roue libre";
Blockly.Msg.MOTOR_FOREWARD = "avancer";
Blockly.Msg.MOTOR_GETPOWER_TOOLTIP = "donne la puissance actuelle de ce moteur";
Blockly.Msg.MOTOR_LEFT = "gauche";
Blockly.Msg.MOTOR_MIDDLE = "moyen";
Blockly.Msg.MOTOR_MIDDLE_TOOLTIP = "bloc pour le moyen moteur";
Blockly.Msg.MOTOR_NONE = "aucun";
Blockly.Msg.MOTOR_ON_FOR_TOOLTIP = "démarre le moteur et l'arrête après le nombre de rotation (ou le nombre de degré)";
Blockly.Msg.MOTOR_ON_TOOLTIP = "démarre le moteur avec une certaine puissance";
Blockly.Msg.MOTOR_OTHER = "autre consommateur d'énergie";
Blockly.Msg.MOTOR_PORT = "port moteur";
Blockly.Msg.MOTOR_REGULATION = "paramétrage";
Blockly.Msg.MOTOR_RIGHT = "droite";
Blockly.Msg.MOTOR_ROTATION = "rotation";
Blockly.Msg.MOTOR_ROTATION_REVERSE = "sens de rotation";
Blockly.Msg.MOTOR_SETPOWER_TOOLTIP = "régler la puissance du moteur";
Blockly.Msg.MOTOR_SIDE = "page";
Blockly.Msg.MOTOR_SPEED = "vitesse";
Blockly.Msg.MOTOR_STEER = "steer";  // untranslated
Blockly.Msg.MOTOR_STOP = "arrête";
Blockly.Msg.MOTOR_STOP_TOOLTIP = "arrête ce moteur";
Blockly.Msg.MOTOR_TURN = "tourne";
Blockly.Msg.NEW_VARIABLE = "Nouvelle variable…";
Blockly.Msg.NEW_VARIABLE_TITLE = "Nouveau nom de la variable :";
Blockly.Msg.NO = "non";
Blockly.Msg.NXTBRICK_TOOLTIP = "NXT brick.";  // untranslated
Blockly.Msg.OFF = "éteindre";
Blockly.Msg.ON = "allumer";
Blockly.Msg.ORA_COMMAND_INVALID = "Le nom existe déjà. Choisi un autre nom et réessaie !";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_CONFIGURATION_NOT_FOUND = "Le serveur n'a pas trouvé la configuration du robot.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_CONFIGURATION_TRANSFORM_FAILED = "Le transfer de la configuration du robot vers le language de programmation a échoué.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_COMPILE_FAILED = "Le programm n'a pas pu être traduit en language machine.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_GENERATION_FAILED = "La génération du programm a échouée.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_NOT_FOUND = "Le programm n'a pas pu être trouvé dans la base de données.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_STORE_FAILED = "Erreur d'enregistrement du programm.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_TRANSFORM_FAILED = "Le programm n'a pas pu être transféré vers le language de programmation.";
Blockly.Msg.ORA_CONFIGURATION_DELETE_ERROR = "Erreur lors de la suppression de la configuration du robot. Réessaie !";
Blockly.Msg.ORA_CONFIGURATION_DELETE_SUCCESS = "Tu as effacé la configuration $ du robot.";
Blockly.Msg.ORA_CONFIGURATION_ERROR_ID_INVALID = "Le nom de la configuration du robot n'est pas valide.";
Blockly.Msg.ORA_CONFIGURATION_GET_ALL_SUCCESS = "La configuration du robot est prête.";
Blockly.Msg.ORA_CONFIGURATION_GET_ONE_ERROR_NOT_FOUND = "La configuration du robot  n'a pas pu être trouvée dans la base de données.";
Blockly.Msg.ORA_CONFIGURATION_GET_ONE_SUCCESS = "La configuration $ est prête.";
Blockly.Msg.ORA_CONFIGURATION_SAVE_ERROR = "Erreur d'enregistrement de la configuration du robot.";
Blockly.Msg.ORA_CONFIGURATION_SAVE_ERROR_NOT_SAVED_TO_DB = "Erreur d'enregistrement de la configuration du robot dans la base de données.";
Blockly.Msg.ORA_CONFIGURATION_SAVE_SUCCESS = "La configuration $ du robot a été enrégistrée !";
Blockly.Msg.ORA_OWNER_DOES_NOT_EXIST = "Cet utilisateur n'existe pas!";
Blockly.Msg.ORA_PROGRAM_CONFIGURATION_NOT_COMPATIBLE = "Le programm n'est pas compatible avec la configuration du robot.";
Blockly.Msg.ORA_PROGRAM_DELETE_ERROR = "Erreur lors de la suppression du programm, réessaie !";
Blockly.Msg.ORA_PROGRAM_DELETE_SUCCESS = "Tu as effacé le programm $ .";
Blockly.Msg.ORA_PROGRAM_ERROR_ID_INVALID = "Le nom du programm existe déjà. Choisi un autre et réessaie !";
Blockly.Msg.ORA_PROGRAM_GET_ALL_SUCCESS = "Les programmes sont prêts.";
Blockly.Msg.ORA_PROGRAM_GET_ONE_ERROR_NOT_FOUND = "Le programm n'a pas pu être trouvé dans la base de données.";
Blockly.Msg.ORA_PROGRAM_GET_ONE_ERROR_NOT_LOGGED_IN = "Tu n'es pas connecté. Réessaie avec ton utilisateur et mot de passe ou crée ton compte.";
Blockly.Msg.ORA_PROGRAM_GET_ONE_SUCCESS = "Programme téléchargé";
Blockly.Msg.ORA_PROGRAM_IMPORT_ERROR = "$.xml n'est pas un programme compatible NEPO et ne peut pas être téléchargé";
Blockly.Msg.ORA_PROGRAM_SAVE_AS_ERROR_PROGRAM_EXISTS = "Le programme existe déjà.";
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_NOT_SAVED_TO_DB = "Erreur de sauvegarde du programme";
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_NO_WRITE_PERMISSION = "Tu n'as pas les droits nécessaires pour modifier le programme.";
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_OPTIMISTIC_TIMESTAMP_LOCKING = "Ton programme a été modifié récemment. Tu dois enregistrer tes modification dans un nouveau programme >enregistrer sous<";
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_PROGRAM_TO_UPDATE_NOT_FOUND = "Le programme est introuvable, la mise à jour est impossible.";
Blockly.Msg.ORA_PROGRAM_SAVE_SUCCESS = "Le programme $ est enregistré.";
Blockly.Msg.ORA_PROGRAM_TO_SHARE_DOES_NOT_EXIST = "Le partage du programme $ n'est pas possible. Il n'existe pas.";
Blockly.Msg.ORA_ROBOT_FIRMWAREUPDATE_IMPOSSIBLE = "Erreur lors du mise à jour du nouveau system pour ton robot.";
Blockly.Msg.ORA_ROBOT_FIRMWAREUPDATE_POSSIBLE = "Le robot est mise à jour avec la toute dernière version.";
Blockly.Msg.ORA_ROBOT_NOT_CONNECTED = "Le robot n'est pas connecté au serveur. Regarde, si le robot est allumé, puis connecte le au serveur avec le mot de passe sous - connexion serveur.<br/> Si cela ne fonctionne pas, regarde dans l'aide.";
Blockly.Msg.ORA_ROBOT_NOT_WAITING = "Le robot est actuellement inactif.";
Blockly.Msg.ORA_ROBOT_PUSH_RUN = "Envoi du programme en cours, le robot va démarrer.";
Blockly.Msg.ORA_SERVER_ERROR = "Erreur du serveur";
Blockly.Msg.ORA_TOKEN_SET_ERROR_NO_ROBOT_WAITING = "As-tu allumé on robot et connecté au serveur?<br/> Si cela ne fonctionne pas, regarde l'aide.";
Blockly.Msg.ORA_TOKEN_SET_SUCCESS = "Très bien! Ton robot $ est connecté au serveur.";
Blockly.Msg.ORA_TOOLBOX_DELETE_ERROR = "Erreur lors de la suppression de la palette, ressaie!";
Blockly.Msg.ORA_TOOLBOX_DELETE_SUCCESS = "Tu as supprimé la palette.";
Blockly.Msg.ORA_TOOLBOX_ERROR_ID_INVALID = "Le nom de la palette n'est pas valide.";
Blockly.Msg.ORA_TOOLBOX_GET_ALL_SUCCESS = "Tu as chargé ta palette.";
Blockly.Msg.ORA_TOOLBOX_GET_ONE_ERROR_NOT_FOUND = "Ta palette na pas pu être trouvée ans la base de données.";
Blockly.Msg.ORA_TOOLBOX_GET_ONE_SUCCESS = "La palette est prête !";
Blockly.Msg.ORA_TOOLBOX_LOAD_ERROR_NOT_FOUND = "les blocs NEPO de la palette n'ont pas été trouvés dans la base de données.";
Blockly.Msg.ORA_TOOLBOX_LOAD_SUCCESS = "les blocs NEPO $ sont prêts !";
Blockly.Msg.ORA_TOOLBOX_SAVE_ERROR = "erreur de sauvegarde de la palette.";
Blockly.Msg.ORA_TOOLBOX_SAVE_ERROR_NOT_SAVED_TO_DB = "erreur de sauvegarde de la palette";
Blockly.Msg.ORA_TOOLBOX_SAVE_SUCCESS = "la palette a été enrégistrée!";
Blockly.Msg.ORA_TOOLBOX_TRANSFORM_ERROR = "erreur de transformation";
Blockly.Msg.ORA_USER_CREATE_ERROR_MISSING_REQ_FIELDS = "Vérifie si toutes les cases ont été remplies.";
Blockly.Msg.ORA_USER_CREATE_ERROR_NOT_SAVED_TO_DB = "Erreur de sauvegarde; l'utilisateur existe déjà ou réesaie !";
Blockly.Msg.ORA_USER_CREATE_SUCCESS = "L'utilisateur a été créé !";
Blockly.Msg.ORA_USER_DELETE_ERROR_ID_NOT_FOUND = "Erreur lors de la suppression de l'utilisateur $.";
Blockly.Msg.ORA_USER_DELETE_ERROR_NOT_DELETED_IN_DB = "Erreur de suppression de l'utilisateur $ de la base de données.";
Blockly.Msg.ORA_USER_DELETE_SUCCESS = "Tu as supprimé ton compte d'utilisateur. Nous espérons que tu reviendras bientôt !";
Blockly.Msg.ORA_USER_EMAIL_ONE_ERROR_USER_NOT_EXISTS_WITH_THIS_EMAIL = "L'adresse mail inconnue. Vérifie son écriture.";
Blockly.Msg.ORA_USER_GET_ALL_SUCCESS = "Ton compte d'utilisateur a été chargé.";
Blockly.Msg.ORA_USER_GET_ONE_ERROR_ID_OR_PASSWORD_WRONG = "Erreur d'inscription. L'utilisateur et le mot de passe, sont-ils corrects? <br /> Réessaie !";
Blockly.Msg.ORA_USER_GET_ONE_SUCCESS = "Login correct !";
Blockly.Msg.ORA_USER_TO_SHARE_DOES_NOT_EXIST = "L'utilisateur pour le partage de ton programme n'existe pas. L'as-tu écrit correctement?<br /> Réessaie !";
Blockly.Msg.ORA_USER_TO_SHARE_SAME_AS_LOGIN_USER = "Tu ne peux pas partager les programmes avec toi-même.";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PLAY = "jeux";
Blockly.Msg.PLAY_DURATION = "durée";
Blockly.Msg.PLAY_FILE = "son";
Blockly.Msg.PLAY_FILE_TOOLTIP = "joue un fichier son.";
Blockly.Msg.PLAY_FREQUENZ = "fréquence";
Blockly.Msg.PLAY_GETVOLUME_TOOLTIP = "Donne le volume.";
Blockly.Msg.PLAY_SETVOLUME_TOOLTIP = "régler le volume.";
Blockly.Msg.PLAY_TONE = "note";
Blockly.Msg.PLAY_TONE_TOOLTIP = "joue une note";
Blockly.Msg.PLAY_VOLUME = "volume";
Blockly.Msg.POPUP_ABOUT_JOIN = "je souhaite aider";
Blockly.Msg.POPUP_ABOUT_TEXT = "Open Roberta Lab est un environnement de programmation online pour les jeunes qui permet de façon simplifiée et sans obstacles techniques la programmation d'un robot. <br /> L'environnement de programmation est complètement »open source«, Vous pouvez l'améliorer!  Les Open-Source-developpertools sont à votre disposition sur le serveur Fraunhofer";
Blockly.Msg.POPUP_ABOUT_TEXT_DEV = "Open Roberta Lab a été développé par Fraunhofer-Instituts IAIS dans le cadre de l'iInitiative  <a href='http://www.roberta-home.de/'>»Roberta – apprendre grâce aux robots«</a>";
Blockly.Msg.POPUP_ABOUT_TEXT_GOOG = "Open Roberta a été créé en coopération avec Google Deutschland afin de permettre un approche simple de la programmation pour les élèves et les professeurs. Open Roberta a été financé par Google.org (2014 - 2015) à hauteur de 1Mio Euro. </a>";
Blockly.Msg.POPUP_ATTENTION = "attention";
Blockly.Msg.POPUP_BEFOREUNLOAD = "Il faut enrégistrer ta configuration et t'inscrire avant pouvoir quitter cette page. Sinon tu vas perdre tout ton travail !";
Blockly.Msg.POPUP_BEFOREUNLOAD_LOGGEDIN = "Il faut enrégistrer ta configurationavant pouvoir quitter cette page. Sinon tu vas perdre tout ton travail !";
Blockly.Msg.POPUP_CANCEL = "abandonner";
Blockly.Msg.POPUP_CHANGE_PASSWORD = "changer le mot de passe";
Blockly.Msg.POPUP_CONFIRM_DELETE_CONFIGURATION = "Veux-tu vraiement supprimer ta configuration du robot?";
Blockly.Msg.POPUP_CONFIRM_DELETE_PROGRAM = "Veux-tu vraiement supprimer ton programme?";
Blockly.Msg.POPUP_CONFIRM_UPDATE_FIRMWARE = "Le firmware du robo a changé. il se peut que tes programmes fonctionnent encore, mais nous te conseillons de le mettre à jour. Clique sur >> actualiser <<";
Blockly.Msg.POPUP_CONTINUE = "continuer";
Blockly.Msg.POPUP_DO_UPDATE_FIRMWARE = "actualiser";
Blockly.Msg.POPUP_EMAIL = "e-mail";
Blockly.Msg.POPUP_EMAIL_SEND = "envoyé maintenant";
Blockly.Msg.POPUP_NAME = "nom";
Blockly.Msg.POPUP_NEW_PASSWORD = "nouveau mot de passe";
Blockly.Msg.POPUP_OLD_PASSWORD = "ancien mot de passe";
Blockly.Msg.POPUP_PASSWORD = "mot de passe";
Blockly.Msg.POPUP_PASSWORD_RECOVERY = "réinitialiser le mot de passe";
Blockly.Msg.POPUP_PROGRAM_TERMINATED_UNEXPECTED = "Le programme n'a pas pu exécuter sur le robot.";
Blockly.Msg.POPUP_REGISTER_USER = "Inscris-toi maintenant";
Blockly.Msg.POPUP_REPEAT_PASSWORD = "répéter le mot de passe";
Blockly.Msg.POPUP_ROBOT_BATTERY = "charge de la battérie";
Blockly.Msg.POPUP_ROBOT_NAME = "nom";
Blockly.Msg.POPUP_ROBOT_NOT_CONNECTED = "Le robot n'est actuellement pas connecté au serveur. Regarde s'il est allumé puis connecte le de nouveau au serveur et donne le mot de passe dans la case - connexion <br />Si cela ne fonctionne pas, regarde dans l'aide.";
Blockly.Msg.POPUP_ROBOT_STATE = "état";
Blockly.Msg.POPUP_ROBOT_STATE_BUSY = "Programme est en cours d'exécution.";
Blockly.Msg.POPUP_ROBOT_STATE_DISCONNECTED = "Pas de connexion avec le robot.";
Blockly.Msg.POPUP_ROBOT_STATE_WAIT = "le robot attend";
Blockly.Msg.POPUP_ROBOT_SYSTEM = "système";
Blockly.Msg.POPUP_ROBOT_WAIT = "temps d'attente";
Blockly.Msg.POPUP_SHARE_READ = "lire";
Blockly.Msg.POPUP_SHARE_WITH = "Partager avec ...";
Blockly.Msg.POPUP_SHARE_WRITE = "écrire";
Blockly.Msg.POPUP_STARTUP_COOKIES = "Nous utilisons les cookies pour personnaliser le contenu et les affichages et pour analyser l'utilisation du site web.";
Blockly.Msg.POPUP_STARTUP_HELP = "As-tu besoin d'aide?";
Blockly.Msg.POPUP_STARTUP_HIDE = "Ne plus afficher cette fenêtre la prochain fois.";
Blockly.Msg.POPUP_STARTUP_NEW = "Qu'est-ce qui est nouveau ?";
Blockly.Msg.POPUP_STARTUP_START = "Choose your system!";  // untranslated
Blockly.Msg.POPUP_STARTUP_TITLE = "Bienvenu !";
Blockly.Msg.POPUP_TOUR = "take a tour";  // untranslated
Blockly.Msg.POPUP_USERNAME = "Nom d'utilisateur";
Blockly.Msg.POPUP_USERNAME_LOGOFF = "tu n'es pas inscrit";
Blockly.Msg.POPUP_VALUE = "valeur";
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "autoriser les ordres";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "avec :";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "http://fr.wikipedia.org/wiki/Proc%C3%A9dure_%28informatique%29";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Exécuter la fonction '%1' définie par l’utilisateur.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Exécuter la fonction '%1' définie par l’utilisateur et utiliser son résultat.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "avec :";
Blockly.Msg.PROCEDURES_CREATE_DO = "Créer '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Décrire cette fonction…";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "faire quelque chose";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "pour";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Crée une fonction sans sortie.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "retour";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Crée une fonction avec une sortie.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Attention : Cette fonction a des paramètres en double.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Surligner la définition de la fonction";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Si une valeur est vraie, alors renvoyer une seconde valeur.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Attention : Ce bloc pourrait n’être utilisé que dans une définition de fonction.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "nom de l’entrée :";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Ajouter une entrée à la fonction.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "entrées";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Ajouter, supprimer, ou réarranger les entrées de cette fonction.";
Blockly.Msg.PROCEDURES_TITLE = "fonction \" disponible";
Blockly.Msg.PROCEDURES_VARIABLES_ERROR = "Erreur de variable";
Blockly.Msg.PROCEDURES_VARIABLES_LOOP_ERROR = "Erreur dans la boucle: problème avec la variable";
Blockly.Msg.REDO = "Refaire";
Blockly.Msg.REMOVE_COMMENT = "Supprimer un commentaire";
Blockly.Msg.RENAME_VARIABLE = "Renommer la variable…";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Renommer toutes les variables « %1 » en :";
Blockly.Msg.SEND_DATA = "envoi des données";
Blockly.Msg.SENSOR_BATTERY = "voltage in mV";  // untranslated
Blockly.Msg.SENSOR_COLOUR = "capteur de couleur";
Blockly.Msg.SENSOR_ENCODER = "capteur de rotation";
Blockly.Msg.SENSOR_GET_MODE = "donne le mode";
Blockly.Msg.SENSOR_GET_SAMPLE = "donne la valeur";
Blockly.Msg.SENSOR_GYRO = "capteur gyroscopique";
Blockly.Msg.SENSOR_INFRARED = "capteur infrarouge";
Blockly.Msg.SENSOR_IS_PRESSED = "enfoncé?";
Blockly.Msg.SENSOR_KEY = "la touche";
Blockly.Msg.SENSOR_KEY_ANY = "n'importe lequel";
Blockly.Msg.SENSOR_KEY_DOWN = "bas";
Blockly.Msg.SENSOR_KEY_ENTER = "milieu";
Blockly.Msg.SENSOR_KEY_ESCAPE = "retour";
Blockly.Msg.SENSOR_KEY_LEFT = "gauche";
Blockly.Msg.SENSOR_KEY_RIGHT = "droite";
Blockly.Msg.SENSOR_KEY_UP = "haut";
Blockly.Msg.SENSOR_LIGHT = "light sensor";  // untranslated
Blockly.Msg.SENSOR_MS_TIMER = "unité ms";
Blockly.Msg.SENSOR_PRESSED = "enfoncé";
Blockly.Msg.SENSOR_RESET = "paramètre";
Blockly.Msg.SENSOR_RESET_II = "retour";
Blockly.Msg.SENSOR_SET_MODE = "choisi le mode";
Blockly.Msg.SENSOR_SOUND = "sound sensor";  // untranslated
Blockly.Msg.SENSOR_TIME = "temps";
Blockly.Msg.SENSOR_TIMER = "capteur temps";
Blockly.Msg.SENSOR_TOUCH = "capteur tactil";
Blockly.Msg.SENSOR_ULTRASONIC = "capteur ultra-son";
Blockly.Msg.SENSOR_WAIT_PRESSED = "enfoncé";
Blockly.Msg.SENSOR_WAIT_PRESSED_RELEASED = "heurté";
Blockly.Msg.SERVER_NOT_AVAILABLE = "Open Roberta Lab est actuellement indisponible. /<br> Vérifie ta connexion internet et actualise la page. Si le problème persiste, merci de bien vouloir nous le signaler par mail :</br>roberta-zentrale@iais.fraunhofer.de";
Blockly.Msg.SET = "Paramètre";
Blockly.Msg.SIM_BLOCK_NOT_SUPPORTED = "Ce bloc n'est malheureusement pas disponible pour la simulation!";
Blockly.Msg.SIM_CONFIGURATION_WARNING_SENSOR_MISSING = "Ce capteur n'est pas prévu dans la configuration de ton robot. Vérifie s'il te plaît!";
Blockly.Msg.SIM_CONFIGURATION_WARNING_WRONG_INFRARED_SENSOR_PORT = "Confusion entre capteur infrarouge et ultra-son. Vérifie s'il te plaït !";
Blockly.Msg.SIM_CONFIGURATION_WARNING_WRONG_SENSOR_PORT = "Mauvais port du capteur ! Vérifie s'il te plaît !";
Blockly.Msg.SOUND_GETSAMPLE_TOOLTIP = "Gets the current reading from the sound sensor.";  // untranslated
Blockly.Msg.START = "démarrage";
Blockly.Msg.START_ACTIVITY = "activité";
Blockly.Msg.START_ACTIVITY_TOOLTIP = "démarre une activité supplémentaire";
Blockly.Msg.START_PROGRAM = "démarrage du programme";
Blockly.Msg.START_PROGRAM_DEBUG = "affiche les données du capteur";
Blockly.Msg.START_TOOLTIP = "Bloc de démarrage du programme principal";
Blockly.Msg.TAB_CONFIGURATION = "configuration du robot";
Blockly.Msg.TAB_PROGRAM = "programme";
Blockly.Msg.TAB_SIMULATION = "simulation";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "ajouter le texte";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "à";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Ajouter du texte à la variable '%1'.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "en minuscules";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "en Majuscule Au Début De Chaque Mot";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "en MAJUSCULES";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Renvoyer une copie du texte dans une autre casse.";
Blockly.Msg.TEXT_CHARAT_FIRST = "obtenir la première lettre";
Blockly.Msg.TEXT_CHARAT_FROM_END = "obtenir la lettre # depuis la fin";
Blockly.Msg.TEXT_CHARAT_FROM_START = "obtenir la lettre #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "dans le texte";
Blockly.Msg.TEXT_CHARAT_LAST = "obtenir la dernière lettre";
Blockly.Msg.TEXT_CHARAT_RANDOM = "obtenir une lettre au hasard";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Renvoie la lettre à la position indiquée.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Ajouter un élément au texte.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "joindre";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Ajouter, supprimer, ou réordonner des sections pour reconfigurer ce bloc de texte.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "jusqu’à la lettre # depuis la fin";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "jusqu’à la lettre #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "jusqu’à la dernière lettre";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "dans le texte";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "obtenir la sous-chaîne depuis la première lettre";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "obtenir la sous-chaîne depuis la lettre # depuis la fin";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "obtenir la sous-chaîne depuis la lettre #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Renvoie une partie indiquée du texte.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "dans le texte";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "trouver la première occurrence de la chaîne";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "trouver la dernière occurrence de la chaîne";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Renvoie l’index de la première/dernière occurrence de la première chaîne dans la seconde. Renvoie 0 si la chaîne n’est pas trouvée.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 est vide";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Renvoie vrai si le texte fourni est vide.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "créer un texte avec";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Créer un morceau de texte en agrégeant un nombre quelconque d’éléments.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "longueur de %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Renvoie le nombre de lettres (espaces compris) dans le texte fourni.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "afficher %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Afficher le texte, le nombre ou une autre valeur spécifié.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Demander un nombre à l’utilisateur.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Demander un texte à l’utilisateur.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "invite pour un nombre avec un message";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "invite pour un texte avec un message";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Une lettre, un mot ou une ligne de texte.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "supprimer les espaces des deux côtés";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "supprimer les espaces du côté gauche";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "supprimer les espaces du côté droit";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Renvoyer une copie du texte avec les espaces supprimés d’un bout ou des deux.";
Blockly.Msg.TIMER_GETSAMPLE_TOOLTIP = "donne la valeur actuelle du capteur temps";
Blockly.Msg.TIMER_RESET_TOOLTIP = "initialise le temps";
Blockly.Msg.TODAY = "Aujourd'hui";
Blockly.Msg.TOOLBOX_ACTION = "action";
Blockly.Msg.TOOLBOX_COLOUR = "couleurs";
Blockly.Msg.TOOLBOX_COMMUNICATION = "message";
Blockly.Msg.TOOLBOX_CONTROL = "contrôle";
Blockly.Msg.TOOLBOX_DECISION = "décision";
Blockly.Msg.TOOLBOX_DISPLAY = "afficher";
Blockly.Msg.TOOLBOX_DRIVE = "rouler";
Blockly.Msg.TOOLBOX_GLOBAL_VARIABLE = "variable globale";
Blockly.Msg.TOOLBOX_LIGHT = "lumière";
Blockly.Msg.TOOLBOX_LIST = "liste";
Blockly.Msg.TOOLBOX_LOGIC = "logique";
Blockly.Msg.TOOLBOX_LOOP = "boucle";
Blockly.Msg.TOOLBOX_LOOP_VARIABLE = "variable de la boucle";
Blockly.Msg.TOOLBOX_MATH = "mathématiques";
Blockly.Msg.TOOLBOX_MOVE = "mouvement";
Blockly.Msg.TOOLBOX_PROCEDURE = "fonctions";
Blockly.Msg.TOOLBOX_SENSOR = "capteurs";
Blockly.Msg.TOOLBOX_SOUND = "son";
Blockly.Msg.TOOLBOX_TEXT = "texte";
Blockly.Msg.TOOLBOX_VARIABLE = "variable";
Blockly.Msg.TOOLBOX_WAIT = "Attendre";
Blockly.Msg.TOUCH_ISPRESSED_TOOLTIP = "Le capteur tactil, est-il enfoncé?";
Blockly.Msg.TOUCH_TOOLTIP = "Bloc pour le capteur tactil.";
Blockly.Msg.TOUR1_DESCRIPTION00 = "next";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION01 = "Welcome,<br>click on  »next« and start a tour through the Open Roberta Lab.<br>I'll show you how you can program your robot with NEPO.<br>You can end this tour all the time with a click on »X« in the right upper corner.";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION02 = "The menu ;-)";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION03 = "Here you can find everything you need to program the robot!<br><span class='typcn typcn-document-text'></span> Save and load programs<br><span class='typcn typcn-Roberta'></span> Connect your robot to the Open Roberta Lab<br><span class='typcn typcn-lightbulb'></span> Help for all kinds of problems<br><span class='typcn typcn-user'></span>Everything about user accounts, e.g. login or logoff";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION04 = "Click here and switch to the robot configuration";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION05 = "You can adapt the robot configuration later,<br>if you've constructed another robot.<br>If you don't have a robot and want to test your program in the simulation <br>this configuration is applied.";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION06 = "Click here and switch back to the programming area!";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION07 = "The toolbox.<br>Here you can find all programming blocks.";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION08 = "Each program starts with the program-start-block«.<br>Further programming blocks, which the robot should execute, should be attached to this block.<br>Just drag'n drop the desired block right under the start block.";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION09 = "Here you find some shortcuts!<br>From left to right:<br><span class='typcn typcn-media-play'></span> Click here to execute the program on the real robot<br><span class='typcn typcn-media-play-outline'></span> Click here to start the robot in the simulation<br><span class='typcn typcn-cloud-storage'></span> Save your program, but before that you need to sign in<br><span class='typcn typcn-zoom'></span> Click here and zoom in on the blocks, if you want to<br><span class='typcn typcn-archive'></span> The trashcan! Just move blocks into the trashcan and they will be deleted.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Attention: You cannot recover blocks once they are deleted!<br>";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION10 = "Click on »Action«";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION11 = "Click and create the block in the workspace";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION12 = "Now drag'n drop the new block just below the start-program-block so that they are connected";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION13 = "Now test your program in the simulation!";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION14 = "Just a moment!";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION15 = "Perfect,<br>your robot is driving 20 cm forward,<br>this is what you have programmed!";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION16 = "Bye and have fun trying out more!";  // untranslated
Blockly.Msg.ULTRASONIC_GETSAMPLE_TOOLTIP = "Donne la valeur actuelle du capteur ultra-son.";
Blockly.Msg.ULTRASONIC_TOOLTIP = "Bloc pour le capteur ultyra-son.";
Blockly.Msg.UNDO = "Annuler";
Blockly.Msg.VALIDATION_FIELD_REQUIRED = "Il faut remplir cette case!";
Blockly.Msg.VALIDATION_PASSWORD_MIN_LENGTH = "Le mot de passe doit contenir au moins 6 caractères!";
Blockly.Msg.VALIDATION_SECOND_PASSWORD_EQUAL = "Les deux mots de passe doivent être identiques !";
Blockly.Msg.VALIDATION_TOKEN_LENGTH = "L'identificateur a 8 caractères!";
Blockly.Msg.VALIDATION_VALID_EMAIL_ADDRESS = "Donne une adresse mail valide s'il te plaît!";
Blockly.Msg.VARIABLES_CREATE_TITLE = "crée";
Blockly.Msg.VARIABLES_CREATE_WITH = "avec";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "élément";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Créer 'fixer %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Renvoie la valeur de cette variable.";
Blockly.Msg.VARIABLES_GLOBAL_DECLARE_TOOLTIP = "déclare une variable globale";
Blockly.Msg.VARIABLES_LOCAL_DECLARE_TOOLTIP = "déclare une variable locale";
Blockly.Msg.VARIABLES_SET = "fixer %1 à %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Créer 'obtenir %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Fixe cette variable pour qu’elle soit égale à la valeur de l’entrée.";
Blockly.Msg.VARIABLES_TITLE = "variable";
Blockly.Msg.VARIABLES_TYPE_ARRAY_BOOLEAN = "liste des valeurs logiques";
Blockly.Msg.VARIABLES_TYPE_ARRAY_COLOUR = "liste des couleurs";
Blockly.Msg.VARIABLES_TYPE_ARRAY_CONNECTION = "liste des connexions";
Blockly.Msg.VARIABLES_TYPE_ARRAY_NUMBER = "liste des chiffres";
Blockly.Msg.VARIABLES_TYPE_ARRAY_STRING = "liste des caractères";
Blockly.Msg.VARIABLES_TYPE_BOOLEAN = "valeur logique";
Blockly.Msg.VARIABLES_TYPE_COLOUR = "couleur";
Blockly.Msg.VARIABLES_TYPE_CONNECTION = "connexion";
Blockly.Msg.VARIABLES_TYPE_NUMBER = "chiffre";
Blockly.Msg.VARIABLES_TYPE_STRING = "caractères";
Blockly.Msg.WAIT = "attend";
Blockly.Msg.WAIT_FOREVER = "infinie";
Blockly.Msg.WAIT_FOR_TOOLTIP = "Il attend la valeur du capteur";
Blockly.Msg.WAIT_OR = "ou attend jusqu'à ce que";
Blockly.Msg.WAIT_TOOLTIP = "attend jusqu'à ce qu'une condition soit vraie";
Blockly.Msg.WAIT_UNTIL = "attend jusqu'à ce que";
Blockly.Msg.YES = "oui";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;