package de.fhg.iais.roberta.components;

public enum Category {
    EXPR, SENSOR, ACTOR, STMT, TASK, FUNCTION, METHOD, HELPER, CONFIGURATION_ACTOR, CONFIGURATION_SENSOR, CONFIGURATION_BOARD, CONFIGURATION_BUS, CONFIGURATION_LIBRARY;
}
