// This file is automatically generated by the Open Roberta Lab.

#define _ARDUINO_STL_NOT_NEEDED
#include <Arduino.h>

#include <Arduino_HTS221.h>
#include <Arduino_LSM9DS1.h>
#include <Arduino_LPS22HB.h>
#include <Arduino_APDS9960.h>
#include <NEPODefs.h>


bool ___b;
double ___v;
double ___x;
double ___y;
double ___z;
float xAsFloat, yAsFloat, zAsFloat;
int _led_L = LED_BUILTIN;
int rAsInt, gAsInt, bAsInt;
void setup()
{
    HTS.begin();
    IMU.begin();
    pinMode(_led_L, OUTPUT);
    BARO.begin();
    APDS.begin();
    ___b = true;
    ___v = 0;
    ___x = 0;
    ___y = 0;
    ___z = 0;
}

void loop()
{
    ___b = (IMU.accelerationAvailable()?(IMU.readAcceleration(xAsFloat,yAsFloat,zAsFloat),___x = (double) xAsFloat,___y = (double) yAsFloat,___z = (double) zAsFloat,1) : 0);
    ___b = (IMU.gyroscopeAvailable()?(IMU.readGyroscope(xAsFloat,yAsFloat,zAsFloat),___x = (double) xAsFloat,___y = (double) yAsFloat,___z = (double) zAsFloat,1) : 0);
    ___b = (IMU.magneticFieldAvailable()?(IMU.readMagneticField(xAsFloat,yAsFloat,zAsFloat),___x = (double) xAsFloat,___y = (double) yAsFloat,___z = (double) zAsFloat,1) : 0);
    ___b = (APDS.proximityAvailable()?(___v = (double) APDS.readProximity(),1) : 0);
    ___b = (APDS.gestureAvailable()?(___v = (double) APDS.readGesture(),1) : 0);
    ___b = (APDS.colorAvailable()?(APDS.readColor(rAsInt,gAsInt,bAsInt),___x = (double) rAsInt,___y = (double) gAsInt,___z = (double) bAsInt,1) : 0);
    ___b = (___v = (double) BARO.readPressure(),1);
    ___b = (___v = (double) HTS.readTemperature(),1);
    ___b = (___v = (double) HTS.readHumidity(),1);
}