// This file is automatically generated by the Open Roberta Lab.

#include <math.h>

#include <LiquidCrystal.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

LiquidCrystal _lcd_L2(12, 11, 5, 4, 3, 2);
void setup()
{
    Serial.begin(9600); 
    _lcd_L2.begin(16, 2);
}

void loop()
{
    _lcd_L2.setCursor(0,0);
    _lcd_L2.print("Hallo");
    _lcd_L2.clear();
}