// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>


#include <LiquidCrystal/src/LiquidCrystal.h>
#include <NEPODefs.h>


double ___numberVar;
String ___stringVar;
LiquidCrystal _lcd_L2(0, 1, 2, 3, 4, 5);
void setup()
{
    _lcd_L2.begin(16, 2);
    ___numberVar = 0;
    ___stringVar = "M\u00FCnchen";
}

void loop()
{
    _lcd_L2.setCursor(___numberVar,___numberVar);
    _lcd_L2.print(___stringVar);
    
    _lcd_L2.clear();
}