// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>


#include <LiquidCrystal/src/LiquidCrystal.h>
#include <NEPODefs.h>

void action();
void display();
void lights();
void move();
void sounds();
void pin();

double ___numberVar;
bool ___booleanVar;
String ___stringVar;
unsigned int ___colourVar;
std::list<double> ___numberList;
std::list<bool> ___booleanList;
std::list<String> ___stringList;
std::list<unsigned int> ___colourList;
LiquidCrystal _lcd_L2(0, 1, 2, 3, 4, 5);

void action() {
    move();
    display();
    sounds();
    lights();
}

void display() {
    _lcd_L2.setCursor(___numberVar,___numberVar);
    _lcd_L2.print(___stringVar);
    
    _lcd_L2.clear();
}

void lights() {
}

void move() {
}

void sounds() {
}

void pin() {
}

void setup()
{
    _lcd_L2.begin(16, 2);
    ___numberVar = 0;
    ___booleanVar = true;
    ___stringVar = "";
    ___colourVar = RGB(0xFF, 0xFF, 0xFF);
    ___numberList = {0, 0};
    ___booleanList = {true, true};
    ___stringList = {"", ""};
    ___colourList = {RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF)};
}

void loop()
{
    action();
}