// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>

#include <NEPODefs.h>

void ____sensors();
void ____sensorsWaitUntil();

double ___numberVar;
bool ___booleanVar;
String ___stringVar;
unsigned int ___colourVar;
std::list<double> ___numberList;
std::list<bool> ___booleanList;
std::list<String> ___stringList;
std::list<unsigned int> ___colourList;
int _moisturePin_M = A0;

void ____sensors() {
    Serial.println(analogRead(_moisturePin_M)/10.24);
}

void ____sensorsWaitUntil() {
    while (true) {
        if ( analogRead(_moisturePin_M)/10.24 < 30 ) {
            break;
        }
        delay(1);
    }
}

void setup()
{
    Serial.begin(9600);
    ___numberVar = 0;
    ___booleanVar = true;
    ___stringVar = "";
    ___colourVar = RGB(0xFF, 0xFF, 0xFF);
    ___numberList = {0, 0};
    ___booleanList = {true, true};
    ___stringList = {"", ""};
    ___colourList = {RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF)};
}

void loop()
{
    ____sensors();
    ____sensorsWaitUntil();
}