// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>

#include <NEPODefs.h>


int _output_A = 0;
void setup()
{
    pinMode(_output_A, OUTPUT);
}

void loop()
{
    digitalWrite(_output_A, (int)1);
}