// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.cs');

goog.require('Blockly.Msg');

Blockly.Msg.ACCELERATION_TOOLTIP = "Vrátí hodnotu zrychlení v násobcích g (mili-g).";
Blockly.Msg.ACCELEROMETER_ROTATION_TOOLTIP = "Vrátí hodnotu naklonění nebo otočení ve stupních.";
Blockly.Msg.ACTIVITY_TOOLTIP = "Značka pro doplňkovou aktivitu.";
Blockly.Msg.ACTOR_TOOLTIP = "Představuje libovolné výstupní zařízení.";
Blockly.Msg.ADD_COMMENT = "Přidat komentář";
Blockly.Msg.ANALOG = "analogový";
Blockly.Msg.ARDUBRICK_TOOLTIP = "Představuje desku Bot'n Roll s připojenými pohony a senzory. Jsou zde také dostupné zabudované pohony a senzory, například tlačítka, displej...";
Blockly.Msg.AUTH = "Prosím udělte oprávnění této aplikaci aby jste mohli uložit a sdílet svou práci.";
Blockly.Msg.BATTERY_GETSAMPLE_TOOLTIP = "Vrátí aktuální napětí baterie.";
Blockly.Msg.BLOCK_NOT_EXECUTED = "The exection of this block will have no effect!";  // untranslated
Blockly.Msg.BOB3_READNUMBER_TOOLTIP = "Returns the previously stored number.";  // untranslated
Blockly.Msg.BOB3_RECALL_NUMBER = "recall number";  // untranslated
Blockly.Msg.BOB3_REMEMBER_NUMBER = "remember number";  // untranslated
Blockly.Msg.BOB3_SAVENUMBER_TOOLTIP = "The number to store should be an integer in the range of 0 to 255";  // untranslated
Blockly.Msg.BOTH = "obě";
Blockly.Msg.BRICKLIGHT = "LED na kostce";
Blockly.Msg.BRICKLIGHT_BLUE = "modrá";
Blockly.Msg.BRICKLIGHT_COLOR = "barva";
Blockly.Msg.BRICKLIGHT_DOUBLE_FLASH = "dvakrát bliká";
Blockly.Msg.BRICKLIGHT_FLASH = "bliká";
Blockly.Msg.BRICKLIGHT_GREEN = "zelená";
Blockly.Msg.BRICKLIGHT_OFF_TOOLTIP = "Vypnout LED na kostce.";
Blockly.Msg.BRICKLIGHT_ON = "zapnuto";
Blockly.Msg.BRICKLIGHT_ON_TOOLTIP = "Zapnout LED na kostce.";
Blockly.Msg.BRICKLIGHT_ORANGE = "oranžová";
Blockly.Msg.BRICKLIGHT_RED = "červená";
Blockly.Msg.BRICKLIGHT_RESET_TOOLTIP = "Resetovat LED na kostce. Nastaví původní stav: blikající zelená.";
Blockly.Msg.BRICK_TRACK_WIDTH = "vzdálenost kol";
Blockly.Msg.BRICK_WHEEL_DIAMETER = "průměr kola";
Blockly.Msg.BUTTON_DO_SHARE = "Sdílet";
Blockly.Msg.BUTTON_DO_UPLOAD_GALLERY = "Upload »$« to the gallery";  // untranslated
Blockly.Msg.BUTTON_EMPTY_LIST = "Prázdný seznam";
Blockly.Msg.CALLIOPEBRICK_TOOLTIP = "Představuje Calliope, kapesní programovatelný počítač. Jsou zde také dostupné zabudované pohony a senzory, například tlačítka, displej...";
Blockly.Msg.CENTER = "prostřední";
Blockly.Msg.CHANGE_VALUE_TITLE = "Změnit hodnotu:";
Blockly.Msg.CHAT = "Psaním do tohoto políčka komunikujte se spolupracovníky!";
Blockly.Msg.CLEAN_UP = "Uspořádat bloky";
Blockly.Msg.COLLAPSE_ALL = "Sbalit bloky";
Blockly.Msg.COLLAPSE_BLOCK = "Sbalit blok";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "barva 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "barva 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "poměr";
Blockly.Msg.COLOUR_BLEND_TITLE = "smíchat";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Smíchá dvě barvy v daném poměru (0.0–1.0).";
Blockly.Msg.COLOUR_GETSAMPLE_TOOLTIP = "Vrátí aktuální hodnotu barevného senzoru.";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://cs.wikipedia.org/wiki/Barva";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Vyberte barvu z palety.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "náhodná barva";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Zvolte barvu náhodně.";
Blockly.Msg.COLOUR_RGB_BLUE = "modrá";
Blockly.Msg.COLOUR_RGB_GREEN = "zelená";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "červená";
Blockly.Msg.COLOUR_RGB_TITLE = "obarvěte barvou";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Vytvoř barvu se zadaným množstvím červené, zelené a modré.  Všechny hodnoty musí být mezi 0 a 100.";
Blockly.Msg.COLOUR_RGB_WHITE = "bílá";
Blockly.Msg.COLOUR_TOOLTIP = "Představuje barevný senzor.";
Blockly.Msg.COMPASS_CALIBRATE_TOOLTIP = "Calibrates the compass. Turn the compass sensor VERY slowly for two times (about 40 seconds).";  // untranslated
Blockly.Msg.COMPASS_GETSAMPLE_TOOLTIP = "Vrátí aktuální hodnodnotu kompasu.";
Blockly.Msg.COMPASS_TOOLTIP = "Představuje kompas.";
Blockly.Msg.CONFIGURATION_ERROR_MOTORS_ROTATION_DIRECTION = "Levý a pravý motor mají různé směry otáčení!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_LEFT_MISSING = "Levý motor chybí v konfiguraci!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_LEFT_UNREGULATED = "Levý motor není regulovaný!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_MISSING = "Motor není připojen k danému portu!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_RIGHT_MISSING = "Pravý motor chybí v konfiguraci!";
Blockly.Msg.CONFIGURATION_ERROR_MOTOR_RIGHT_UNREGULATED = "Pravý motor není regulovaný!";
Blockly.Msg.CONFIGURATION_ERROR_MULTIPLE_LEFT_MOTORS = "V konfiguraci je přiřazeno více levých motorů!";
Blockly.Msg.CONFIGURATION_ERROR_MULTIPLE_RIGHT_MOTORS = "V konfiguraci je přiřazeno více pravých motorů!";
Blockly.Msg.CONFIGURATION_ERROR_SENSOR_MISSING = "Tento senzor není připojen do portu.";
Blockly.Msg.CONFIGURATION_ERROR_SENSOR_WRONG = "Do daného portu je připojen špatný senzor.";
Blockly.Msg.CONFLIST_DELETE_ALL_TOOLTIP = "Klikni zde pro vymazání všech vybraných programů.";
Blockly.Msg.CONFLIST_DELETE_TOOLTIP = "Klikni zde pro vymazání konfigurace robota.";
Blockly.Msg.CONFLIST_LOAD_TOOLTIP = "Klikni zde pro nahrání nastavení robota do prostředí pro konfiguraci.";
Blockly.Msg.CONNECTION_BOB3_RECEIVE_TOOLTIP = "Reads a message via the IR receiver. Only numbers can be received.";  // untranslated
Blockly.Msg.CONNECTION_BOB3_SEND_TOOLTIP = "Sends a message of type number to another Bob3. Hold the Bob3's face to face!";  // untranslated
Blockly.Msg.CONNECTION_CHECK = "je připojení robota %1 aktivní?";
Blockly.Msg.CONNECTION_CHECK_TOOLTIP = "Zkontrolujte, zda je připojení k robotovi aktivní.";
Blockly.Msg.CONNECTION_CONNECT = "připojit k robotovi";
Blockly.Msg.CONNECTION_FROM_CONNECTION = "z připojení";
Blockly.Msg.CONNECTION_FROM_ROBOT = "od robota";
Blockly.Msg.CONNECTION_MBED_RECEIVE_TOOLTIP = "Reads a message over one of the channels (0 - 255). The default channel is 0.";  // untranslated
Blockly.Msg.CONNECTION_MBED_SEND_TOOLTIP = "Sends a message to another system. You can specify a signal strength from 0 - 7, where 0 is very low and 7 is the strongests. The message is send over channel 0 unless you specify another one.";  // untranslated
Blockly.Msg.CONNECTION_OVER_CHANNEL = "přenosová cesta";
Blockly.Msg.CONNECTION_POWER = "with strength";  // untranslated
Blockly.Msg.CONNECTION_PROTOCOL_BLUETOOTH = "Bluetooth";
Blockly.Msg.CONNECTION_RECEIVED_DATA = "přijmi zprávu";
Blockly.Msg.CONNECTION_RECEIVE_TOOLTIP = "Čeká na zprávu od robota uvedeného v parametrech připojení.";
Blockly.Msg.CONNECTION_SEND_DATA = "pošli zprávu";
Blockly.Msg.CONNECTION_SEND_TOOLTIP = "Pošle zprávu jinému robotovi.";
Blockly.Msg.CONNECTION_SET_CHANNEL = "set channel to %1";  // untranslated
Blockly.Msg.CONNECTION_SET_CHANNEL_TOOLTIP = "Sets the channel for sending and receiving messages. Can be set from 0 to 255.";  // untranslated
Blockly.Msg.CONNECTION_START_TOOLTIP = "Zkusí vytvořit připojení k jinému robotovi prostřednicvím Bluetooth.";
Blockly.Msg.CONNECTION_TOOLTIP = "Připojení k robotovi";
Blockly.Msg.CONNECTION_TO_CONNECTION = "připojení";
Blockly.Msg.CONNECTION_TO_ROBOT = "jméno robota";
Blockly.Msg.CONNECTION_WAIT_FOR_CONNECTION = "čeká na připojení";
Blockly.Msg.CONNECTION_WAIT_TOOLTIP = "Čeká na připojení pomocí Bluetooth.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "vyskočit ze smyčky";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "pokračuj dalším opakováním smyčky";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Vyskoč z vnitřní smyčky.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Přeskoč zbytek této smyčky a pokračuj dalším opakováním.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Upozornění: Tento blok může být použit pouze uvnitř smyčky.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_TITLE = "pro každou položku %1 v seznamu %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Pro každou položku v seznamu nastavte do proměnné '%1' danou položku a proveďte nějaké operace.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TITLE = "počítat s %1 od %2 do %3 po %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Nechá proměnnou '%1' nabývat hodnot od počátečního do koncového čísla po daném přírůstku a provádí s ní příslušné bloky.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Přidat podmínku do \"pokud\" bloku.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Přidej konečnou podmínku zahrnující ostatní případy do bloku \"pokud\".";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Přidej, odstraň či uspořádej sekce k přenastavení tohoto bloku \"pokud\".";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "jinak";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "nebo pokud";
Blockly.Msg.CONTROLS_IF_MSG_IF = "pokud";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Je-li hodnota pravda, proveď určité příkazy.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Je-li hodnota pravda, proveď první blok příkazů.  V opačném případě proveď druhý blok příkazů.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Je-li první hodnota pravdivá, proveď první blok příkazů. V opačném případě, je-li pravdivá druhá hodnota, proveď druhý blok příkazů.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Je-li první hodnota pravda, proveď první blok příkazů.  Je-li druhá hodnota pravda, proveď druhý blok příkazů.  Pokud žádná hodnota není pravda, proveď poslední blok příkazů.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://cs.wikipedia.org/wiki/Cyklus_pro";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "dělej";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "opakuj %1 krát";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Proveď určité příkazy několikrát.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "opakovat dokud";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "opakovat když";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Dokud je hodnota nepravdivá, prováděj určité příkazy.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Dokud je hodnota pravdivá, prováděj určité příkazy.";
Blockly.Msg.DATATABLE_ACTUALIZATION = "Datum aktualizace.";
Blockly.Msg.DATATABLE_CONFIGURATIONS = "konfigurace";
Blockly.Msg.DATATABLE_CONFIGURATION_NAME = "Jméno konfigurace";
Blockly.Msg.DATATABLE_CREATED_BY = "Vytvořil";
Blockly.Msg.DATATABLE_CREATED_ON = "Datum vytvoření";
Blockly.Msg.DATATABLE_PROGRAMS = "programy";
Blockly.Msg.DATATABLE_PROGRAM_NAME = "Jméno programu";
Blockly.Msg.DATATABLE_SHARED = "Shared";  // untranslated
Blockly.Msg.DATATABLE_SHARED_WITH = "Sdílené s";
Blockly.Msg.DELETE_ALL_BLOCKS = "Smazat všech %1 bloků?";
Blockly.Msg.DELETE_BLOCK = "Smazat blok";
Blockly.Msg.DELETE_X_BLOCKS = "Smazat %1 bloků";
Blockly.Msg.DIGITAL = "digitální";
Blockly.Msg.DISABLE_BLOCK = "Deaktivovat blok";
Blockly.Msg.DISPLAY_ANIMATION = "animace";
Blockly.Msg.DISPLAY_CHARACTER = "znak";
Blockly.Msg.DISPLAY_CLEAR = "vymaž displej";
Blockly.Msg.DISPLAY_CLEAR_TOOLTIP = "Vymaže displej.";
Blockly.Msg.DISPLAY_COL = "ve sloupci";
Blockly.Msg.DISPLAY_GET_BRIGHTNESS_TOOLTIP = "Vrátí jas všech LED na displeji. 0 znamená, že LED nesvítí, 9 že svítí maximálním jasem.";
Blockly.Msg.DISPLAY_GET_PIXEL_TOOLTIP = "Vrátí jas této LED. 0 znamená, že LED nesvítí, 9 že svítí maximálním jasem.";
Blockly.Msg.DISPLAY_IMAGE = "obrázek";
Blockly.Msg.DISPLAY_PICTURE = "obrázek";
Blockly.Msg.DISPLAY_PICTURE_EYES_CLOSED = "oči zavřené";
Blockly.Msg.DISPLAY_PICTURE_EYES_OPEN = "oči otevřené";
Blockly.Msg.DISPLAY_PICTURE_FLOWERS = "květiny";
Blockly.Msg.DISPLAY_PICTURE_GLASSES = "brýle";
Blockly.Msg.DISPLAY_PICTURE_TACHO = "tachometr";
Blockly.Msg.DISPLAY_PICTURE_TOOLTIP = "Zobrazí obrázek na displeji.";
Blockly.Msg.DISPLAY_PIXEL_BRIGHTNESS = "jas";
Blockly.Msg.DISPLAY_PIXEL_TITLE = "LED";
Blockly.Msg.DISPLAY_ROW = "v řádku";
Blockly.Msg.DISPLAY_SET_BRIGHTNESS_TOOLTIP = "Nastaví jas všech LED na displeji. 0 znamená, že LED nesvítí, 9 že svítí maximálním jasem.";
Blockly.Msg.DISPLAY_SET_PIXEL_TOOLTIP = "Nastaví jas této LED. 0 znamená, že LED nesvítí, 9 že svítí maximálním jasem.";
Blockly.Msg.DISPLAY_SHOW = "zobraz";
Blockly.Msg.DISPLAY_TEXT = "text";
Blockly.Msg.DISPLAY_TEXT_TOOLTIP = "Zobrazí text na displeji.";
Blockly.Msg.DUPLICATE_BLOCK = "Duplikovat";
Blockly.Msg.ENABLE_BLOCK = "Povolit blok";
Blockly.Msg.ENCODER_GETSAMPLE_TOOLTIP = "Vrátí aktuální hodnotu z tachometru motoru.";
Blockly.Msg.ENCODER_RESET_TOOLTIP = "Vynuluje tachometr motoru.";
Blockly.Msg.EV3BRICK_TOOLTIP = "Představuje kostku EV3 s připojenými pohony a senzory. Jsou zde také dostupné zabudované pohony a senzory, například tlačítka, displej...";
Blockly.Msg.EXPAND_ALL = "Rozbalit bloky";
Blockly.Msg.EXPAND_BLOCK = "Rozbalit blok";
Blockly.Msg.EXTERNAL_INPUTS = "vnější vstupy";
Blockly.Msg.FLAME_GETSAMPLE_TOOLTIP = "Gets the current reading from the flame sensor.";  // untranslated
Blockly.Msg.FLAME_TOOLTIP = "Represents a flame sensor.";  // untranslated
Blockly.Msg.FLYOUT_VARIABLE_TEXT = "You need a variable? Please declare it first with a click on the + sign at the »start« block.";  // untranslated
Blockly.Msg.FOR = "pro";
Blockly.Msg.GALLERY_BY = "by";  // untranslated
Blockly.Msg.GALLERY_DATE = "created";  // untranslated
Blockly.Msg.GALLERY_DISLIKE = "dislike";  // untranslated
Blockly.Msg.GALLERY_LIKE = "like";  // untranslated
Blockly.Msg.GALLERY_SHARED_ALREADY = "You have already uploaded this program to the gallery. If you want to change it, look for the copy from the gallery and modify it. You can also remove it from the gallery while deleting the copy from the gallery.";  // untranslated
Blockly.Msg.GET = "získat";
Blockly.Msg.GETSAMPLE_TOOLTIP = "Vrátí aktuální hodnotu vybraného senzoru.";
Blockly.Msg.GET_CODE_TOOLTIP = "Returns the value of the solderable code pad in the head piece. Values are in range 0-31.";  // untranslated
Blockly.Msg.GO_TO_GROUPS = "Go to groups";  // untranslated
Blockly.Msg.GYRO_GETSAMPLE_TOOLTIP = "Vrátí aktuální hodnotu gyro senzoru.";
Blockly.Msg.GYRO_RESET_TOOLTIP = "Resetuje gyro senzor.";
Blockly.Msg.GYRO_TOOLTIP = "Představuje gyro senzor.";
Blockly.Msg.HELP = "Nápověda";
Blockly.Msg.HINT_USER_ACCOUNT = "»IAmBotman« or »RobellaStracciatella«? Not everyone needs to know your real name. Think of a cool nickname that you can easily remember.";  // untranslated
Blockly.Msg.HINT_USER_AGE = "Are you under 16? Then please ask your parents to help you. They can specify their e-mail address to confirm your account.";  // untranslated
Blockly.Msg.HINT_USER_EMAIL = "This is voluntary! However, some functions of the lab are only available if you have verified your account by e-mail. You are younger than 16? Please ask your parents to help you out with one of their e-mail addresses. <br><a href='https://www.roberta-home.de/index.php?id=138&L=1' target='_blank'>Further information ...</a>";  // untranslated
Blockly.Msg.HINT_USER_NAME = "Enter your real name here if you like. This is just for you, no one else will see it.";  // untranslated
Blockly.Msg.HINT_USER_PASSWORT = "12345 is no secure password. Rather think of a safe combination of numbers and letters that you will not forget.";  // untranslated
Blockly.Msg.HINT_USER_PASSWORT_CONFIRM = "Got it? Better make sure!";  // untranslated
Blockly.Msg.IF_TOOLTIP = "Checks the condition in »if«. If the condition is true, executes the »do« action.";  // untranslated
Blockly.Msg.IMAGE_GET_TOOLTIP = "Returns the chosen image.";  // untranslated
Blockly.Msg.IMAGE_GET_TOOLTIP_ANGRY = "rozzlobený";
Blockly.Msg.IMAGE_GET_TOOLTIP_ASLEEP = "spící";
Blockly.Msg.IMAGE_GET_TOOLTIP_BUTTERFLY = "motýl";
Blockly.Msg.IMAGE_GET_TOOLTIP_CHESSBOARD = "šachovnice";
Blockly.Msg.IMAGE_GET_TOOLTIP_CONFUSED = "zmatený";
Blockly.Msg.IMAGE_GET_TOOLTIP_COW = "kráva";
Blockly.Msg.IMAGE_GET_TOOLTIP_DIAMOND = "diamant";
Blockly.Msg.IMAGE_GET_TOOLTIP_DIAMOND_SMALL = "malý diamant";
Blockly.Msg.IMAGE_GET_TOOLTIP_DUCK = "kachna";
Blockly.Msg.IMAGE_GET_TOOLTIP_FABULOUS = "báječný";
Blockly.Msg.IMAGE_GET_TOOLTIP_GHOST = "duch";
Blockly.Msg.IMAGE_GET_TOOLTIP_GIRAFFE = "žirafa";
Blockly.Msg.IMAGE_GET_TOOLTIP_HEART = "srdce";
Blockly.Msg.IMAGE_GET_TOOLTIP_HEART_SMALL = "malé srdce";
Blockly.Msg.IMAGE_GET_TOOLTIP_HOUSE = "dům";
Blockly.Msg.IMAGE_GET_TOOLTIP_MEH = "meh!";
Blockly.Msg.IMAGE_GET_TOOLTIP_MUSIC_CROTCHET = "čtvrťová nota";
Blockly.Msg.IMAGE_GET_TOOLTIP_MUSIC_QUAVER = "osminová nota";
Blockly.Msg.IMAGE_GET_TOOLTIP_MUSIC_QUAVERS = "osminové noty";
Blockly.Msg.IMAGE_GET_TOOLTIP_NO = "ne";
Blockly.Msg.IMAGE_GET_TOOLTIP_PACMAN = "pacman";
Blockly.Msg.IMAGE_GET_TOOLTIP_PITCHFORK = "vidle";
Blockly.Msg.IMAGE_GET_TOOLTIP_RABBIT = "králík";
Blockly.Msg.IMAGE_GET_TOOLTIP_ROLLERSKATE = "brusle";
Blockly.Msg.IMAGE_GET_TOOLTIP_SAD = "smutný";
Blockly.Msg.IMAGE_GET_TOOLTIP_SILLY = "pošetilý";
Blockly.Msg.IMAGE_GET_TOOLTIP_SKULL = "lebka";
Blockly.Msg.IMAGE_GET_TOOLTIP_SMILE = "úsměv";
Blockly.Msg.IMAGE_GET_TOOLTIP_SNAKE = "had";
Blockly.Msg.IMAGE_GET_TOOLTIP_SQUARE = "čtverec";
Blockly.Msg.IMAGE_GET_TOOLTIP_SQUARE_SMALL = "malý čtverec";
Blockly.Msg.IMAGE_GET_TOOLTIP_STICKFIGURE = "postava";
Blockly.Msg.IMAGE_GET_TOOLTIP_SWORD = "meč";
Blockly.Msg.IMAGE_GET_TOOLTIP_TARGET = "cíl";
Blockly.Msg.IMAGE_GET_TOOLTIP_TORTOISE = "želva";
Blockly.Msg.IMAGE_GET_TOOLTIP_TRIANGLE = "trojúhelník";
Blockly.Msg.IMAGE_GET_TOOLTIP_TRIANGLE_LEFT = "trojúhelník vlevo";
Blockly.Msg.IMAGE_GET_TOOLTIP_TSHIRT = "tričko";
Blockly.Msg.IMAGE_GET_TOOLTIP_UMBRELLA = "deštník";
Blockly.Msg.IMAGE_GET_TOOLTIP_XMAS = "Vánoce";
Blockly.Msg.IMAGE_GET_TOOLTIP_YES = "ano";
Blockly.Msg.IMAGE_INVERT = "převrátit";
Blockly.Msg.IMAGE_INVERT_TOOLTIP = "Invertuje obrázek. Pixely s hodnotou 0 nebo \"žádná\" budou nastaveny na hodnotu # nebo 9, pixely s hodnotou # nebo 9 budou nastaveny na hodnotu 0 nebo \"žádná\".";
Blockly.Msg.IMAGE_SHIFT = "posun";
Blockly.Msg.IMAGE_SHIFT_TOOLTIP = "Posune obrázek v zadaném směru o zadanou hodnotou.";
Blockly.Msg.IMAGE_TOOLTIP = "Vytvoří obrázek pro displej.";
Blockly.Msg.INFO_DOCUMENTATION_HINT = "Document your program here ...";  // untranslated
Blockly.Msg.INFO_TAGS = "Tags";  // untranslated
Blockly.Msg.INFRARED_DISTANCE_GETSAMPLE_TOOLTIP = "Gets the current relative distance from the infrared sensor. The values are between 1 and 75 cm.";  // untranslated
Blockly.Msg.INFRARED_GETSAMPLE_TOOLTIP = "Vráti aktuální hodnotu infračerveného senzoru.";
Blockly.Msg.INFRARED_PRESENCE_GETSAMPLE_TOOLTIP = "Returns an array of measurements for the presence of a beacon.";  // untranslated
Blockly.Msg.INFRARED_TOOLTIP = "Představuje infračervený senzor.";
Blockly.Msg.INLINE_INPUTS = "Vložené vstupy";
Blockly.Msg.INTERNAL_PORT = "internal";  // untranslated
Blockly.Msg.JOYSTICK_GETSAMPLE_TOOLTIP = "Gets the current reading of one of the axises of the joystick";  // untranslated
Blockly.Msg.KEY_ISPRESSED_TOOLTIP = "Je vybrané tlačítko stisknuto?";
Blockly.Msg.LANGUAGE_ARABIC = "Arabic";  // untranslated
Blockly.Msg.LANGUAGE_BRAZILIAN = "Brazilian";  // untranslated
Blockly.Msg.LANGUAGE_CHINESE = "Chinese";  // untranslated
Blockly.Msg.LANGUAGE_CZECH = "Czech";  // untranslated
Blockly.Msg.LANGUAGE_DANISH = "Danish";  // untranslated
Blockly.Msg.LANGUAGE_DUTCH = "Dutch";  // untranslated
Blockly.Msg.LANGUAGE_ENGLISH = "English";  // untranslated
Blockly.Msg.LANGUAGE_FINNISH = "Finnish";  // untranslated
Blockly.Msg.LANGUAGE_FRENCH = "French";  // untranslated
Blockly.Msg.LANGUAGE_GERMAN = "German";  // untranslated
Blockly.Msg.LANGUAGE_GREEK = "Greek";  // untranslated
Blockly.Msg.LANGUAGE_ITALIAN = "Italian";  // untranslated
Blockly.Msg.LANGUAGE_JAPANESE = "Japanese";  // untranslated
Blockly.Msg.LANGUAGE_KOREAN = "Korean";  // untranslated
Blockly.Msg.LANGUAGE_NORWEGIAN = "Norwegian";  // untranslated
Blockly.Msg.LANGUAGE_POLISH = "Polish";  // untranslated
Blockly.Msg.LANGUAGE_PORTUGUESE = "Portuguese";  // untranslated
Blockly.Msg.LANGUAGE_RUSSIAN = "Russian";  // untranslated
Blockly.Msg.LANGUAGE_SPANISH = "Spanish";  // untranslated
Blockly.Msg.LANGUAGE_SWEDISH = "Swedish";  // untranslated
Blockly.Msg.LANGUAGE_TURKISH = "Turkish";  // untranslated
Blockly.Msg.LED = "LED";  // untranslated
Blockly.Msg.LED_OFF = "vypne LED";
Blockly.Msg.LED_OFF_TOOLTIP = "Turns the LED off.";  // untranslated
Blockly.Msg.LED_ON = "zapne LED";
Blockly.Msg.LED_ON_TOOLTIP = "Zapne LED a změní barvu.";
Blockly.Msg.LED_ON_WHITE_TOOLTIP = "Turns the LED on. Watch out, it's very bright!";  // untranslated
Blockly.Msg.LEFT = "left";  // untranslated
Blockly.Msg.LIGHT_ARDU_TOOLTIP = "Představuje 8 světelných senzorů.";
Blockly.Msg.LIGHT_GETSAMPLE_TOOLTIP = "Vrátí aktuální hodnotu světelného senzoru.";
Blockly.Msg.LIGHT_TOOLTIP = "Představuje světelný senzor.";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "vytvořit prázdný seznam";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Vrátí seznam nulové délky, který neobsahuje žádné datové záznamy";
Blockly.Msg.LISTS_CREATE_TITLE = "seznam";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "seznam";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Přidat, odebrat nebo změnit pořadí oddílů tohoto seznamu bloku.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "vytvořit seznam s";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Přidat položku do seznamu.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Vytvoř seznam s libovolným počtem položek.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "první";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# od konce";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "získat";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "získat a odstranit";
Blockly.Msg.LISTS_GET_INDEX_LAST = "poslední";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "náhodné";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "odstranit";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Vrátí první položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Vrátí položku z určené pozice v seznamu.  #1 je poslední položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Vrátí položku z určené pozice v seznamu.  #1 je první položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Vrátí poslední položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Vrátí náhodnou položku ze seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Odstraní a vrátí první položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Odstraní a vrátí položku z určené pozice v seznamu.  #1 je poslední položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Odstraní a vrátí položku z určené pozice v seznamu.  #1 je první položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Odstraní a vrátí poslední položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Odstraní a vrátí náhodnou položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Odstraní první položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Odstraní položku na konkrétním místu v seznamu. #1 je poslední položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Odebere položku na konkrétním místě v seznamu.  #1 je první položka.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Odstraní poslední položku v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Odstraní náhodou položku v seznamu.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "do # od konce";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "do #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "jako poslední";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "získat podseznam od první položky";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "získat podseznam od # od konce";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "získat podseznam od #";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Vytvoří kopii určené části seznamu.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "najít první výskyt položky";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "najít poslední výskyt položky";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Vrací index prvního/posledního výskytu položky v seznamu. Vrací 0, pokud položka nebyla nalezena.";
Blockly.Msg.LISTS_INLIST = "v seznamu";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";  // untranslated
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 je prázdné";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Vrátí hodnotu pravda, pokud je seznam prázdný.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "délka %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Vrací počet položek v seznamu.";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "vytvoř seznam s položkou %1 opakovanou %1 krát";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Vytváří seznam obsahující danou hodnotu n-krát.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "jako";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "vložit na";
Blockly.Msg.LISTS_SET_INDEX_SET = "nastavit";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Vložit položku na začátek seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Vloží položku na určenou pozici v seznamu.  #1 je poslední položka.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Vloží položku na určenou pozici v seznamu.  #1 je první položka.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Připojí položku na konec seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Připojí položku náhodně do seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Nastaví první položku v seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Nastaví položku na konkrétní místo v seznamu. #1 je poslední položka.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Nastaví položku na konkrétní místo v seznamu. #1 je první položka.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Nastaví poslední položku v seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Nastaví náhodnou položku v seznamu.";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";  // untranslated
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "ascending";  // untranslated
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "descending";  // untranslated
Blockly.Msg.LISTS_SORT_TITLE = "sort %1 %2 %3";  // untranslated
Blockly.Msg.LISTS_SORT_TOOLTIP = "Sort a copy of a list.";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "alphabetic, ignore case";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "numeric";  // untranslated
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "alphabetic";  // untranslated
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";  // untranslated
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "udělat z textu seznam";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "udělat ze seznamu text";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Spojit seznam textů do jednoho textu, rozdělaného oddělovači.";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Rozdělit text do seznamu textů, lámání na oddělovačích.";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "s oddělovačem";
Blockly.Msg.LIST_BACK_TOOLTIP = "Zpět na předchozí pohled.";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "nepravda";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Vrací pravda nebo nepravda.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "pravda";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://cs.wikipedia.org/wiki/Nerovnost_(matematika)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Vrátí hodnotu pravda, pokud se oba vstupy rovnají jeden druhému.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Navrátí hodnotu pravda, pokud první vstup je větší než druhý vstup.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Navrátí hodnotu pravda, pokud je první vstup větší a nebo rovný druhému vstupu.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Navrátí hodnotu pravda, pokud je první vstup menší než druhý vstup.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Navrátí hodnotu pravda, pokud je první vstup menší a nebo rovný druhému vstupu.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Vrátí hodnotu pravda, pokud se oba vstupy nerovnají sobě navzájem.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "ne %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Navrátí hodnotu pravda, pokud je vstup nepravda. Navrátí hodnotu nepravda, pokud je vstup pravda.";
Blockly.Msg.LOGIC_NULL = "prázdný";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Vrátí prázdnou hodnotu";
Blockly.Msg.LOGIC_OPERATION_AND = "a";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "nebo";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Vrátí hodnotu pravda, pokud oba dva vstupy jsou pravdivé.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Vrátí hodnotu pravda, pokud alespoň jeden ze vstupů má hodnotu pravda.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://cs.wikipedia.org/wiki/Ternární operátor (programování)";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "pokud nepravda";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "pokud pravda";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Zkontroluje podmínku v \"testu\". Když je podmínka pravda, vrátí hodnotu \"pokud pravda\"; v opačném případě vrátí hodnotu \"pokud nepravda\".";
Blockly.Msg.LOOP = "repeat until";  // untranslated
Blockly.Msg.LOOPFOREVER_TOOLTIP = "Opakuje akci stále.";
Blockly.Msg.LOOP_FOREVER = "opakuj stále";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://cs.wikipedia.org/wiki/Aritmetika";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Vrátí součet dvou čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Vrátí podíl dvou čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Vrátí rozdíl dvou čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Vrátí součin dvou čísel.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Vrátí první číslo umocněné na druhé číslo.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_TITLE = "zaměň %1 za %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Přičti číslo k proměnné '%1'.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Vraťte jednu z následujících konstant: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (nekonečno).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "omez %1 na rozmezí od %2 do %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Omezí číslo tak, aby bylo ve stanovených mezích (včetně).";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "je dělitelné číslem";
Blockly.Msg.MATH_IS_EVEN = "je sudé";
Blockly.Msg.MATH_IS_NEGATIVE = "je záporné";
Blockly.Msg.MATH_IS_ODD = "je liché";
Blockly.Msg.MATH_IS_POSITIVE = "je kladné";
Blockly.Msg.MATH_IS_PRIME = "je prvočíslo";
Blockly.Msg.MATH_IS_TOOLTIP = "Kontrola, zda je číslo sudé, liché, prvočíslo, celé, kladné, záporné nebo zda je dělitelné daným číslem. Vrací pravdu nebo nepravdu.";
Blockly.Msg.MATH_IS_WHOLE = "je celé";
Blockly.Msg.MATH_MODULO_HELPURL = "https://cs.wikipedia.org/wiki/Modul%C3%A1rn%C3%AD_aritmetika";
Blockly.Msg.MATH_MODULO_TITLE = "zbytek po dělení %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Vrátí zbytek po dělení dvou čísel.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";
Blockly.Msg.MATH_NUMBER_HELPURL = "https://cs.wikipedia.org/wiki/Číslo";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Číslo.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "průměr v seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "největší v seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "medián v seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "nejmenší v seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "nejčastější ze seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "náhodná položka seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "směrodatná odchylka ze seznamu";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "suma seznamu";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Vrátí průměr (aritmetický průměr) číselných hodnot v seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Vrátí největší číslo v seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Vrátí medián seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Vrátí nejmenší číslo v seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Vrátí seznam nejčastějších položek seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Vrátí náhodnou položku ze seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Vrátí směrodatnou odchylku seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Vrátí součet všech čísel v seznamu.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://cs.wikipedia.org/wiki/Gener%C3%A1tor_n%C3%A1hodn%C3%BDch_%C4%8D%C3%ADsel";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "náhodné číslo mezi 0 (včetně) do 1";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Vrátí náhodné číslo mezi 0,0 (včetně) až 1,0";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://cs.wikipedia.org/wiki/Gener%C3%A1tor_n%C3%A1hodn%C3%BDch_%C4%8D%C3%ADsel";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "náhodné celé číslo od %1 do %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Vrací náhodné celé číslo mezi dvěma určenými mezemi, včetně mezních hodnot.";
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "zaokrouhlit";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "zaokrouhlit dolů";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "zaokrouhlit nahoru";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Zaokrouhlit číslo nahoru nebo dolů.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://cs.wikipedia.org/wiki/Druhá_odmocnina";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "absolutní hodnota";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "druhá odmocnina";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Vrátí absolutní hodnotu čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Vrátí mocninu čísla e.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Vrátí přirozený logaritmus čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Vrátí desítkový logaritmus čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Vrátí zápornou hodnotu čísla.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Vrátí mocninu čísla 10.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Vrátí druhou odmocninu čísla.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";
Blockly.Msg.MATH_TRIG_ACOS = "acos";
Blockly.Msg.MATH_TRIG_ASIN = "arcsin";
Blockly.Msg.MATH_TRIG_ATAN = "arctan";
Blockly.Msg.MATH_TRIG_COS = "cos";
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "sin";
Blockly.Msg.MATH_TRIG_TAN = "tan";
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Vrátí arkus kosinus čísla.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Vrátí arkus sinus čísla.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Vrátí arkus tangens čísla.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Vrátí kosinus úhlu ve stupních.";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Vrátí sinus úhlu ve stupních.";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Vrátí tangens úhlu ve stupních.";
Blockly.Msg.ME = "Já";
Blockly.Msg.MENU_ABOUT = "o aplikaci";
Blockly.Msg.MENU_ABOUT_PROJECT = "about the Open Roberta Project";  // untranslated
Blockly.Msg.MENU_ATTACH = "připojit...";
Blockly.Msg.MENU_BEGINNER = "začátečník";
Blockly.Msg.MENU_CHANGE = "změnit...";
Blockly.Msg.MENU_CHECK = "zkontrolovat";
Blockly.Msg.MENU_CODE_DOWNLOAD_TOOLTIP = "Stáhne zdrojový kód programu do počítače.";
Blockly.Msg.MENU_CODE_REFRESH_TOOLTIP = "Aktualizuje zdrojový kód, pokud jste změnili NEPO bloky.";
Blockly.Msg.MENU_CONNECT = "připojit...";
Blockly.Msg.MENU_CREATE_LINK = "vytvořit propojení programu...";
Blockly.Msg.MENU_DELETE_USER = "smazat uživatele...";
Blockly.Msg.MENU_EDIT = "úpravy";
Blockly.Msg.MENU_EDIT_TOOLTIP = "úpravy";
Blockly.Msg.MENU_EV3 = "Robot preparation";  // untranslated
Blockly.Msg.MENU_EXPERT = "expert";
Blockly.Msg.MENU_EXPORT_PROG = "exportovat program";
Blockly.Msg.MENU_FAQ = "otázky a odpovědi";
Blockly.Msg.MENU_GALLERY = "galerie";
Blockly.Msg.MENU_GALLERY_TOOLTIP = "galerie";
Blockly.Msg.MENU_GENERAL = "obecná nápověda";
Blockly.Msg.MENU_HELP = "nápověda";
Blockly.Msg.MENU_HELP_TOOLTIP = "nápověda";
Blockly.Msg.MENU_IMPORT_PROG = "importovat program";
Blockly.Msg.MENU_LANGUAGE = "jazyky";
Blockly.Msg.MENU_LANGUAGE_TOOLTIP = "jazyky";
Blockly.Msg.MENU_LIST = "list ...";  // untranslated
Blockly.Msg.MENU_LIST_CONF = "moje nastavení...";
Blockly.Msg.MENU_LIST_PROG = "moje programy...";
Blockly.Msg.MENU_LIST_PROG_EXAMPLES = "ukázkové programy...";
Blockly.Msg.MENU_LOGGING = "historie provedených akcí";
Blockly.Msg.MENU_LOG_IN = "přihlásit se...";
Blockly.Msg.MENU_LOG_OUT = "odhlásit se";
Blockly.Msg.MENU_MESSAGE_DOWNLOAD = "Program byl úspěšně stažen.";
Blockly.Msg.MENU_NEW = "nový...";
Blockly.Msg.MENU_PROGRAMMING = "programming with NEPO";  // untranslated
Blockly.Msg.MENU_PROPERTIES = "vlastnosti";
Blockly.Msg.MENU_RIGHT_HELP_TOOLTIP = "Otevře/zavře zobrazení nápovědy";
Blockly.Msg.MENU_RIGHT_INFO_TOOLTIP = "Otevře/zavře zobrazení informací";
Blockly.Msg.MENU_ROBOT = "robot";
Blockly.Msg.MENU_ROBOT_STATE_INFO = "informace";
Blockly.Msg.MENU_ROBOT_STATE_TOOLTIP = "Informace o robotovi";
Blockly.Msg.MENU_ROBOT_STOP_HINT_EV3 = "Press <span class='typcn typcn-media-stop'></span>+<span class='typcn typcn-arrow-sorted-down'></span> buttons on the robot to abort the program!";  // untranslated
Blockly.Msg.MENU_ROBOT_STOP_HINT_NXT = "Press <span class='typcn typcn-media-cancel'></span> button on the robot to abort the program!";  // untranslated
Blockly.Msg.MENU_ROBOT_TOOLTIP = "roboti";
Blockly.Msg.MENU_SAVE = "uložit";
Blockly.Msg.MENU_SAVE_AS = "uložit jako...";
Blockly.Msg.MENU_SHOW_AGAIN = "jdi na úvodní obrazovku";
Blockly.Msg.MENU_SHOW_CODE = "ukázat kód";
Blockly.Msg.MENU_SIM_BACK = "Zpět";
Blockly.Msg.MENU_SIM_DRAW = "Scéna Kreslení";
Blockly.Msg.MENU_SIM_IMPORT_TOOLTIP = "Nahraje váš vlastní obrázek jako pozadí simulátoru, pozadí bude přidáno na konec seznamu.";
Blockly.Msg.MENU_SIM_MATH = "Scéna Matematika";
Blockly.Msg.MENU_SIM_POSE_TOOLTIP = "Move the robot back to it's initial position.";  // untranslated
Blockly.Msg.MENU_SIM_RESCUE = "Scéna Záchrana";
Blockly.Msg.MENU_SIM_ROBERTA = "Scéna Roberta";
Blockly.Msg.MENU_SIM_ROBOT_TOOLTIP = "otevře/zavře pohled robota";
Blockly.Msg.MENU_SIM_SCENE_TOOLTIP = "změní scénu";
Blockly.Msg.MENU_SIM_SIMPLE = "Scéna Jednoduchá";
Blockly.Msg.MENU_SIM_START_TOOLTIP = "Spustí váš program v simulátoru.";
Blockly.Msg.MENU_SIM_STOP = "Stop";
Blockly.Msg.MENU_SIM_STOP_TOOLTIP = "Zastaví běh vašeho programu v simulátoru.";
Blockly.Msg.MENU_SIM_VALUES_TOOLTIP = "Otevře/zavře zobrazení dat ze senzorů.";
Blockly.Msg.MENU_SIM_WRO = "Scéna Olympiáda robotů";
Blockly.Msg.MENU_START_BRICK = "spustit v »$«";
Blockly.Msg.MENU_START_SIM = "otevře/zavře okno simulátoru";
Blockly.Msg.MENU_STATE_INFO = "informace o stavu";
Blockly.Msg.MENU_TOOLBOX = "NEPO bloky";
Blockly.Msg.MENU_TOOLBOX_BEGINNER = "NEPO bloky - začátečník";
Blockly.Msg.MENU_TOOLBOX_EXPERT = "NEBO bloky - pokročilý";
Blockly.Msg.MENU_USER = "přihlásit se";
Blockly.Msg.MENU_USER_STATE_TOOLTIP = "informace o uživateli";
Blockly.Msg.MENU_USER_TOOLTIP = "uživatel";
Blockly.Msg.MENU_ZOOM = "měřítko";
Blockly.Msg.MENU_ZOOM_IN = "přiblížit";
Blockly.Msg.MENU_ZOOM_OUT = "oddálit";
Blockly.Msg.MENU_ZOOM_RESET = "výchozí měřítko";
Blockly.Msg.MESSAGE_ADDED_USER = "Uživatel »$« byl přidán";
Blockly.Msg.MESSAGE_CONFIGURATION_DELETED = "Nastavení »$« bylo smazáno";
Blockly.Msg.MESSAGE_EDIT_CHECK = "Váš program je nyní kontrolován!";
Blockly.Msg.MESSAGE_EDIT_SAVE_CONFIGURATION = "Vaše nastavení bylo uloženo.";
Blockly.Msg.MESSAGE_EDIT_SAVE_CONFIGURATION_AS = "Vaše nastavení bylo uloženo jako »$«";
Blockly.Msg.MESSAGE_EDIT_SAVE_GROUP_AS = "Vaše skupina byla vytvořena";
Blockly.Msg.MESSAGE_EDIT_SAVE_PROGRAM = "Váš program byl uložen";
Blockly.Msg.MESSAGE_EDIT_SAVE_PROGRAM_AS = "Váš program byl uložen jako »$«";
Blockly.Msg.MESSAGE_EDIT_START = "Váš program $ se za chvíli spustí!";
Blockly.Msg.MESSAGE_FIRMWARE_ERROR = "Verze firmwaru vašeho robota a verze Open Roberta Lab se liší. Kontaktujte nás prosím.";
Blockly.Msg.MESSAGE_GROUP_DELETED = "Skupina »$« byla smazána";
Blockly.Msg.MESSAGE_INVALID_NAME = "Vyplňte prosím správné jméno. Musí začínat písmenem a může obsahovat pouze písmena a číslice.";
Blockly.Msg.MESSAGE_NOT_AVAILABLE = "Nedostupné";
Blockly.Msg.MESSAGE_PROGRAM_DELETED = "Program »$« byl smazán";
Blockly.Msg.MESSAGE_RESTART_ROBOT = "Připojte prosím robota znovu k Open Roberta Lab.";
Blockly.Msg.MESSAGE_ROBOT_CONNECTED = "Váš robot $ je připojen";
Blockly.Msg.MESSAGE_ROBOT_DISCONNECTED = "An active robot was disconnected";  // untranslated
Blockly.Msg.MESSAGE_USER_DELETED = "Uživatel byl smazán";
Blockly.Msg.MESSAGE_USER_GROUP_DELETED = "Uživatel »$« byl smazán";
Blockly.Msg.MESSAGE_USER_LOGIN = "Ahoj »$«";
Blockly.Msg.MESSAGE_USER_LOGOUT = "Byl jste odhlášen";
Blockly.Msg.MICROBITBRICK_TOOLTIP = "Představuje desku micro:bit, kapesní programovatelný počítač. Jsou zde také dostupné zabudované pohony a senzory, například tlačítka, displej...";
Blockly.Msg.MICROPHONE_GETSAMPLE_TOOLTIP = "Vrátí aktuální hodnotu mikrofonu.";
Blockly.Msg.MODE = "mód";
Blockly.Msg.MODE_ACCELERATION = "zrychlení";
Blockly.Msg.MODE_AMBIENTLIGHT = "okolní světlo";
Blockly.Msg.MODE_ANALOG = "analog";  // untranslated
Blockly.Msg.MODE_ANGLE = "úhel";
Blockly.Msg.MODE_CLOSE = "zavřít";
Blockly.Msg.MODE_COLOUR = "barva";
Blockly.Msg.MODE_COMPASS = "compass";  // untranslated
Blockly.Msg.MODE_DEGREE = "stupňů";
Blockly.Msg.MODE_DIGITAL = "digital";  // untranslated
Blockly.Msg.MODE_DISTANCE = "vzdálenost";
Blockly.Msg.MODE_LIGHT = "světlo";
Blockly.Msg.MODE_OBSTACLE = "překážka";
Blockly.Msg.MODE_OPEN = "otevřít";
Blockly.Msg.MODE_ORIENTATION = "směr";
Blockly.Msg.MODE_PRESENCE = "přítomnost";
Blockly.Msg.MODE_PRESSED = "pressed";  // untranslated
Blockly.Msg.MODE_PULSE_HIGH = "pulse time HIGH";  // untranslated
Blockly.Msg.MODE_PULSE_LOW = "pulse time LOW";  // untranslated
Blockly.Msg.MODE_RATE = "rychlost změny";
Blockly.Msg.MODE_RGB = "RGB";
Blockly.Msg.MODE_ROTATION = "otáčky";
Blockly.Msg.MODE_SOUND = "zvuk";
Blockly.Msg.MODE_VALUE = "value";  // untranslated
Blockly.Msg.MOTOR = "motor";
Blockly.Msg.MOTORDIFF_ON_FOR_TOOLTIP = "Spustí pohyb robota danou rychlostí a zastaví ho po určené vzdálenosti.";
Blockly.Msg.MOTORDIFF_ON_TOOLTIP = "Spustí pohyb robota danou rychlostí.";
Blockly.Msg.MOTORDIFF_STOP_TOOLTIP = "Zastaví robota.";
Blockly.Msg.MOTORDIFF_TURN_FOR_TOOLTIP = "Otáčení robota o zadaný počet stupňů.";
Blockly.Msg.MOTORDIFF_TURN_TOOLTIP = "Otáčení robota.";
Blockly.Msg.MOTOR_ARDU_TOOLTIP = "Představuje motor na podvozku robota Bot'n Roll.";
Blockly.Msg.MOTOR_BACKWARD = "dozadu";
Blockly.Msg.MOTOR_BIG = "velký";
Blockly.Msg.MOTOR_BIG_TOOLTIP = "Představuje velký motor.";
Blockly.Msg.MOTOR_BRAKE = "brzda";
Blockly.Msg.MOTOR_DEGREE = "stupně";
Blockly.Msg.MOTOR_DISTANCE = "vzdálenost v cm";
Blockly.Msg.MOTOR_DRIVE = "jeď";
Blockly.Msg.MOTOR_FLOAT = "uvolnit";
Blockly.Msg.MOTOR_FOREWARD = "dopředu";
Blockly.Msg.MOTOR_GETPOWER_TOOLTIP = "Vrátí aktuální rychlost/sílu tohoto motoru.";
Blockly.Msg.MOTOR_LEFT = "vlevo";
Blockly.Msg.MOTOR_MIDDLE = "střední";
Blockly.Msg.MOTOR_MIDDLE_TOOLTIP = "Představuje střední motor.";
Blockly.Msg.MOTOR_NONE = "žádný";
Blockly.Msg.MOTOR_ON_FOR_TOOLTIP = "Spustí motor a zastaví ho po otočení o daný počet otáček/stupňů.";
Blockly.Msg.MOTOR_ON_TOOLTIP = "Spustí motor určitou rychlostí/silou.";
Blockly.Msg.MOTOR_OTHER = "jiné výstupní zařízení";
Blockly.Msg.MOTOR_PAN = "přejíždět";
Blockly.Msg.MOTOR_PORT = "port motoru";
Blockly.Msg.MOTOR_REGULATION = "regulace";
Blockly.Msg.MOTOR_RIGHT = "vpravo";
Blockly.Msg.MOTOR_ROTATION = "otáčka";
Blockly.Msg.MOTOR_ROTATION_REVERSE = "směr otáčení";
Blockly.Msg.MOTOR_SETPOWER_TOOLTIP = "Nastaví rychlost/sílu tohoto motoru.";
Blockly.Msg.MOTOR_SIDE = "strana";
Blockly.Msg.MOTOR_SPEED = "rychlost %";
Blockly.Msg.MOTOR_SPEED_0 = "Motor Speed is 0!";  // untranslated
Blockly.Msg.MOTOR_STEER = "zatáčej";
Blockly.Msg.MOTOR_STOP = "zastav";
Blockly.Msg.MOTOR_STOP_TOOLTIP = "Zastaví tento motor.";
Blockly.Msg.MOTOR_TILT = "naklonit";
Blockly.Msg.MOTOR_TURN = "zatáčej";
Blockly.Msg.NAO_ABSOLUTE = "absolutní";
Blockly.Msg.NAO_ACCELEROMETER = "akcelerometr";
Blockly.Msg.NAO_ACCELEROMETER_TOOLTIP = "Vrátí aktuální hodnotu akcelerometru v daném směru";
Blockly.Msg.NAO_ANIMATION_TOOLTIP = "Spustí vybranou animaci.";
Blockly.Msg.NAO_ANSWER = "odpověď";
Blockly.Msg.NAO_APPLYPOSTURE = "použij postoj";
Blockly.Msg.NAO_APPLYPOSTURE_TOOLTIP = "Robot jde to vybraného postoje.";
Blockly.Msg.NAO_AUTONOMOUS = "autonomous life";  // untranslated
Blockly.Msg.NAO_AUTONOMOUS_TOOLTIP = "Turn the robots autonomous life on or off. When it is turned on the robot will react to sounds and try to detect faces. Turn it off if this behaviour interrupts your programm.";  // untranslated
Blockly.Msg.NAO_BLINK = "blikat";
Blockly.Msg.NAO_CAMERA = "kamera";
Blockly.Msg.NAO_CAMERA_BOTTOM = "spodní";
Blockly.Msg.NAO_CAMERA_TOP = "vrchní";
Blockly.Msg.NAO_CURRENT = "elektrický proud";
Blockly.Msg.NAO_DETECTFACE = "detekuje tvář";
Blockly.Msg.NAO_DETECTFACE_TOOLTIP = "Detekuje tvář dříve uloženou pod daným jménem";
Blockly.Msg.NAO_DIALOG_TOOLTIP = "Robot se pokusí rozpoznat frázi a odpovědět v případě úspěchu.";
Blockly.Msg.NAO_FACE_GET_INFORMATION = "get information about recognized face";  // untranslated
Blockly.Msg.NAO_FACE_GET_INFORMATION_TOOLTIP = "This block will return additional information about the given recognized face in the format on a 1-d array with following values: [XAngle, YAngle, XSize, YSize, Heading], please note that all values are given in camera angles.";  // untranslated
Blockly.Msg.NAO_FILENAME = "jméno souboru";
Blockly.Msg.NAO_FORGETFACEOF = "zapomeň tvář";
Blockly.Msg.NAO_FORGETFACE_TOOLTIP = "Zapomeň tvář dříve uloženou pod daným jménem";
Blockly.Msg.NAO_FRAME = "snímek";
Blockly.Msg.NAO_FRAME_TORSO = "trup";
Blockly.Msg.NAO_FRAME_WORLD = "světlo";
Blockly.Msg.NAO_FSR = "tlakový senzor";
Blockly.Msg.NAO_FSR_TOOLTIP = "Vrátí aktuální hodnotu tlakového senzoru pod nohou robota.";
Blockly.Msg.NAO_GETCURRENT_TOOLTIP = "Vrátí hodnotu proudu z vybraného kloubu.";
Blockly.Msg.NAO_GETLANGUAGE = "vrať jazyk";
Blockly.Msg.NAO_GETLANGUAGE_TOOLTIP = "Vrátí aktivní jazyk.";
Blockly.Msg.NAO_GETVOLUME_TOOLTIP = "Vrátí hlasitost.";
Blockly.Msg.NAO_GYROMETER = "gyrometr";
Blockly.Msg.NAO_GYROMETER_TOOLTIP = "Vrátí aktuální hodnotu gyrometru v daném směru.";
Blockly.Msg.NAO_HAND = "ruka";
Blockly.Msg.NAO_HAND_TOOLTIP = "Otevřít/zavřít ruku";
Blockly.Msg.NAO_HEADSENSOR = "hlavový senzor";
Blockly.Msg.NAO_INTENSITY = "intenzita";
Blockly.Msg.NAO_JOINT_ANKLEPITCH = "sklon kotníku";
Blockly.Msg.NAO_JOINT_ANKLEROLL = "náklon kotníku";
Blockly.Msg.NAO_JOINT_ELBOWROLL = "náklon lokte";
Blockly.Msg.NAO_JOINT_ELBOWYAW = "natočení lokte";
Blockly.Msg.NAO_JOINT_HAND = "ruka";
Blockly.Msg.NAO_JOINT_HEADPITCH = "sklon hlavy";
Blockly.Msg.NAO_JOINT_HEADYAW = "natočení hlavy";
Blockly.Msg.NAO_JOINT_HIPPITCH = "sklon kyčle";
Blockly.Msg.NAO_JOINT_HIPROLL = "náklon kyčle";
Blockly.Msg.NAO_JOINT_HIPYAWPITCH = "natočení kyčle";
Blockly.Msg.NAO_JOINT_KNEEPITCH = "sklon kolena";
Blockly.Msg.NAO_JOINT_SHOULDERPITCH = "sklon ramene";
Blockly.Msg.NAO_JOINT_SHOULDERROLL = "náklon ramene";
Blockly.Msg.NAO_JOINT_WRISTYAW = "natočení zápěstí";
Blockly.Msg.NAO_LEARNFACEOF = "naučit se tvář";
Blockly.Msg.NAO_LEARNFACE_TOOLTIP = "Naučí a uloží tvář pod zadaným jménem";
Blockly.Msg.NAO_LED = "led";
Blockly.Msg.NAO_LEDOFF_TOOLTIP = "Vyplne LED.";
Blockly.Msg.NAO_LEDRESET_TOOLTIP = "Resetuje LED.";
Blockly.Msg.NAO_LED_ALL = "vše";
Blockly.Msg.NAO_LED_CHEST = "hruď";
Blockly.Msg.NAO_LED_EAR = "ucho";
Blockly.Msg.NAO_LED_EARS = "uši";
Blockly.Msg.NAO_LED_EYE = "oko";
Blockly.Msg.NAO_LED_EYES = "oči";
Blockly.Msg.NAO_LED_FOOT = "noha";
Blockly.Msg.NAO_LED_HEAD = "hlava";
Blockly.Msg.NAO_LED_TOOLTIP = "Nastaví barvu skupiny LED.";
Blockly.Msg.NAO_LOOKAT = "podívej se na";
Blockly.Msg.NAO_MARK_GET_INFORMATION = "get information about NAO mark";  // untranslated
Blockly.Msg.NAO_MARK_GET_INFORMATION_TOOLTIP = "This block will return additional information about the given NAO mark in the format on a 1-d array with following values: [XAngle, YAngle, XSize, YSize, Heading], please note that all values are given in camera angles.";  // untranslated
Blockly.Msg.NAO_MODE_ACTIVE = "aktivní";
Blockly.Msg.NAO_MODE_REST = "odpočívat";
Blockly.Msg.NAO_MODE_SIT = "sednout";
Blockly.Msg.NAO_MODE_TOOLTIP = "Aktivuje motory a robot se postaví, nebo přejde od odpočinkového postoje a motory vypne.";
Blockly.Msg.NAO_MOVE = "pobyb";
Blockly.Msg.NAO_MOVEJOINT_TOOLTIP = "Pobyb jednoho kloubu.";
Blockly.Msg.NAO_NAOMARK = "detekuje NAO značku";
Blockly.Msg.NAO_NAOMARK_TOOLTIP = "Vrátí počet detekovaných NAO značek.";
Blockly.Msg.NAO_PART_ARM = "paže";
Blockly.Msg.NAO_PART_ARMS = "paže";
Blockly.Msg.NAO_PART_BODY = "tělo";
Blockly.Msg.NAO_PART_HEAD = "hlava";
Blockly.Msg.NAO_PART_LEG = "noha";
Blockly.Msg.NAO_PART_LEGS = "nohy";
Blockly.Msg.NAO_PERFORM = "proveď";
Blockly.Msg.NAO_PHRASE = "fráze";
Blockly.Msg.NAO_PLAYFILE_TOOLTIP = "Přehraje zvukový soubor z robota.";
Blockly.Msg.NAO_PLAY_FILE = "přehraje soubor";
Blockly.Msg.NAO_POINTAT = "ukaž na";
Blockly.Msg.NAO_POINTLOOKAT_TOOLTIP = "Robot ukáže nebo se podívá na zadané místo";
Blockly.Msg.NAO_POSTURE_CROUCH = "dřepnout si";
Blockly.Msg.NAO_POSTURE_LYINGBACK = "lehnout si na záda";
Blockly.Msg.NAO_POSTURE_LYINGBELLY = "lehnout si na břicho";
Blockly.Msg.NAO_POSTURE_SITRELAX = "posadit se";
Blockly.Msg.NAO_POSTURE_STAND = "postavit se";
Blockly.Msg.NAO_POSTURE_STANDINIT = "postavit se";
Blockly.Msg.NAO_POSTURE_STANDZERO = "postavit se";
Blockly.Msg.NAO_QQVGA = "160*120";
Blockly.Msg.NAO_QVGA = "320*240";
Blockly.Msg.NAO_RANDOMEYES = "náhodné oči";
Blockly.Msg.NAO_RANDOMEYES_TOOLTIP = "Barva očí se náhodně mění po zadaný čas.";
Blockly.Msg.NAO_RASTA = "rasta";
Blockly.Msg.NAO_RASTA_TOOLTIP = "Barva očí se mění mezi zelenou, žlutou a červenou po zadaný čas.";
Blockly.Msg.NAO_RECOGNIZEDWORD = "recognized word";  // untranslated
Blockly.Msg.NAO_RECOGNIZEDWORD_TOOLTIP = "Returns the last word the robot recognized.";  // untranslated
Blockly.Msg.NAO_RECOGNIZEWORD = "recognize word from list";  // untranslated
Blockly.Msg.NAO_RECOGNIZEWORDOR = "rozpoznané slovo";
Blockly.Msg.NAO_RECOGNIZEWORD_TOOLTIP = "Return a word from the given list when recognized by NAO";  // untranslated
Blockly.Msg.NAO_RECORDVIDEO = "zaznamenej video";
Blockly.Msg.NAO_RECORDVIDEO_TOOLTIP = "Zaznamená video a uloží ho v robotovi.";
Blockly.Msg.NAO_RELATIVE = "relativní";
Blockly.Msg.NAO_RESOLUTION = "rozlišení";
Blockly.Msg.NAO_SETINTENSITY_TOOLTIP = "Nastaví intenzitu skupiny LED.";
Blockly.Msg.NAO_SETLANGUAGE_TOOLTIP = "Nastaví jazyk.";
Blockly.Msg.NAO_SETVOLUME_TOOLTIP = "Nastaví hlasitost.";
Blockly.Msg.NAO_STIFFNESS = "tuhost";
Blockly.Msg.NAO_STIFFNESS_TOOLTIP = "Tuhost vybrané části těla je zapnuta nebo vypnuta";
Blockly.Msg.NAO_STOP = "přeruš pohyb";
Blockly.Msg.NAO_STOP_TOOLTIP = "Robot zastaví všechny pohyby.";
Blockly.Msg.NAO_TAI_CHI = "tai chi";
Blockly.Msg.NAO_TAKEPICTURE = "vyfoť";
Blockly.Msg.NAO_TAKEPICTURE_TOOLTIP = "Vyfotí obrázek a uloží ho v robotovi.";
Blockly.Msg.NAO_TOUCHSENSOR_TOOLTIP = "Je pravda pokud je dotykový senzor robota stisknut.";
Blockly.Msg.NAO_TOUCH_BUMPER = "nárazník";
Blockly.Msg.NAO_TOUCH_FRONT = "přední";
Blockly.Msg.NAO_TOUCH_HAND = "ruka";
Blockly.Msg.NAO_TOUCH_REAR = "zadní";
Blockly.Msg.NAO_TURN_TOOLTIP = "Otočí robota o zadaný počet stupňů";
Blockly.Msg.NAO_VGA = "640*480";
Blockly.Msg.NAO_WALK = "jdi";
Blockly.Msg.NAO_WALKTO = "jdi k";
Blockly.Msg.NAO_WALKTO_TOOLTIP = "Robot jde k zadanému místu.";
Blockly.Msg.NAO_WALK_ASYNC_TOOLTIP = "Makes the robot walk infinitely";  // untranslated
Blockly.Msg.NAO_WALK_TOOLTIP = "Robot ujde danou vzdálenost.";
Blockly.Msg.NAO_WAVE = "zamávej";
Blockly.Msg.NAO_WIPE_FOREHEAD = "otřít čelo";
Blockly.Msg.NEW_VARIABLE = "Nová proměnná...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Nový název proměnné:";
Blockly.Msg.NO = "ne";
Blockly.Msg.NXTBRICK_TOOLTIP = "Představuje kostku NXT s připojenými motory a senzory. Jsou zde také dostupné zabudované součásti, například tlačítka, displej...";
Blockly.Msg.OFF = "vypnout";
Blockly.Msg.OLDER_THEN_14 = "I am 16 or older than 16!";  // untranslated
Blockly.Msg.ON = "zapnout";
Blockly.Msg.ORA_ACCOUNT_NOT_ACTIVATED_TO_SHARE = "Your are not allowed to share. Please activate your account! <br><a href='https://www.roberta-home.de/index.php?id=138&L=1' target='_blank'>Further information ...</a>";  // untranslated
Blockly.Msg.ORA_COMMAND_INVALID = "Chybný příkaz Javascriptu";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_CONFIGURATION_NOT_FOUND = "Nastavení robota není možné najít na serveru.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_CONFIGURATION_TRANSFORM_FAILED = "Nastavení robota nemůže být převedeno do programovacího jazyka robota.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_COMPILE_FAILED = "Program nemůže být přeložen do strojového kódu.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_GENERATION_FAILED = "Program nemůže být vygenerován.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_NOT_FOUND = "Program nelze převést do programovacího jazyku robota.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_STORE_FAILED = "Program nelze uložit z důvodu vnitřní chyby.";
Blockly.Msg.ORA_COMPILERWORKFLOW_ERROR_PROGRAM_TRANSFORM_FAILED = "Program nelze převést do programovacího jazyku robota.";
Blockly.Msg.ORA_CONFIGURATION_DELETE_ERROR = "Při mazání nastavení robota došlo k chybě, zkuste to znovu!";
Blockly.Msg.ORA_CONFIGURATION_DELETE_SUCCESS = "Nastavení smazáno";
Blockly.Msg.ORA_CONFIGURATION_ERROR_ID_INVALID = "Název nastavení není platný identifikátor";
Blockly.Msg.ORA_CONFIGURATION_GET_ALL_SUCCESS = "Nastavení nahráno";
Blockly.Msg.ORA_CONFIGURATION_GET_ONE_ERROR_NOT_FOUND = "Nastavení robota není možné najít v databázi.";
Blockly.Msg.ORA_CONFIGURATION_GET_ONE_SUCCESS = "Nastavení nahráno";
Blockly.Msg.ORA_CONFIGURATION_SAVE_ERROR = "Při ukládání nastavení robota došlo k chybě.";
Blockly.Msg.ORA_CONFIGURATION_SAVE_ERROR_NOT_SAVED_TO_DB = "An error error has occurred while saving the configuration in the database.";  // untranslated
Blockly.Msg.ORA_CONFIGURATION_SAVE_SUCCESS = "Nastavení uloženo";
Blockly.Msg.ORA_GALLERY_UPLOAD_ERROR = "Your program »$« couldn't be uploaded to the gallery, it seems as if it is already uploaded.";  // untranslated
Blockly.Msg.ORA_GALLERY_UPLOAD_SUCCESS = "Your program »$« is now in the gallery!";  // untranslated
Blockly.Msg.ORA_GROUP_CREATE_ERROR_NOT_SAVED_TO_DB = "This group already exists";  // untranslated
Blockly.Msg.ORA_LIKE_DELETE_SUCCESS = "You do not like program »$« anymore!";  // untranslated
Blockly.Msg.ORA_LIKE_SAVE_ERROR_EXISTS = "You couldn't like program »$«. Maybe you have already liked it.";  // untranslated
Blockly.Msg.ORA_LIKE_SAVE_SUCCESS = "You like program »$« now!";  // untranslated
Blockly.Msg.ORA_OWNER_DOES_NOT_EXIST = "Vlastník neexistuje";
Blockly.Msg.ORA_PROGRAM_CONFIGURATION_NOT_COMPATIBLE = "Program is not compatible with the configuration";  // untranslated
Blockly.Msg.ORA_PROGRAM_DELETE_ERROR = "Při mazání nastavení došlo k chybě. Prosím zkuste to znovu!";
Blockly.Msg.ORA_PROGRAM_DELETE_SUCCESS = "Program smazán";
Blockly.Msg.ORA_PROGRAM_ERROR_ID_INVALID = "Název vašeho programu už v systému existuje. Zvolte prosím jiný název a zkuste to znovu!";
Blockly.Msg.ORA_PROGRAM_GET_ALL_SUCCESS = "Program nahrán";
Blockly.Msg.ORA_PROGRAM_GET_ONE_ERROR_NOT_FOUND = "Program nebyl nalezen.";
Blockly.Msg.ORA_PROGRAM_GET_ONE_ERROR_NOT_LOGGED_IN = "Nejste přihlášen, prosím přihlašte se pomocí vašeho uživatelského jméno a hesla nebo si založte nový účet.";
Blockly.Msg.ORA_PROGRAM_GET_ONE_SUCCESS = "Program nahrán";
Blockly.Msg.ORA_PROGRAM_IMPORT_ERROR = "Tento program nemá formát NEPO programu a nemůže být nahrán!";
Blockly.Msg.ORA_PROGRAM_IMPORT_ERROR_WRONG_ROBOT_TYPE = "Pokoušíte se importovat program pro robota jiného typu než je nastaveno v menu. <br> Prosím změňte typ robota v menu a zkuste import znovu!";
Blockly.Msg.ORA_PROGRAM_INVALID_STATEMETNS = "There are errors in your program. Please check the messages";  // untranslated
Blockly.Msg.ORA_PROGRAM_SAVE_AS_ERROR_PROGRAM_EXISTS = "Program už existuje.";
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_NO_WRITE_PERMISSION = "Nemáte právo měnit tento program!";
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_OPTIMISTIC_TIMESTAMP_LOCKING = "Tento program byl naposledy změněn někým jiným. Pro uložení vašich změn do nového programu vyberte >uložit jako< !";
Blockly.Msg.ORA_PROGRAM_SAVE_ERROR_PROGRAM_TO_UPDATE_NOT_FOUND = "Program nelze nalézt, proto ho nelze aktualizovat.";
Blockly.Msg.ORA_PROGRAM_SAVE_SUCCESS = "Program uložen";
Blockly.Msg.ORA_PROGRAM_TO_SHARE_DOES_NOT_EXIST = "Program, který chcete sdílet, neexistuje.";
Blockly.Msg.ORA_ROBOT_DOES_NOT_EXIST = "It seems that we do not support the desired robot system!<br>Please choose another one.";  // untranslated
Blockly.Msg.ORA_ROBOT_FIRMWAREUPDATE_IMPOSSIBLE = "Při aktualizaci firmware vašeho robota došlo k chybě.";
Blockly.Msg.ORA_ROBOT_FIRMWAREUPDATE_POSSIBLE = "Firmware byl aktualizován";
Blockly.Msg.ORA_ROBOT_NOT_CONNECTED = "Robot není připojen. Zkontrolujte, zda je robot zapnut, připojte ho k serveru a zadejte jeho heslo v menu robot-připojení. <br />Pokud máte stále problémy, podívejte se na stránky s nápovědou.";
Blockly.Msg.ORA_ROBOT_NOT_WAITING = "Robot nečeká na příkaz start.";
Blockly.Msg.ORA_ROBOT_PUSH_RUN = "Robot čekal a nyní je soubor jar přenášen do robota.";
Blockly.Msg.ORA_ROBOT_PUSH_RUN_CALLIOPE2016 = "Your program »$« is downloaded to Calliope, press the reset button to start it!";  // untranslated
Blockly.Msg.ORA_ROBOT_PUSH_RUN_NXT = "Your program »$« is downloaded to the NXT, start it on the robot!";  // untranslated
Blockly.Msg.ORA_ROBOT_SET_SUCCESS = "Switched to robot system »$«!";  // untranslated
Blockly.Msg.ORA_SERVER_ERROR = "Chyba serveru";
Blockly.Msg.ORA_TOKEN_SET_ERROR_NO_ROBOT_WAITING = "Zkontrolujte, zda je robot zapnut a připojen k serveru. <br />Pokud máte stále problémy, podívejte se na stránky s nápovědou.";
Blockly.Msg.ORA_TOKEN_SET_ERROR_WRONG_ROBOTTYPE = "Pokoušíte se připojit robota jiného typu než je nastaveno v menu. <br> Prosím, vyberte v menu správný typ robota a zkuste se připojit znovu!";
Blockly.Msg.ORA_TOKEN_SET_SUCCESS = "Kód nastaven";
Blockly.Msg.ORA_TOOLBOX_DELETE_ERROR = "An error has occurred while deleting the toolbox, please try it again!";  // untranslated
Blockly.Msg.ORA_TOOLBOX_DELETE_SUCCESS = "Toolbox deleted";  // untranslated
Blockly.Msg.ORA_TOOLBOX_ERROR_ID_INVALID = "Název palety nástrojů není platný.";
Blockly.Msg.ORA_TOOLBOX_GET_ALL_SUCCESS = "Toolbox loaded";  // untranslated
Blockly.Msg.ORA_TOOLBOX_GET_ONE_ERROR_NOT_FOUND = "Paleta nástrojů nemůže být nalezena v databázi.";
Blockly.Msg.ORA_TOOLBOX_GET_ONE_SUCCESS = "Paleta nástrojů nahrána";
Blockly.Msg.ORA_TOOLBOX_SAVE_ERROR = "Při ukládání palety nástrojů došlo k chybě.";
Blockly.Msg.ORA_TOOLBOX_SAVE_ERROR_NOT_SAVED_TO_DB = "An error error has occurred while saving the configuration in the database.";  // untranslated
Blockly.Msg.ORA_TOOLBOX_SAVE_SUCCESS = "Toolbox saved";  // untranslated
Blockly.Msg.ORA_TOOLBOX_TRANSFORM_ERROR = "Transformation error?";  // untranslated
Blockly.Msg.ORA_USER_ACTIVATION_INVALID_URL = "The link is not valid anymore. Please ask for resending your verification mail again";  // untranslated
Blockly.Msg.ORA_USER_ACTIVATION_SENT_MAIL_FAIL = "Sorry, we cannot send a mail to you, please contact »roberta-zentrale@iais.fraunhofer.de«";  // untranslated
Blockly.Msg.ORA_USER_ACTIVATION_SENT_MAIL_SUCCESS = "We send a mail to you, please check your mailbox!";  // untranslated
Blockly.Msg.ORA_USER_ACTIVATION_SUCCESS = "Your account is successfully verified! Please login!";  // untranslated
Blockly.Msg.ORA_USER_CREATE_ERROR_ACCOUNT_LENGTH = "Vámi zvolené jméno účtu nebo vaše uživatelské jméno je příliš dlouhé. Nemělo by být delší než 25 znaků. Váš účet nemohl být vytvořen.";
Blockly.Msg.ORA_USER_CREATE_ERROR_CONTAINS_SPECIAL_CHARACTERS = "Používáte jeden nebo více speciálních znaků ve vašem jméně účtu! Odstraňte je prosím. Váš účet nemohl být vytvořen.";
Blockly.Msg.ORA_USER_CREATE_ERROR_MISSING_REQ_FIELDS = "Zkontrolujte, zda všechna požadovaná pole byla vyplněna. Váš účet nemohl být vytvořen.";
Blockly.Msg.ORA_USER_CREATE_ERROR_NOT_SAVED_TO_DB = "Zadané uživatelské jméno již existuje v databázi, zvolte prosím jiné jméno.";
Blockly.Msg.ORA_USER_CREATE_SUCCESS = "Váš uživatelský účet »$« byl úspěšně vytvořen!";
Blockly.Msg.ORA_USER_DEACTIVATION_SUCCESS = "Your account is currently not verified, please check your mailbox!";  // untranslated
Blockly.Msg.ORA_USER_DELETE_ERROR_ID_NOT_FOUND = "Chyba při mazání uživatele.";
Blockly.Msg.ORA_USER_DELETE_ERROR_NOT_DELETED_IN_DB = "Chyba při mazání uživatele v databázi.";
Blockly.Msg.ORA_USER_DELETE_SUCCESS = "Váš účet »$« byl úspěšně vymazán. Doufáme, že se opět brzy uvidíme!";
Blockly.Msg.ORA_USER_EMAIL_ONE_ERROR_USER_NOT_EXISTS_WITH_THIS_EMAIL = "Tento e-mail je neznámý, možná překlep?";
Blockly.Msg.ORA_USER_ERROR_EMAIL_USED = "Účet s touto e-mailovou adresou je již registrován. Zvolte prosím jinou e-mailovou adresu!";
Blockly.Msg.ORA_USER_GET_ALL_SUCCESS = "Uživatel nahrán";
Blockly.Msg.ORA_USER_GET_ONE_ERROR_ID_OR_PASSWORD_WRONG = "Zadali jste špatné uživatelské jméno nebo heslo. Zkuste to znovu!";
Blockly.Msg.ORA_USER_GET_ONE_SUCCESS = "Přihlášení bylo úspěšné";
Blockly.Msg.ORA_USER_GROUP_SAVE_AS_ERROR_USER_GROUP_EXISTS = "This user already belongs to the group";  // untranslated
Blockly.Msg.ORA_USER_PASSWORD_RECOVERY_EXPIRED_URL = "Odkaz již není platný. Prosím požádejte znovu o resetování svého hesla, pokud si ho stále nepamatujete.";
Blockly.Msg.ORA_USER_PASSWORD_RECOVERY_SENT_MAIL_FAIL = "Omlouváme se, ale nemůžeme vám poslat email, kontaktuje prosím »roberta-zentrale@iais.fraunhofer.de«";
Blockly.Msg.ORA_USER_PASSWORD_RECOVERY_SENT_MAIL_SUCCESS = "Email odeslán, zkontrolujte si prosím emailovou schránku!";
Blockly.Msg.ORA_USER_TO_ADD_NOT_FOUND = "Uživatel nebyl nalezen";
Blockly.Msg.ORA_USER_TO_SHARE_DOES_NOT_EXIST = "Uživatel, se kterým chcete sdílet program, neexistuje. <br />Zkuste to znovu!";
Blockly.Msg.ORA_USER_TO_SHARE_SAME_AS_LOGIN_USER = "Nemůžete sdílet program sám se sebou.";
Blockly.Msg.ORA_USER_UPDATE_SUCCESS = "Vaše heslo bylo úspěšně změněno!";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PIN_GETSAMPLE_ANALOG_TOOLTIP = "Returns the value from the specified analog pin. The value is between 0 and 1023.";  // untranslated
Blockly.Msg.PIN_GETSAMPLE_DIGITAL_TOOLTIP = "Returns the value from the specified digital pin. The value is either HIGH »1« or LOW »0«.";  // untranslated
Blockly.Msg.PIN_GETSAMPLE_PULSEHIGH_TOOLTIP = "Returns the pulse HIGH on a pin in microseconds or -1 if no complete pulse was received within the timeout.";  // untranslated
Blockly.Msg.PIN_GETSAMPLE_PULSELOW_TOOLTIP = "Returns the pulse LOW on a pin in microseconds or -1 if no complete pulse was received within the timeout.";  // untranslated
Blockly.Msg.PIN_ISTOUCHED_TOOLTIP = "Je vybraný pin stisknutý?";
Blockly.Msg.PIN_WRITE = "zapiš";
Blockly.Msg.PITCH = "sklon";
Blockly.Msg.PLAY = "přehraj tón";
Blockly.Msg.PLAY_DURATION = "doba trvání v ms";
Blockly.Msg.PLAY_EIGHTH = "osminová nota";
Blockly.Msg.PLAY_FILE = "soubor";
Blockly.Msg.PLAY_FILE_TOOLTIP = "Přehraje zvukový soubor.";
Blockly.Msg.PLAY_FREQUENZ = "frekvence v Hz";
Blockly.Msg.PLAY_GETVOLUME_TOOLTIP = "Vrátí aktuální hlasitost.";
Blockly.Msg.PLAY_HALF = "půlová nota";
Blockly.Msg.PLAY_NOTE = "note";  // untranslated
Blockly.Msg.PLAY_NOTE_TOOLTIP = "Přehraje notu";
Blockly.Msg.PLAY_QUARTER = "čtrťová nota";
Blockly.Msg.PLAY_SETVOLUME_TOOLTIP = "Nastaví hlasitost.";
Blockly.Msg.PLAY_SIXTEENTH = "šestnáctinová nota";
Blockly.Msg.PLAY_TONE = "tone";  // untranslated
Blockly.Msg.PLAY_TONE_TOOLTIP = "Přehraje tón.";
Blockly.Msg.PLAY_VOLUME = "hlasitost";
Blockly.Msg.PLAY_WHOLE = "celá nota";
Blockly.Msg.POPUP_ABOUT_JOIN = "Rád bych pomohl";
Blockly.Msg.POPUP_ABOUT_TEXT = "Open Roberta Lab je online integrované vývojové prostředí které umožňuje dětem snadno programovat různé robotické systémy. Prostředí je zcela open source, takže se můžete bez obav zapojit! Jak programy tak vývojové nástroje jsou dostupné na serverech Fraunhoferova institutu.";
Blockly.Msg.POPUP_ABOUT_TEXT_DEV = "Open Roberta Lab je open source vývojová platforma vyvinutá Fraunhofer IAIS v rámci iniciativy <a href='http://www.roberta-home.de/'>»Roberta – Učení s roboty«</a>";
Blockly.Msg.POPUP_ABOUT_TEXT_GOOG = "Open Roberta byla založena ve spolupráci s Google Německo aby zmenšila překážky studentů, učitelů a škol při programování výukových robotů. Open Roberta je financována  Google.org (2014 - 2015) částkou 1Mio Euro.</a>";
Blockly.Msg.POPUP_AGE = "Age";  // untranslated
Blockly.Msg.POPUP_ATTENTION = "Pozor";
Blockly.Msg.POPUP_BEFOREUNLOAD = "V programu nebo nastavení jsou neuložené změny. Přihlašte se a uložte program nebo nastavení.";
Blockly.Msg.POPUP_BEFOREUNLOAD_LOGGEDIN = "V programu nebo nastavení jsou neuložené změny.";
Blockly.Msg.POPUP_CANCEL = "Storno";
Blockly.Msg.POPUP_CHANGE_PASSWORD = "změna hesla...";
Blockly.Msg.POPUP_CONFIRM_CONTINUE = "<br><br><i>Press »OK« to discard your work. Press »Cancel« to stay here and save your work first.</i>";  // untranslated
Blockly.Msg.POPUP_CONFIRM_DELETE_CONFIGURATION = "Opravdu chcete smazat nastavení?";
Blockly.Msg.POPUP_CONFIRM_DELETE_GROUP = "Do you really want to delete these groups?";  // untranslated
Blockly.Msg.POPUP_CONFIRM_DELETE_PROGRAM = "Opravdu chcete smazat program?";
Blockly.Msg.POPUP_CONFIRM_DELETE_USER_GROUP = "Do you really want to remove these users below from the current group?";  // untranslated
Blockly.Msg.POPUP_CONFIRM_UPDATE_FIRMWARE = "Pro vašeho robota je k dispozici nový firmware. Můžete zkusit spustit program se starým firmware, ale nejlépe bude když firmware svého robota nyní aktualizujete! Stačí, když kliknete na >>Aktualizovat nyní<<.";
Blockly.Msg.POPUP_CONTINUE = "continue anyway";  // untranslated
Blockly.Msg.POPUP_DOWNLOAD = "Nahrát váš program do »$«";
Blockly.Msg.POPUP_DOWNLOAD_CHECK = "OK, změnil jsem trvale složku pro stahování souborů ve svém prohlížeči. Toto okno už nezobrazuj a stahuj moje programy přímo.";
Blockly.Msg.POPUP_DOWNLOAD_SAVE = "Uložit";
Blockly.Msg.POPUP_DOWNLOAD_SAVE_AS = "Uložit odkaz jako...";
Blockly.Msg.POPUP_DOWNLOAD_STEP_A = "Klikněte pravým tlačítkem na odkaz na váš proram níže a";
Blockly.Msg.POPUP_DOWNLOAD_STEP_B = "zvolte »Uložit odkaz jako«, potom";
Blockly.Msg.POPUP_DOWNLOAD_STEP_C = "klikněte na váš připojený »$« v levém sloupci,";
Blockly.Msg.POPUP_DOWNLOAD_STEP_D = "nyní klikněte na tlačítko »Uložit« vpravo dole.<br><span style='font-size: 14px;'>Pokud se váš program nespustí automaticky, stiskněte po chvíli tlačítko Reset.</span>";
Blockly.Msg.POPUP_DO_UPDATE_FIRMWARE = "Aktualizovat nyní";
Blockly.Msg.POPUP_EMAIL = "E-mail";
Blockly.Msg.POPUP_EMAIL_SEND = "Odeslat nyní";
Blockly.Msg.POPUP_GET_LINK = "Zde je odkaz na váš aktuální program. Prosím, neměňte ho, pak už pravděpodobně nebude fungovat. Odkaz už byl zkopírován do schránky!</br>$";
Blockly.Msg.POPUP_NAME = "Jméno";
Blockly.Msg.POPUP_NEW_PASSWORD = "Nové heslo";
Blockly.Msg.POPUP_OLD_PASSWORD = "Staré heslo";
Blockly.Msg.POPUP_PASSWORD = "Heslo";
Blockly.Msg.POPUP_PASSWORD_RECOVERY = "resetovat heslo...";
Blockly.Msg.POPUP_PROGRAM_TERMINATED_UNEXPECTED = "Provádění programu robota bylo neočekávaně ukončeno!";
Blockly.Msg.POPUP_REGISTER_USER = "Registrovat nyní";
Blockly.Msg.POPUP_REPEAT_PASSWORD = "Zopakujte heslo";
Blockly.Msg.POPUP_ROBOT_BATTERY = "Napětí";
Blockly.Msg.POPUP_ROBOT_NAME = "Jméno";
Blockly.Msg.POPUP_ROBOT_NOT_CONNECTED = "Nejprve musíte připojit svého robota.";
Blockly.Msg.POPUP_ROBOT_STATE = "Stav";
Blockly.Msg.POPUP_ROBOT_STATE_BUSY = "zaneprázdněn";
Blockly.Msg.POPUP_ROBOT_STATE_DISCONNECTED = "odpojený";
Blockly.Msg.POPUP_ROBOT_STATE_WAIT = "čekej";
Blockly.Msg.POPUP_ROBOT_SYSTEM = "Systém";
Blockly.Msg.POPUP_ROBOT_WAIT = "Čekací doba";
Blockly.Msg.POPUP_STARTUP_COOKIES = "Používáme cookies pro přizpůsobení obsahu a pro analýzu provozu.";
Blockly.Msg.POPUP_STARTUP_HELP = "Potřebujete pomoc?";
Blockly.Msg.POPUP_STARTUP_HELP_TEXT = "V naší podrobné nápovědě je vysvětleno vše, co potřebujete, od instrukcí pro stavbu po často kladené otázky. Vše jen anglicky!";
Blockly.Msg.POPUP_STARTUP_HIDE = "OK, toto okno už nezobrazuj a pamatuj si moji volbu.";
Blockly.Msg.POPUP_STARTUP_START = "Vyberte váš systém!";
Blockly.Msg.POPUP_STARTUP_TOUR_TEXT = "Chcete začít, ale nevíte jak? Ukážeme vám první kroky v interaktivním tutoriálu.";
Blockly.Msg.POPUP_TOUR = "prohlídka";
Blockly.Msg.POPUP_USERNAME = "Uživatelské jméno";
Blockly.Msg.POPUP_USERNAME_LOGOFF = "Nejste přihlášen.";
Blockly.Msg.POPUP_VALUE = "Hodnota";
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "povolit příkazy";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "s:";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://cs.wikipedia.org/wiki/Funkce_(programov%C3%A1n%C3%AD)";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Spustí uživatelem definovanou funkci '%1'.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://cs.wikipedia.org/wiki/Funkce_(programov%C3%A1n%C3%AD)";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Spustí uživatelem definovanou funkci '%1' a použije její výstup.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "s:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Vytvořit '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Popište tuto funkci...";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://cs.wikipedia.org/w/index.php?title=Funkce_(programování)";
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "proveď něco";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "k provedení";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Vytvořit funkci bez výstupu.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://cs.wikipedia.org/w/index.php?title=Funkce_(programování)";
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "navrátit";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Vytvořit funkci s výstupem.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Upozornění: Tato funkce má duplicitní parametry.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Zvýraznit definici funkce";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Je-li hodnota pravda, pak vrátí druhou hodnotu.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Varování: Tento blok může být použit pouze uvnitř definici funkce.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "vstupní jméno:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Přidat vstupy do funkce.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "vstupy";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Přidat, odebrat nebo změnit pořadí vstupů této funkce.";
Blockly.Msg.PROCEDURES_TITLE = "procedura";
Blockly.Msg.PROCEDURES_VARIABLES_ERROR = "Chyba: Tento blok může být použit jen v rámci »";
Blockly.Msg.PROCEDURES_VARIABLES_LOOP_ERROR = "Chyba: Tento blok může být použit jen v rámci cyklu který deklaruje";
Blockly.Msg.PROGLIST_DELETE_ALL_TOOLTIP = "Klikněte zde pro smazání všech vybraných programů.";
Blockly.Msg.PROGLIST_DELETE_TOOLTIP = "Klikněte zde pro smazání vašeho programu.";
Blockly.Msg.PROGLIST_LOAD_TOOLTIP = "Klikněte zde pro nahrání konfigurace vašeho robota do prostředí pro nastavování.";
Blockly.Msg.PROGLIST_SHARE_TOOLTIP = "Klikněte zde pro sdílení vašeho programu s přítelem.";
Blockly.Msg.PROGLIST_SHARE_WITH_GALLERY = "Opravdu chcete sdílet váš program se všemi?";
Blockly.Msg.PROGLIST_SHARE_WITH_GALLERY_TOOLTIP = "Click here to upload your program to the gallery hence share it with all other users.";  // untranslated
Blockly.Msg.PULSE_HIGH = "pulse time HIGH";  // untranslated
Blockly.Msg.PULSE_LOW = "pulse time LOW";  // untranslated
Blockly.Msg.RADIO_GET_RSSI_TOOLTIP = "Gets the RSSI of the last package.";  // untranslated
Blockly.Msg.REDO = "Redo";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "Odstranit komentář";
Blockly.Msg.RENAME_VARIABLE = "Přejmenovat proměnnou...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Přejmenuj všech '%1' proměnných na:";
Blockly.Msg.RESEND_ACTIVATION = "resend verification email";  // untranslated
Blockly.Msg.RETURN = "návrat";
Blockly.Msg.RIGHT = "right";  // untranslated
Blockly.Msg.ROLL = "náklon";
Blockly.Msg.SAY = "say";  // untranslated
Blockly.Msg.SAY_PARAMETERS_TOOLTIP = "The robot says the given text. It is also possible to enter special charaters. The robot will use the selected language to try and speak the entered text. Modify the speed (range: 0-100) and the pitch of the voice (range: 0-100) with the input fields";  // untranslated
Blockly.Msg.SAY_TOOLTIP = "The robot says the given text. It is also possible to enter special charaters. The robot will use the selected language to try and speak the entered text.";  // untranslated
Blockly.Msg.SEND_DATA = "data to send";  // untranslated
Blockly.Msg.SENSOR_ACCELEROMETER = "accelerometer";  // untranslated
Blockly.Msg.SENSOR_AMBIENTLIGHT = "ambientlight sensor";  // untranslated
Blockly.Msg.SENSOR_ANY = "anyplace";  // untranslated
Blockly.Msg.SENSOR_ARM_TOOLTIP = "Returns true, if the selected part of the arm is touched, otherwise false.";  // untranslated
Blockly.Msg.SENSOR_BATTERY = "napětí ve V";
Blockly.Msg.SENSOR_BOTTOM = "bottom";  // untranslated
Blockly.Msg.SENSOR_CALIBRATE = "calibrate";  // untranslated
Blockly.Msg.SENSOR_CODE = "code pad";  // untranslated
Blockly.Msg.SENSOR_COLOUR = "barevný senzor";
Blockly.Msg.SENSOR_COMPASS = "kompas";
Blockly.Msg.SENSOR_ENCODER = "tachometr";
Blockly.Msg.SENSOR_FLAME = "flame sensor";  // untranslated
Blockly.Msg.SENSOR_GESTURE = "gesto";
Blockly.Msg.SENSOR_GESTURE_ACTIVE = "aktivní?";
Blockly.Msg.SENSOR_GESTURE_DOWN = "dolů";
Blockly.Msg.SENSOR_GESTURE_DOWN_GETSAMPLE_TOOLTIP = "Returns »true« if the posture is down.";  // untranslated
Blockly.Msg.SENSOR_GESTURE_FACE_DOWN = "vepředu";
Blockly.Msg.SENSOR_GESTURE_FACE_DOWN_GETSAMPLE_TOOLTIP = "Returns »true« if the posture is face down.";  // untranslated
Blockly.Msg.SENSOR_GESTURE_FACE_UP = "vzadu";
Blockly.Msg.SENSOR_GESTURE_FACE_UP_GETSAMPLE_TOOLTIP = "Returns »true« if the posture is face up.";  // untranslated
Blockly.Msg.SENSOR_GESTURE_FREEFALL = "volný pád";
Blockly.Msg.SENSOR_GESTURE_FREEFALL_GETSAMPLE_TOOLTIP = "Returns »true« if it is free falling.";  // untranslated
Blockly.Msg.SENSOR_GESTURE_SHAKE = "třesení";
Blockly.Msg.SENSOR_GESTURE_SHAKE_GETSAMPLE_TOOLTIP = "Returns »true« if it is shaken.";  // untranslated
Blockly.Msg.SENSOR_GESTURE_TOOLTIP = "Is the system in the selected state?";  // untranslated
Blockly.Msg.SENSOR_GESTURE_UP = "nahoru";
Blockly.Msg.SENSOR_GESTURE_UP_GETSAMPLE_TOOLTIP = "Returns »true« if the posture is upright.";  // untranslated
Blockly.Msg.SENSOR_GET = "vrať hodnotu";
Blockly.Msg.SENSOR_GET_SAMPLE = "vrať hodnotu";
Blockly.Msg.SENSOR_GROVE = "senzor hloubky";
Blockly.Msg.SENSOR_GYRO = "gyroskop";
Blockly.Msg.SENSOR_INFRARED = "IR senzor";
Blockly.Msg.SENSOR_IS_ARM = "is arm";  // untranslated
Blockly.Msg.SENSOR_IS_PIN = "je";
Blockly.Msg.SENSOR_IS_PRESSED = "stisknuto?";
Blockly.Msg.SENSOR_IS_TOUCHED = "dotýká se?";
Blockly.Msg.SENSOR_JOYSTICK = "joystick";  // untranslated
Blockly.Msg.SENSOR_KEY = "klávesa";
Blockly.Msg.SENSOR_KEY_ANY = "libovolná";
Blockly.Msg.SENSOR_KEY_DOWN = "dolů";
Blockly.Msg.SENSOR_KEY_ENTER = "enter";
Blockly.Msg.SENSOR_KEY_ESCAPE = "esc";
Blockly.Msg.SENSOR_KEY_LEFT = "vlevo";
Blockly.Msg.SENSOR_KEY_RIGHT = "vpravo";
Blockly.Msg.SENSOR_KEY_UP = "nahoru";
Blockly.Msg.SENSOR_LIGHT = "světelný senzor";
Blockly.Msg.SENSOR_MIC = "mikrofon";
Blockly.Msg.SENSOR_MS_TIMER = "v ms";
Blockly.Msg.SENSOR_PIN = "pin";
Blockly.Msg.SENSOR_PINTOUCH = "pin";  // untranslated
Blockly.Msg.SENSOR_PINTOUCH_BOB3 = "arm";  // untranslated
Blockly.Msg.SENSOR_PRESSED = "(stisknuto)";
Blockly.Msg.SENSOR_RADIO_RSSI = "radio RSSI sensor";  // untranslated
Blockly.Msg.SENSOR_RESET = "vynuluj";
Blockly.Msg.SENSOR_RESET_II = "";  // untranslated
Blockly.Msg.SENSOR_RSSI = "signal strength";  // untranslated
Blockly.Msg.SENSOR_RSSI_VALUE_GETSAMPLE_TOOLTIP = "Gets the signal strength from the last received message.";  // untranslated
Blockly.Msg.SENSOR_SONAR = "sonar";
Blockly.Msg.SENSOR_SOUND = "zvukový senzor";
Blockly.Msg.SENSOR_SOUND_CALLIOPE = "microphone";  // untranslated
Blockly.Msg.SENSOR_TEMPERATURE = "senzor teploty";
Blockly.Msg.SENSOR_TIME = "čas";
Blockly.Msg.SENSOR_TIMER = "časovač";
Blockly.Msg.SENSOR_TOP = "top";  // untranslated
Blockly.Msg.SENSOR_TOUCH = "dotykový senzor";
Blockly.Msg.SENSOR_ULTRASONIC = "ultrazvukový senzor";
Blockly.Msg.SENSOR_UNIT_CM = "cm";  // untranslated
Blockly.Msg.SENSOR_UNIT_DEGREE = "°";  // untranslated
Blockly.Msg.SENSOR_UNIT_MILLIG = "milli-g";  // untranslated
Blockly.Msg.SENSOR_UNIT_MS = "ms";  // untranslated
Blockly.Msg.SENSOR_UNIT_OMEGA = "ω";  // untranslated
Blockly.Msg.SENSOR_UNIT_PERCENT = "%";  // untranslated
Blockly.Msg.SENSOR_UNIT_VOLT = "V";  // untranslated
Blockly.Msg.SENSOR_VALUE = "hodnota";
Blockly.Msg.SERVER_NOT_AVAILABLE = "Open Roberta Lab není momentálně dostupný. </br> Zkontrolujte prosím svoje internetové připojení a zkuste stránku obnovit. Pokud problém přetrvává, kontaktujte prosím:</br>roberta-zentrale@iais.fraunhofer.de";
Blockly.Msg.SET = "nastav";
Blockly.Msg.SETLANGUAGE = "set language";  // untranslated
Blockly.Msg.SETLANGUAGE_TOOLTIP = "Set the language.";  // untranslated
Blockly.Msg.SET_LED = "turn LED";  // untranslated
Blockly.Msg.SIM_BLOCK_NOT_SUPPORTED = "Bohužel tento blok nemůžete použít v simulaci!";
Blockly.Msg.SIM_CONFIGURATION_WARNING_SENSOR_MISSING = "Tento senzor není v nastavení! Chování programu ve skutečném robotovi bude jiné než jste čekali!";
Blockly.Msg.SIM_CONFIGURATION_WARNING_WRONG_INFRARED_SENSOR_PORT = "Infračervený senzor není připojen v nastavení! Chování programu ve skutečném robotovi bude jiné než jste čekali, zkontrolujte prosím konfiguraci robota!";
Blockly.Msg.SIM_CONFIGURATION_WARNING_WRONG_SENSOR_PORT = "V tomto bloku jste použili špatný port senzoru! Chování programu ve skutečném robotovi bude jiné než jste čekali, zkontrolujte prosím konfiguraci robota!";
Blockly.Msg.SLEEP = "sleep";  // untranslated
Blockly.Msg.SOUND_GETSAMPLE_TOOLTIP = "Vráti aktuální hodnotu zvukového senzoru.";
Blockly.Msg.SOUND_TOOLTIP = "Představuje zvukový senzor.";
Blockly.Msg.START = "start";
Blockly.Msg.START_ACTIVITY = "aktivita";
Blockly.Msg.START_ACTIVITY_TOOLTIP = "Spustí doplňkovou aktivitu.";
Blockly.Msg.START_PROGRAM = "start";
Blockly.Msg.START_PROGRAM_DEBUG = "zobrazovat data ze senzorů";
Blockly.Msg.START_TOOLTIP = "Počáteční bod hlavního programu.";
Blockly.Msg.STRENGTH = "síla";
Blockly.Msg.TAB_CONFIGURATION = "Konfigurace robota";
Blockly.Msg.TAB_PROGRAM = "Program";
Blockly.Msg.TEMPERATURE_GETSAMPLE_TOOLTIP = "Vrátí aktuální hodnotu senzoru teploty.";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "přidat text";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "do";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Přidá určitý text k proměnné '%1'.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "na malá písmena";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "na Počáteční Velká Písmena";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "na VELKÁ PÍSMENA";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Vrátí kopii textu s jinou velikostí písmen.";
Blockly.Msg.TEXT_CHARAT_FIRST = "získat první písmeno";
Blockly.Msg.TEXT_CHARAT_FROM_END = "získat # písmeno od konce";
Blockly.Msg.TEXT_CHARAT_FROM_START = "získat písmeno #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "v textu";
Blockly.Msg.TEXT_CHARAT_LAST = "získat poslední písmeno";
Blockly.Msg.TEXT_CHARAT_RANDOM = "získat náhodné písmeno";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Získat písmeno na konkrétní pozici.";
Blockly.Msg.TEXT_COMMENT_TOOLTIP = "Write a comment to your code here, to make it easier for you and others to read and understand your code. It will also generate an inline comment in the generated source code";  // untranslated
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Přidat položku do textu.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "spojit";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Přidat, odebrat nebo změnit pořadí oddílů tohoto textového bloku.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "do # písmene od konce";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "do písmene #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "do posledního písmene";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "v textu";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "získat podřetězec od prvního písmene";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "získat podřetězec od písmene # od konce";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "získat podřetězec od písmene #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Získat zadanou část textu.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "v textu";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "najít první výskyt textu";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "najít poslední výskyt textu";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Vrátí index prvního/posledního výskytu prvního textu v druhém textu.  Pokud text není nalezen, vrátí hodnotu 0.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 je prázdný";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Vrátí pravda pokud je zadaný text prázdný.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "vytvořit text s";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Vytvoří kousek textu spojením libovolného počtu položek.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "délka %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Vrátí počet písmen (včetně mezer) v zadaném textu.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "tisk %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Tisk zadaného textu, čísla nebo jiné hodnoty.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Výzva pro uživatele k zadání čísla.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Výzva pro uživatele k zadání nějakého textu.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "výzva k zadání čísla se zprávou";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "výzva k zadání textu se zprávou";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://cs.wikipedia.org/wiki/Textov%C3%BD_%C5%99et%C4%9Bzec";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Písmeno, slovo nebo řádek textu.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "odstranit mezery z obou stran";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "odstranit mezery z levé strany";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "odstranit mezery z pravé strany";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Vrátí kopii textu s odstraněnými mezerami z jednoho nebo obou konců.";
Blockly.Msg.TIMEOUT = "timeout";  // untranslated
Blockly.Msg.TIMER_GETSAMPLE_TOOLTIP = "Vráti aktuální hodnotu časovače.";
Blockly.Msg.TIMER_RESET_TOOLTIP = "Vynuluje časovač.";
Blockly.Msg.TODAY = "Dnes";
Blockly.Msg.TOOLBOX_ACTION = "Akce";
Blockly.Msg.TOOLBOX_ANIMATION = "Animace";
Blockly.Msg.TOOLBOX_COLOUR = "Barvy";
Blockly.Msg.TOOLBOX_COMMUNICATION = "Zprávy";
Blockly.Msg.TOOLBOX_CONTROL = "Ovládání";
Blockly.Msg.TOOLBOX_DECISION = "Podmínky";
Blockly.Msg.TOOLBOX_DISPLAY = "Displej";
Blockly.Msg.TOOLBOX_DRIVE = "Jízda";
Blockly.Msg.TOOLBOX_IMAGE = "Obrázky";
Blockly.Msg.TOOLBOX_LIGHT = "LED na kostce";
Blockly.Msg.TOOLBOX_LIST = "Seznamy";
Blockly.Msg.TOOLBOX_LOGIC = "Logické spojky";
Blockly.Msg.TOOLBOX_LOOP = "Cykly";
Blockly.Msg.TOOLBOX_MATH = "Matematika";
Blockly.Msg.TOOLBOX_MOVE = "Pohyb";
Blockly.Msg.TOOLBOX_PIN = "Pin";  // untranslated
Blockly.Msg.TOOLBOX_PROCEDURE = "Funkce";
Blockly.Msg.TOOLBOX_SENSOR = "Senzory";
Blockly.Msg.TOOLBOX_SOUND = "Zvuky";
Blockly.Msg.TOOLBOX_TEXT = "Text";
Blockly.Msg.TOOLBOX_VARIABLE = "Proměnné";
Blockly.Msg.TOOLBOX_VISION = "Zrak";
Blockly.Msg.TOOLBOX_WAIT = "Čekání";
Blockly.Msg.TOOLBOX_WALK = "Chůze";
Blockly.Msg.TOUCH_ISPRESSED_TOOLTIP = "Je dotykový senzor stisknut?";
Blockly.Msg.TOUCH_TOOLTIP = "Je dotykový senzor stisknut?";
Blockly.Msg.TOUR1_DESCRIPTION00 = "další";
Blockly.Msg.TOUR1_DESCRIPTION01 = "Vítejte,<br>klikněte na  »další« a zahajte prohlídku Open Roberta Lab.<br>Ukážu vám, jak můžete programovat svého robota pomocí NEPO.<br>Prohlídku můžete kdykoliv ukončit kliknutím na »X« v pravém horním rohu.";
Blockly.Msg.TOUR1_DESCRIPTION02 = "Menu ;-)";
Blockly.Msg.TOUR1_DESCRIPTION03 = "Zde naleznete vše, co potřebujete k programování svého robota!<br><span class='typcn typcn-document-text'></span> Uložit a nahrát programy<br><span class='typcn typcn-Roberta'></span> Připojit robota k Open Roberta Lab<br><span class='typcn typcn-lightbulb'></span> Nápověda s různými problémy<br><span class='typcn typcn-user'></span>Vše o uživatelských účtech, např. přihlašování nebo odhlašování";
Blockly.Msg.TOUR1_DESCRIPTION04 = "Klikněte zde a přepněte se do nastavení robota";
Blockly.Msg.TOUR1_DESCRIPTION05 = "Nastavení robota můžete přizpůsobit později,<br>pokud máte postaveného jiného robota.<br>Pokud žádného robota nemáte a chcete otestovat svůj program v simulaci, <br>použije se toto nastavení.";
Blockly.Msg.TOUR1_DESCRIPTION06 = "Klikněte zde a přepnete se zpět do oblasti pro programování!";
Blockly.Msg.TOUR1_DESCRIPTION07 = "Nástroje.<br>Zde naleznete všechny programové bloky.";
Blockly.Msg.TOUR1_DESCRIPTION07a = "Once you are an experienced user you can switch here to the expert mode of the toolbox.<br>You will then find more blocks to program your robot.<br><span class='typcn typcn-media-stop-outline'></span> beginner mode<br><span class='typcn typcn-star-outline'></span> expert mode";  // untranslated
Blockly.Msg.TOUR1_DESCRIPTION08 = "Každý program začíná startovním blokem«.<br>Další programové bloky, které má robot vykonat, připojte k tomuto bloku.<br>Jednoduše přetáhněte požadovaný blok pod startovní blok.";
Blockly.Msg.TOUR1_DESCRIPTION09 = "Zde najdete pár klávesových zkratek!<br>Zleva doprava:<br><span class='typcn typcn-media-play'></span> Klikněte zde pro spuštění programu ve skutečném robotovi<br><span class='typcn typcn-media-play-outline'></span> Klikněte zde pro spuštění robota v simulátoru<br><span class='typcn typcn-cloud-storage'></span> Uloží program, předtím se ale musíte přihlásit<br><span class='typcn typcn-zoom'></span> Klikněte zde a přibližte si bloky<br><span class='typcn typcn-archive'></span> Odpadkový koš! Jednoduše přesuňte bloky do koše a tím je smažete.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Pozor: Po smazání bloků je už nelze obnovit!<br>";
Blockly.Msg.TOUR1_DESCRIPTION10 = "Klikněte na »Akce«";
Blockly.Msg.TOUR1_DESCRIPTION12 = "Nyní přetáhněte nový blok pod blok začátku programu";
Blockly.Msg.TOUR1_DESCRIPTION13 = "Nyní otevřete simulátor...";
Blockly.Msg.TOUR1_DESCRIPTION13a = "a otestuje svůj program v simulátoru!";
Blockly.Msg.TOUR1_DESCRIPTION15 = "Výborně,<br>váš robot jede 20cm dopředu,<br>to je přesně to, co jste naprogramovali!";
Blockly.Msg.TOUR1_DESCRIPTION16 = "Nashledanou a uživejte si dalších pokusů!";
Blockly.Msg.ULTRASONIC_GETSAMPLE_TOOLTIP = "Vrátí aktuální hodnotu z ultrazvukového senzoru.";
Blockly.Msg.ULTRASONIC_TOOLTIP = "Představuje ultrazvukový senzor.";
Blockly.Msg.UNDO = "Undo";  // untranslated
Blockly.Msg.VALIDATION_CONTAINS_SPECIAL_CHARACTERS = "Povolené speciální znaky: »=+!?.,%#+&^@_-«";
Blockly.Msg.VALIDATION_FIELD_REQUIRED = "Toto pole nemůže být prázdné!";
Blockly.Msg.VALIDATION_MAX_LENGTH = "Maximální délka je 25 znaků!";
Blockly.Msg.VALIDATION_PASSWORD_MIN_LENGTH = "Heslo musí mít nejméně 6 znaků!";
Blockly.Msg.VALIDATION_SECOND_PASSWORD_EQUAL = "Obě hesla musí být stejná!";
Blockly.Msg.VALIDATION_TOKEN_LENGTH = "Symbol musí mít alespoň 8 znaků!";
Blockly.Msg.VALIDATION_VALID_EMAIL_ADDRESS = "Zadejte prosím platnou e-mailovou adresu!";
Blockly.Msg.VALUE_TO = "hodnota";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "položka";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Vytvořit \"nastavit %1\"";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Vrátí hodnotu této proměnné.";
Blockly.Msg.VARIABLES_GLOBAL_DECLARE_TOOLTIP = "Vytvoří globální proměnnou.";
Blockly.Msg.VARIABLES_LOCAL_DECLARE_TOOLTIP = "Vytvoří lokální proměnnou.";
Blockly.Msg.VARIABLES_SET = "nastavit %1 na %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Vytvořit \"získat %1\"";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Nastaví tuto proměnnou, aby se rovnala vstupu.";
Blockly.Msg.VARIABLES_TITLE = "proměnná";
Blockly.Msg.VARIABLES_TYPE_ARRAY_BOOLEAN = "Seznam pravdivostních hodnot";
Blockly.Msg.VARIABLES_TYPE_ARRAY_COLOUR = "List Colour";  // untranslated
Blockly.Msg.VARIABLES_TYPE_ARRAY_CONNECTION = "Seznam připojení";
Blockly.Msg.VARIABLES_TYPE_ARRAY_IMAGE = "Seznam obrázků";
Blockly.Msg.VARIABLES_TYPE_ARRAY_NUMBER = "Seznam čísel";
Blockly.Msg.VARIABLES_TYPE_ARRAY_STRING = "Seznam řetězců";
Blockly.Msg.VARIABLES_TYPE_BOOLEAN = "Pravdivostní hodnota";
Blockly.Msg.VARIABLES_TYPE_COLOUR = "Barva";
Blockly.Msg.VARIABLES_TYPE_CONNECTION = "Připojení";
Blockly.Msg.VARIABLES_TYPE_IMAGE = "Obrázek";
Blockly.Msg.VARIABLES_TYPE_NUMBER = "Číslo";
Blockly.Msg.VARIABLES_TYPE_STRING = "Řetězec";
Blockly.Msg.VARIABLE_USED_BEFORE_DECLARATION = "The variable is used before declaration.";  // untranslated
Blockly.Msg.VOICE_PITCH = "voice pitch";  // untranslated
Blockly.Msg.VOICE_SPEED = "voice speed";  // untranslated
Blockly.Msg.WAIT = "čekej (ms)";
Blockly.Msg.WAIT_FOR_TOOLTIP = "Čeká na hodnoty ze senzorů";
Blockly.Msg.WAIT_OR = "nebo čekej na";
Blockly.Msg.WAIT_TIME_TOOLTIP = "Čeká po určitý čas (v ms).";
Blockly.Msg.WAIT_TOOLTIP = "Čeká, až bude podmínka splněna.";
Blockly.Msg.WAIT_UNTIL = "čekej až";
Blockly.Msg.WRITE_TO_PIN_TOOLTIP = "Pošle hodnotu na vybraný pin.";
Blockly.Msg.X = "x";
Blockly.Msg.Y = "y";
Blockly.Msg.YAW = "yaw";  // untranslated
Blockly.Msg.YES = "ano";
Blockly.Msg.YOUNGER_THEN_14 = "I am younger than 16!";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.SENSOR_PINTOUCH_PRESSED_GETSAMPLE_TOOLTIP = Blockly.Msg.PIN_ISTOUCHED_TOOLTIP;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.KEY_GETSAMPLE_TOOLTIP = Blockly.Msg.KEY_ISPRESSED_TOOLTIP;
Blockly.Msg.SENSOR_INFRARED_GETSAMPLE_TOOLTIP = Blockly.Msg.INFRARED_GETSAMPLE_TOOLTIP;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.MODE_DOWN = Blockly.Msg.SENSOR_GESTURE_DOWN;
Blockly.Msg.SENSOR_ULTRASONIC_GETSAMPLE_TOOLTIP = Blockly.Msg.ULTRASONIC_GETSAMPLE_TOOLTIP;
Blockly.Msg.MODE_SHAKE = Blockly.Msg.SENSOR_GESTURE_SHAKE;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.SENSOR_ENCODER_GETSAMPLE_TOOLTIP = Blockly.Msg.ENCODER_GETSAMPLE_TOOLTIP;
Blockly.Msg.MODE_FACE_UP = Blockly.Msg.SENSOR_GESTURE_FACE_UP;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.MODE_FACE_DOWN = Blockly.Msg.SENSOR_GESTURE_FACE_DOWN;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.SENSOR_COLOUR_GETSAMPLE_TOOLTIP = Blockly.Msg.COLOUR_GETSAMPLE_TOOLTIP;
Blockly.Msg.SENSOR_SOUND_GETSAMPLE_TOOLTIP_CALLIOPE = Blockly.Msg.MICROPHONE_GETSAMPLE_TOOLTIP;
Blockly.Msg.MODE_FREEFALL = Blockly.Msg.SENSOR_GESTURE_FREEFALL;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.SENSOR_TIMER_GETSAMPLE_TOOLTIP = Blockly.Msg.TIMER_GETSAMPLE_TOOLTIP;
Blockly.Msg.SENSOR_ACCELEROMETER_VALUE_GETSAMPLE_TOOLTIP = Blockly.Msg.ACCELEROMETER_ROTATION_TOOLTIP;
Blockly.Msg.ORA_ROBOT_PUSH_RUN = Blockly.Msg.MESSAGE_EDIT_START;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MODE_UP = Blockly.Msg.SENSOR_GESTURE_UP;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.SENSOR_GYRO_GETSAMPLE_TOOLTIP = Blockly.Msg.GYRO_GETSAMPLE_TOOLTIP;
Blockly.Msg.SENSOR_BATTERY_GETSAMPLE_TOOLTIP = Blockly.Msg.BATTERY_GETSAMPLE_TOOLTIP;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.SENSOR_LIGHT_GETSAMPLE_TOOLTIP = Blockly.Msg.LIGHT_GETSAMPLE_TOOLTIP;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.SENSOR_INFRARED_PRESENCE_GETSAMPLE_TOOLTIP = Blockly.Msg.INFRARED_PRESENCE_GETSAMPLE_TOOLTIP;
Blockly.Msg.SENSOR_COMPASS_GETSAMPLE_TOOLTIP = Blockly.Msg.COMPASS_GETSAMPLE_TOOLTIP;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.SENSOR_SOUND_GETSAMPLE_TOOLTIP = Blockly.Msg.SOUND_GETSAMPLE_TOOLTIP;
Blockly.Msg.SENSOR_FLAME_GETSAMPLE_TOOLTIP = Blockly.Msg.FLAME_GETSAMPLE_TOOLTIP;
Blockly.Msg.TOUCH_GETSAMPLE_TOOLTIP = Blockly.Msg.TOUCH_ISPRESSED_TOOLTIP;
Blockly.Msg.SENSOR_INFRARED_DISTANCE_GETSAMPLE_TOOLTIP = Blockly.Msg.INFRARED_DISTANCE_GETSAMPLE_TOOLTIP;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.SENSOR_KEY_GETSAMPLE_TOOLTIP = Blockly.Msg.KEY_GETSAMPLE_TOOLTIP;
Blockly.Msg.SENSOR_TEMPERATURE_GETSAMPLE_TOOLTIP = Blockly.Msg.TEMPERATURE_GETSAMPLE_TOOLTIP;
Blockly.Msg.SENSOR_TOUCH_GETSAMPLE_TOOLTIP = Blockly.Msg.TOUCH_GETSAMPLE_TOOLTIP;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;