// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <ArduinoSTL.h>
#include <list>
#include <NEPODefs.h>

RobertaFunctions rob;

std::list<double> item;
std::list<double> item2;
int _led_L = 13;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    item = {0, 0, 0};
    item2 = {0, 0, 0};
}

void loop()
{
    item2 = _getSubList(item, 0, 0);
    item2 = _getSubList(item, 0, item.size() - 1 - 0);
    item2 = _getSubList(item, 0, item.size() - 1);
    item2 = _getSubList(item, item.size() - 1 - 0, 0);
    item2 = _getSubList(item, item.size() - 1 - 0, item.size() - 1 - 0);
    item2 = _getSubList(item, item.size() - 1 - 0, item.size() - 1);
    item2 = _getSubList(item, 0, 0);
    item2 = _getSubList(item, 0, item.size() - 1 - 0);
    item2 = _getSubList(item, 0, item.size() - 1);
}