// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <NEPODefs.h>


std::list<String> ___item;
double ___item2;
bool ___item3;
int _led_L = 13;
void setup()
{
    pinMode(_led_L, OUTPUT);
    ___item = {"b", "v", "b"};
    ___item2 = _getFirstOccuranceOfElement(___item, String("v"));
    ___item3 = false;
}

void loop()
{
    ___item2 = _getLastOccuranceOfElement(___item, String("v"));
    ___item3 = ___item.empty();
}
