// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

std::list<double> item;
std::list<bool> item2;
std::list<String> item3;
std::list<unsigned int> item4;
int _led_L = 13;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    item = _createListRepeat(5,5);
    item2= _createListRepeat(5,true);
    item3= _createListRepeat(5,"123");
    item4= _createListRepeat(5,RGB(0x33,0xcc,0x00));
}

void loop()
{
}