// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <ArduinoSTL.h>
#include <list>
#include <NEPODefs.h>

RobertaFunctions rob;

std::list<String> ___item;
double ___item2;
bool ___item3;
int _led_L = 13;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    ___item = {"b", "v", "b"};
    ___item2 = _getFirstOccuranceOfElement(___item, String("v"));
    ___item3 = false;
}

void loop()
{
    ___item2 = _getLastOccuranceOfElement(___item, String("v"));
    ___item2 = null;
    ___item3 = (___item.size() == 0);
}
