// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <ArduinoSTL.h>
#include <list>
#include <NEPODefs.h>

RobertaFunctions rob;

std::list<double> item;
std::list<bool> item2;
std::list<String> item3;
std::list<unsigned int> item4;
int _led_L = 13;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    item = {0, 0, 0, 0};
    item2 = {true, false, true, false, true, false, false, true};
    item3 = {"a", "b", "c", "b"};
    item4 = {RGB(0xff, 0xcc, 0x33), RGB(0xff, 0xff, 0x33), RGB(0x66, 0x00, 0x00), RGB(0x00, 0x00, 0x99), RGB(0x66, 0x33, 0xff), RGB(0xff, 0x99, 0x00)};
}

void loop()
{
    Serial.println(_getListElementByIndex(_getSubList(item, 0, 2), 0));
    _setListElementByIndex(_getSubList(item3, 1, 2), 1, "b");
    Serial.println(((int) _getSubList(item2, 0, 2).size()));
    Serial.println(_getFirstOccuranceOfElement(_getSubList(item4, 2, 4), RGB(0x00, 0x00, 0x99)));
    delay(1000);
}
