#!/bin/bash

# The logic to start the application.
# The application will work only if it binds to $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT
# the application is expected in directory <GIT-REPO>/diy

echo "NOTE: deploying on LOCAL address ${OPENSHIFT_DIY_IP}:${OPENSHIFT_DIY_PORT}"

cd $OPENSHIFT_REPO_DIR/diy
chmod +x ./ora.sh
# mkdir logs

# nohup ./ora.sh --start-db >logs/db.logs &
# nohup ./ora.sh --ip $OPENSHIFT_DIY_IP --port $OPENSHIFT_DIY_PORT --start-db
nohup ./ora.sh --ip $OPENSHIFT_DIY_IP --port $OPENSHIFT_DIY_PORT --start-server openRoberta.properties
