create table USER (
  ID INTEGER not null generated by default as identity (start with 42),
  ACCOUNT varchar(255) not null,
  PASSWORD  varchar(255) not null,
  EMAIL varchar(255),
  ROLE varchar(32) not null,
  CREATED timestamp not null,
  LAST_LOGIN timestamp not null,
  TAGS varchar(16M), -- e.g. HERDER-GYMNASIUM KÖLN Q1 ED_SHEERAN
  
  primary key (ID)
)

create unique index accountIdx on USER(ACCOUNT)

create table PROGRAM (
  ID INTEGER not null generated by default as identity (start with 42),
  NAME varchar(255) not null,
  OWNER_ID INTEGER not null,
  PROGRAM_TEXT varchar(16M),
  CREATED timestamp not null,
  LAST_CHANGED timestamp not null,
  LAST_CHECKED timestamp,
  LAST_ERRORFREE timestamp,
  NUMBER_OF_BLOCKS INTEGER,
  TAGS varchar(16M), -- e.g. CAR AUTONOMOUS COOL 3WHEELS
  ICON_NUMBER integer not null,
  
  primary key (ID),
  foreign key (OWNER_ID) references USER(ID) ON DELETE CASCADE
)

create unique index progNameOwnerIdx on PROGRAM(NAME, OWNER_ID)

create table USER_PROGRAM (
  USER_ID INTEGER not null,
  PROGRAM_ID INTEGER not null,
  RELATION INTEGER not null, -- 1 READ access, 2 WRITE access, 4 DELETE right, (really? not yet used) 8 PROMOTE_READ right, 16 PROMOTE_WRITE right
 
  foreign key (USER_ID) references USER(ID) ON DELETE CASCADE,
  foreign key (PROGRAM_ID) references PROGRAM(ID) ON DELETE CASCADE
)

create table CONFIGURATION (
  ID INTEGER not null generated by default as identity (start with 42),
  NAME varchar(255) not null,
  OWNER_ID INTEGER not null,
  CONFIGURATION_TEXT varchar(16M),
  CREATED timestamp not null,
  LAST_CHANGED timestamp not null,
  LAST_CHECKED timestamp,
  LAST_ERRORFREE timestamp,
  TAGS varchar(16M), -- e.g. CAR AUTONOMOUS COOL 3WHEELS
  ICON_NUMBER integer not null,
  
  primary key (ID),
  foreign key (OWNER_ID) references USER(ID) ON DELETE CASCADE
)

create unique index confNameOwnerIdx on CONFIGURATION(NAME, OWNER_ID)
