// This file is automatically generated by the Open Roberta Lab.

#include <Arduino.h>
#include <NEPODefs.h>


std::list<double> ___item2;
int _led_L = 13;
void setup()
{
    pinMode(_led_L, OUTPUT);
    ___item2 = {0, 0, 0};
}

void loop()
{
    while ( true ) {
        break;
        delay(1);
    }
    for (int ___k0 = 0; ___k0 < 10; ___k0 += 1) {
        break;
        delay(1);
    }
    for (int ___i = 1; ___i < 10; ___i += 1) {
        break;
        delay(1);
    }
    for ( double ___item : ___item2 ) {
        break;
        delay(1);
    }
}
