// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <ArduinoSTL.h>
#include <list>
#include <NEPODefs.h>

RobertaFunctions rob;

std::list<double> item2;
int _led_L = 13;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    item2 = {0, 0, 0};
}

void loop()
{
    while ( true ) {
        break;
        delay(1);
    }
    for (int k0 = 0; k0 < 10; k0 += 1) {
        break;
        delay(1);
    }
    for (int i = 1; i < 10; i += 1) {
        break;
        delay(1);
    }
    for ( double item : item2 ) {
        break;
        delay(1);
    }
}