// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <ArduinoSTL.h>
#include <list>
#include <NEPODefs.h>

RobertaFunctions rob;

std::list<String> item;
double item2;
bool item3;
int _led_L = 13;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    item = {"b", "v", "b"};
    item2 = _getFirstOccuranceOfElement(item, String("v"));
    item3 = false;
}

void loop()
{
    item2 = _getLastOccuranceOfElement(item, String("v"));
    item2 = null;
    item3 = (item.size() == 0);
}