// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <ArduinoSTL.h>
#include <list>
#include <NEPODefs.h>

RobertaFunctions rob;

std::list<double> item;
double item2;
int _led_L = 13;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    item = {0, 0, 0};
    item2 = 0;
}

void loop()
{
    item2 = _getListElementByIndex(item, 0);
    item2 = _getListElementByIndex(item, item.size() - 1 - 0);
    item2 = _getListElementByIndex(item, 0);
    item2 = _getListElementByIndex(item, item.size() - 1);
    item2 = _getListElementByIndex(item, 0 /* absolutely random number */);
    item2 = _getAndRemoveListElementByIndex(item, 0);
    item2 = _getAndRemoveListElementByIndex(item, item.size() - 1 - 0);
    item2 = _getAndRemoveListElementByIndex(item, 0);
    item2 = _getAndRemoveListElementByIndex(item, item.size() - 1);
    item2 = _getAndRemoveListElementByIndex(item, 0 /* absolutely random number */);
    _removeListElementByIndex(item, 0);
    _removeListElementByIndex(item, item.size() - 1 - 0);
    _removeListElementByIndex(item, 0);
    _removeListElementByIndex(item, item.size() - 1);
    _removeListElementByIndex(item, 0 /* absolutely random number */);
    _setListElementByIndex(item, 0, 0);
    _setListElementByIndex(item, item.size() - 1 - 0, 0);
    _setListElementByIndex(item, 0, 0);
    _setListElementByIndex(item, item.size() - 1, 0);
    _setListElementByIndex(item, 0 /* absolutely random number */, 0);
    _insertListElementBeforeIndex(item, 0, 0);
    _insertListElementBeforeIndex(item, item.size() - 1 - 0, 0);
    _insertListElementBeforeIndex(item, 0, 0);
    item.push_back(0);
    _insertListElementBeforeIndex(item, 0 /* absolutely random number */, 0);
}