name: UnitTest

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]
    paths-ignore:
      - '.github/**'
      - 'Docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests for branch ${{ github.ref }} of repo ${{ github.repository }}
        run: echo "Run unit tests for branch ${{ github.ref }} of repo ${{ github.repository }}"
      - name: Checkout the branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with maven and run unit tests
        run: mvn --batch-mode clean install
