name: IntegrationTest-Dispatch-By-User

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch/ref for integration tests'
        required: true
        default: 'develop'
      oraccrsctag:
        description: 'Tag/version for the crosscompiler resources'
        required: true
        default: ${{ BASE_VERSION_MESSAGE }}

jobs:
  integration-test:
    runs-on: ubuntu-22.04
    container: openroberta/base-x64:${{ github.event.inputs.oraccrsctag }}
    steps:
      - name: branch ${{ github.event.inputs.branch }}, repo ${{ github.repository }}, ora-cc-rsc-tag ${{ github.event.inputs.oraccrsctag }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local maven repository
        uses: actions/cache@v3
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with maven and run integration tests
        run: mvn --batch-mode clean install -PrunIT
