name: create release for tag ORA_

on:
  push:
    tags:
      - ORA-*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "create release for branch ${{ github.ref }} and tag ${GITHUB_REF#refs/tags/ORA-} of repo ${{ github.repository }}"
      - name: Checkout the branch
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with maven
        run: mvn --batch-mode clean install -DskipTests
      - name: Build binaries and zip it
        run: ./ora.sh export openrobertalab_binaries gzip && zip -r openrobertalab_binaries.zip openrobertalab_binaries/
      - name: Build changelog
        uses: OpenRoberta/gh-actions-issue-changelog@v1
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.changelog.outputs.changelog}}
          files: openrobertalab_binaries.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2
      - name: Set up QEMU for multi architecture build
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get tag name 
        id: getTagName
        # Parse version number without ORA prefix
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/ORA-}
      - name: Build docker image for standalone
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Docker/openroberta/conf/y-standalone-lab/Dockerfile
          platforms: linux/arm/v7, linux/amd64
          push: true
          tags: openroberta/standalone:latest, openroberta/standalone:${{ steps.getTagName.outputs.tag }}
      - name: Build docker imaage for the lab server
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Docker/openroberta/conf/y-docker-for-lab-ci/Dockerfile
          platforms: linux/amd64
          push: true
          tags: openroberta/server:${{ steps.getTagName.outputs.tag }}
