// This file is automatically generated by the Open Roberta Lab.

#include <math.h>
#include <RobertaFunctions.h>   // Open Roberta library
#include <NEPODefs.h>

RobertaFunctions rob;

double item;
bool item2;
String item3;
unsigned int item4;
int _led_L = 13;
void setup()
{
    Serial.begin(9600); 
    pinMode(_led_L, OUTPUT);
    item = 0;
    item2 = true;
    item3 = "";
    item4 = RGB(0xFF, 0xFF, 0xFF);
}

void loop()
{
    item3 += String(item);
    item3 += String(item2);
    item3 += item3;
    item3 += String(item4);
}