package de.fhg.iais.roberta.ast.syntax;

/**
 * This class contains all Blockly name constants that are used in the XML representation of the block.
 */
public final class BlocklyConstants {
    public static final String ADD = "ADD";
    public static final String ELSE = "ELSE";
    public static final String THEN = "THEN";
    public static final String IF = "IF";
    public static final String ACTIVITY = "ACTIVITY";
    public static final String FLOW = "FLOW";
    public static final String TIMES = "TIMES";
    public static final String FOR_EACH = "FOR_EACH";
    public static final String FOR = "FOR";
    public static final String BY_ = "BY";
    public static final String DO = "DO";
    public static final String WAIT = "WAIT";
    public static final String COLOUR = "COLOUR";
    public static final String AT1 = "AT1";
    public static final String AT2 = "AT2";
    public static final String WHERE2 = "WHERE2";
    public static final String WHERE1 = "WHERE1";
    public static final String WHERE = "WHERE";
    public static final String AT = "AT";
    public static final String ITEM = "ITEM";
    public static final String TO_ = "TO";
    public static final String FROM_ = "FROM";
    public static final String HIGH = "HIGH";
    public static final String LOW = "LOW";
    public static final String MOD = "MOD";
    public static final String LIST_ = "LIST";
    public static final String DIVISOR = "DIVISOR";
    public static final String DIVISIBLE_BY = "DIVISIBLE_BY";
    public static final String NUMBER_TO_CHECK = "NUMBER_TO_CHECK";
    public static final String END = "END";
    public static final String FIND = "FIND";
    public static final String TEXT = "TEXT";
    public static final String PROPERTY = "PROPERTY";
    public static final String CONSTANT = "CONSTANT";
    public static final String NUM = "NUM";
    public static final String NOT = "NOT";
    public static final String BOOL = "BOOL";
    public static final String OP_ = "OP";
    public static final String B = "B";
    public static final String A = "A";
    public static final String SENSORTYPE = "SENSORTYPE";
    public static final String SENSORNUM = "SENSORNUM";
    public static final String KEY = "KEY";
    public static final String SENSORPORT = "SENSORPORT";
    public static final String SWITCH_BLINK = "SWITCH_BLINK";
    public static final String SWITCH_COLOR = "SWITCH_COLOR";
    public static final String VOLUME = "VOLUME";
    public static final String FILE = "FILE";
    public static final String DURATION = "DURATION";
    public static final String FREQUENCE = "FREQUENCE";
    public static final String Y_ = "Y";
    public static final String X_ = "X";
    public static final String PICTURE = "PICTURE";
    public static final String MODE_ = "MODE";
    public static final String ROW_ = "ROW";
    public static final String COL_ = "COL";
    public static final String OUT = "OUT";
    public static final String DEGREE = "DEGREE";
    public static final String MOTORROTATION = "MOTORROTATION";
    public static final String DISTANCE = "DISTANCE";
    public static final String DIRECTION = "DIRECTION";
    public static final String VALUE = "VALUE";
    public static final String POWER = "POWER";
    public static final String MOTORPORT = "MOTORPORT";
    public static final String VAR = "VAR";
}
